### ISSUE TITLE
Solution unsoundness in QF_ABV

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#4799] opened 2020-11-17 19:42 UTC
The bug requires the `push` at the beginning for it to trigger it. 
```
[530] % cvc4 --incremental -q small.smt2
unsat
[531] % z3release small.smt2
sat
[532] % cat small.smt2
(push)
(declare-fun a () (_ BitVec 32))
(declare-fun b () (Array (_ BitVec 32) (_ BitVec 32)))
(declare-fun c () (_ BitVec 32))
(declare-fun d () (_ BitVec 32))
(declare-fun q () (_ BitVec 32))
(declare-fun e () (Array (_ BitVec 32) (_ BitVec 32)))
(define-fun g () (_ BitVec 32) a)
(define-fun f () (_ BitVec 32) (_ bv4 32))
(define-fun aa () (Array (_ BitVec 32) (_ BitVec 32)) b)
(define-fun ab () (_ BitVec 32) (bvadd f g))
(define-fun j () (_ BitVec 32) c)
(define-fun h () Bool (= g j))
(define-fun i () Bool h)
(define-fun m () Bool i)
(define-fun k () (_ BitVec 32) d)
(define-fun l () Bool (= j k))
(define-fun p () (_ BitVec 32) (bvadd f j))
(define-fun n () (_ BitVec 32) q)
(define-fun o () Bool (= p n))
(define-fun ac () Bool (and l o))
(define-fun ad () Bool (and m ac))
(define-fun ae () (_ BitVec 32) (select aa n))
(define-fun af () (Array (_ BitVec 32) (_ BitVec 32)) e)
(define-fun ag () (Array (_ BitVec 32) (_ BitVec 32)) (store aa k ae))
(define-fun ah () Bool (= af ag))
(define-fun ai () Bool (and ad ah))
(define-fun aj () (_ BitVec 32) (select af j))
(define-fun ak () (_ BitVec 32) (select af ab))
(define-fun al () Bool (= aj ak))
(define-fun am () Bool (not al))
(define-fun an () Bool (and ai am))
(assert an)
(check-sat)
[533] %
```
OS: Ubuntu 18.04
Commit: 3bbdafb

**Comment by NikolajBjorner** [comment] 2020-11-28 02:02
duplicate of #4795

**Closed by NikolajBjorner** 2020-11-28 02:02 UTC
