### ISSUE TITLE
Timeout seems not to  work in this case(C API).

### ISSUE THREAD

**Issue by martin2011** [Z3Prover/z3#383] opened 2015-12-22 03:09 UTC
This instance involved `long double` constraint, and converse between `real` and `long double`.
Timeout is set as `10u` (which means 10 miliseconds) by setting param, while, after 339.04 second, it outputs `unknonwn`.  Is there something wrong?. I just want to get a result with timeout as I set instead of tens of thousands of times than my setting.
Environment is ubuntu-12.04-64, following attachment is the triggered code:

[timeout-instance.txt](https://github.com/Z3Prover/z3/files/69255/timeout-instance.txt)

**Comment by wintersteiger** [comment] 2015-12-22 12:44
Can you try just 10 instead of 10u? Last I checked we didn't support 'u'.

**Comment by NikolajBjorner** [comment] 2015-12-22 12:57
The problem is the following: you are calling the parameter ":timeout", call it "timeout" instead.
Z3 should complain that it does not know what ":timeout" is. The use of ":" is specific to SMT-LIB input format for symbols. After changing the name your example times out quickly.

**Comment by NikolajBjorner** [comment] 2015-12-22 15:54
It spends time in mpf.cpp, in the following loop:

          // Normalize
        while (m_mpq_manager.ge(sig, 2)) {
            m_mpq_manager.div(sig, mpq(2), sig);
            m_mpz_manager.inc(exp);
        }

sig is initially a large number, the time it takes to divide by 2 increases with the number of iterations.

**Comment by wintersteiger** [comment] 2015-12-23 00:04
Just to clarify: A timeout of "10u" is not supported (and u usually means "micro", not "milli"). However, the ANSI-C expression 10u can be used when using the C API, and it means _unsigned_ integer 10.

**Comment by wintersteiger** [comment] 2015-12-23 00:29
Nikolaj is right about the time being taken up in the simplifier; the conversion of the _real_ number 1.189731495357231765E4932 to a long double float is expensive because it's in base-10 (E) and floats are in base-2, and the exponent is a large number. The current implementation can perhaps be improved (but I won't be able to look into the details of that in the next few days) and we'll have to look into ways to make sure the timeouts are at least respected.

I would recommend not to construct a real numbered term at all, but to keep everything in floats whereever possible. This particular mode of operation (large numerals) can be improved, but the other (symbolic) conversions from/to reals will create very ugly non-linear constraints that will be very hard to solve (real-to-float) or they will cause the non-linear real solver will give up and return unknown (float-to-real). The default/usual mode of operation is to use 3 bit-vectors to construct float numerals (this is true for all of SMT but also for Z3), and that is always fast.

**Comment by martin2011** [comment] 2015-12-23 02:47
`u` is   used as one of ways to indicate this is an unsigned number, there is another way is to apply `(unsigned ) 10` to strongly convert to  `unsigned number`.   From my downloaded Z3 source ( at 2015-12-21), argument of  `set()`  function cant be set as no other than  `unsigned`, `double`, and `bool`. It is necessary to chose explicitly one of  `set()` instances (for example, using `(unsigned) 10` to choose the first one), or there is a syntax error.

>
"Can you try just 10 instead of 10u? Last I checked we didn't support 'u"

thanks  wintersteiger,  I tested  `(unsigned ) 10`, the problem still exist, but in this test, it outputed `unknown` after `348.72 s`

>
"I would recommend not to construct a real numbered term at all, but to keep everything in floats whereever possible"

I want to represent a `long double` const numeral. From the Z3 source code and document, floating-point number can be intialled  by  `Z3_mk_fpa_numeral_float()` and `Z3_mk_fpa_numeral_double()`. There is no way to initial `long double` const numeral ( is it going to update?). As a result, I represent it as `real` numeral and convert to `floating-point ast` . After all, there are differences between `long double` and `double` in varying compiler(gcc-4.8 with 64bit) .

Is there another to initial a `long double` numeral?

>
"the other (symbolic) conversions from/to reals will create very ugly non-linear constraints that will be very hard to solve (real-to-float)"

is this still existing in conversions between `bv ` and `float`?

**Comment by NikolajBjorner** [comment] 2015-12-23 02:54
Note that the discussion about 10u is settled. Christoph was referring to how we parse parameter values when they are passed as strings, not when they are passed over the API that accepts unsigned integers. There is no issue with 10u as you use it. Passing 15u even makes the timeout problem more consistent under debug builds.

**Comment by wintersteiger** [comment] 2015-12-23 12:55
Correct, there is no API function for quadruple precision floats, but it is not necessary. Like I said before, the "usual" way is to use three bit-vectors to construct numerals via the `(fp ...)` constructor in SMT2 and the corresponding C API function is `Z3_mk_fpa_fp`. There was a spurious assertion failure for these large numbers, but I just fixed that one. 

For example, in SMT2 language, this here:

    (set-logic QF_FP)
    (set-option :pp.fp_real_literals true)
    (declare-fun x () (_ FloatingPoint 15 113))
    (assert (= x (fp #b0 #b011111111111111 #x8000000000000000000000000000)))
    (check-sat)
    (get-model)

produces

    (model 
      (define-fun x () (_ FloatingPoint 15 113)
        ((_ to_fp 15 113) RTZ 1.5 0))
    )

The construction of numerals via bit-vectors is always fast because there is no actual conversion to be computed, as internally Z3 uses a 3 bit-vector representation as well.

However, the bit-blasting that happens later (conversion to SAT) can be inefficient or hard to solve too, especially when complicated operations are used on large floats, i.e., keep them as small as possible (prefer single over double if the precision isn't required). As a rough example of what to expect: symbolic representation of the float remainder `a % b` where `a`, `b` are double-precision, produces a SAT formula that is larger than 2 GB. The remainder is by far the worst of all operations though.

In general it's important to remembre that floating-point numbers are _not_ a cheap version of reals. Quite often the floating-point equivalent of a real numbered problem is much harder to solve, and also vice versa, sometimes the real-numbered equivalent of a floating-point problem can be harder to solve too. But, the very worst case is when floats are converted to reals and vice versa within one problem.

**Comment by martin2011** [comment] 2015-12-25 03:08
ok, thanks . BTW, I  have experienced  the discomfort of the `mode ()` operation.

**Comment by wintersteiger** [comment] 2016-01-06 13:56
Has this problem been resolved so that we close the issue, or are there fuerther problems?

**Comment by wintersteiger** [comment] 2016-01-11 18:58
I've rewritten the relevant parts of code that made this case so slow. It should be much faster now and return within the timeout, at least in release mode and for large, positive exponents.

**Comment by martin2011** [comment] 2016-01-12 06:31
Thanks, I have been used the suggested way, creating a  long double floating-point const from three bit-vectors. It is not an simple job. Especially, 1) there is no 128 bit integer can be used to shift to get the exponent and significant, 2)  we should distinguish denormed number and normal. 3) I assume number  is not inf/NaN. To date, it works.
 And I get the following finding:
1), the arguments of  `Z3_mk_fpa_fp()`  should be carefully due to the use of this function is not same as, at least, the document. In fact,  the second (`exponent`) and third (`significant`) is truly inverse. 

2)The `significant expr` with 112 bit will trigger the `SASSERT(mpzm.is_int64(r3.to_mpq().numerator()));` in `src/ast/rewriter/fpa_rewriter.cpp:767`. And, I commented it.

3) to denormed number , `Z3_mk_fpa_fp()` maybe need more test, I tested `2^(-130)` with 32 bit floating-point type. From IEEE-754, the exponent is  `-127`, and significant is `0.125`. However, I print it from `get_numeral_exponent/significant_string()`  there are  `-130` and `1`.

**Comment by wintersteiger** [comment] 2016-01-12 16:33
Yes, the bit-vector representation is a bit cumbersome in the beginning. I have a bit of a language problem with your comments though, it's very hard for me to understand what you are asking for. 

1) Which document? `Z3_mk_fpa_fp` has the same semantics as the `(fp ...)` operator in the [SMT FP theory](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml). I recently fixed a couple bugs in the API where the order of exponent and significand was reversed, but all of those should be fixed. 

2) I remember fixing a faulty assertion recently, that was also related to the exp/sig ordering. It's possible that by commenting the assertion you now end up with reversed arguments. 

3) Are you saying that 2^-130 is rounded to 2^-127, but later get_numeral_exponent will produce -130? 

Before looking at any of those issues, please update to the latest version (without commenting any assertions) and then check whether any of these issues still exist.

**Comment by martin2011** [comment] 2016-01-13 00:48
Ok, thanks. The experience was not with the latest version( with the version a week or two weeks ago), if there are fixed, just ignore it. I will test the latest version in the following.
>3) Are you saying that 2^-130 is rounded to 2^-127, but later get_numeral_exponent will produce -130?

yes, it was not described clearly with the context before.

 Actually, I just want to  check `Z3_mk_fpa_fa` when represented denormed number  is working correctly. It is hard to get a `long double` denormed number, as a result, I test `float` type,
 (at this point, all of these have no business with `long double`). After storing this denormed number (`2^-130`) in `ast`, the `exponent` should be `-127`, and significant `0.125`, however, I get `-130`, and `1`.

Similarly, it was tested with Z3 download in one or two weeks ago.

**Comment by wintersteiger** [comment] 2016-01-13 12:29
Thanks for the clarification on 3), it's highly likely that this is indeed a bug.

The reason there are no `long double` functions is that this dataype is not clearly defined, e.g., it can be 64, 80, 96, or 128 bits wide, depending on the platform (see e.g. [here](https://en.wikipedia.org/wiki/Long_double)). But, if you can think of a platform-independent way of providing quadruple precision floats, I'd be very happy to add that.

**Comment by wintersteiger** [comment] 2016-01-13 16:35
I updated those sig/exp extraction functions. There was no bug, they just returned _normalized_ results, but that was unclear from the documentation. I changed them all to consistently return non-normalized results. If we ever need normalization in the future, we can add a normalization flag to those functions, or add new functions altogether.

**Comment by martin2011** [comment] 2016-01-14 01:51
Ok, thanks.

>if you can think of a platform-independent way of providing quadruple precision floats, I'd be very happy to add that.

No, I just represent as 128 bit (16 byte), which is the width in my ubuntu-12.04-64 system. In the following,  I will try when I have time.

**Comment by wintersteiger** [comment] 2016-01-19 15:36
Looks to me like all problems have been fixed, so I'm closing this issue. Feel free to submit a new issue or ask me to repoen this one if further problems come up.

**Closed by wintersteiger** 2016-01-19 15:36 UTC
