### ISSUE TITLE
Segfault with trace=true, smt.arith.eager_eq_axioms false, auto_config false

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3582] opened 2020-03-30 14:46 UTC
The following trace shows Z3 triggering a segfault.
```
[1458] % z3 small.smt2
Segmentation fault
[1459] % 
[1459] % cat small.smt2
(set-option :trace true)
(set-option :smt.arith.eager_eq_axioms false)
(set-option :auto_config false)
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun e () Real)
(declare-fun g () Real)
(assert
 (not
 (exists ((f Real))
  (or (and (>= f b g) (>= a 0) (< e g))
  (>= (+ (* (/ 0 (mod 0 b))) (mod (/ 0 (+ (/ 0 d) a)) (/ 1 c))) g)))))
(check-sat)
[1460] %
```

OS: Ubuntu 18.04
Commit: 9be7bda

**Comment by NikolajBjorner** [comment] 2020-03-30 23:51
seems to be a duplicate of bug triggered by trace

**Closed by NikolajBjorner** 2020-03-30 23:51 UTC
