### ISSUE TITLE
Assertion violation at smt/theory_str_mc.cpp:627 (z3str3)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4285] opened 2020-05-12 04:06 UTC
~~~~
(set-option :smt.string_solver z3str3)
(declare-const Str17 String)
(assert (>= (str.len Str17) (* 46 332 764 43 46)))
(check-sat)
~~~~

z3 (commit a14c2a3) 
~~~~
ASSERTION VIOLATION
File: ../src/smt/theory_str_mc.cpp
Line: 627
varLen_value.is_unsigned() && "actually arithmetic solver can assign it a very large number"
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

**Comment by mtrberzi** [comment] 2020-05-13 17:04
Duplicate of #3769

**Closed** 2020-05-16 01:42 UTC
Labels: duplicate, string, z3str3
