### ISSUE TITLE
Refutation soundness issue on a QF_NRA formula

### ISSUE THREAD

**Issue by zhendongsu** [Z3Prover/z3#5161] opened 2021-04-08 19:28 UTC
```
[685] % cvc4 -q small.smt2
sat
[686] % z3release small.smt2
sat
[687] % z3release nlsat.reorder=false nlsat.simplify_conflicts=false rewriter.flat=false small.smt2
unsat
[688] % cat small.smt2
(declare-fun a () Real)
(declare-fun b () Real)
(assert (>= (* a a) 0))
(assert (> 0 (* a (- 1 a))))
(assert (> 0 (- (ite (= a 0) 0 1))))
(assert (> 0 (+ a (* b (- b)))))
(assert (>= a 0))
(check-sat)
[689] % 
```
Commit: 44156f9f556bab9f2f4343c9bca34e33f6b380d0

The issue does not reproduce if `(set-logic QF_NRA)` is added to the formula.

**Comment by NikolajBjorner** [comment] 2021-04-08 20:09
Run with -v:10, shows nlsat portion is to blame. smt.arith.nl.nra=false results in unknown.
Almost for sure a duplicate of other nlsat bugs (many are now filed as separate bugs but really trace back to a very old and open bug). 

BTW, Is anybody interested in (small) $ for a bug bounty on this one?

**Comment by NikolajBjorner** [comment] 2021-04-08 21:55
duplicate #2650

**Closed by NikolajBjorner** 2021-04-08 21:55 UTC
Labels: nlsat
