### ISSUE TITLE
QF_S, soundness bug str.indxeof, str.at, str.substr

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2838] opened 2020-01-03 18:49 UTC
Consider the following formula

```
(declare-fun a () String)   
(assert  (and  (= (ite (= (str.at (str.substr a (+ (str.indexof a "=" 0) 1)                       
              (- (str.len a) (+ (str.indexof a "=" 0) 1))) (- (str.len (str.substr a (+ (str.indexof a "=" 0) 1) 
              (- (str.len a) (+ (str.indexof a "=" 0) 1)))) 1)) "") 1 0) 0) 
              (not (= (ite (= (str.at (str.substr a (- (str.indexof a "=" 0) 1)               
              (- (str.len a) (+ (str.indexof a "=" 0) 1))) 0) " ") 1 0) 0))))            
(check-sat)
```

Z3 reports this formula to be `unsat` although e.g.
```
(model
(define-fun a () String " =A")
)
```
is a model which Z3 accepts.

OS: Ubuntu 18.04
Revision: 0b486d2

**Comment by NikolajBjorner** [comment] 2020-01-25 00:06
it is fixed #2860 is a duplicate of this.

**Closed by NikolajBjorner** 2020-01-25 00:06 UTC
Labels: string
