### ISSUE TITLE
Free variables in interpolants

### ISSUE THREAD

**Issue by kenmcmil** [Z3Prover/z3#1269] opened 2017-09-25 19:41 UTC
Free variables come out in interpolants. 

Example:

`
(declare-const v!0 (Array Int Int))
(declare-const v!1 Int)
(declare-const v!2 Int)
(declare-const v!3 (Array Int Int))
(declare-const v!4 (Array Int Int))
(declare-fun len ((Array Int Int)) Int)

(compute-interpolant (and (= v!4 v!3)
     (= (len v!4) 2)
     (= (select v!4 0) 4)
     (= (select v!4 1) 4)
     (interp (and (= (len v!3) (- v!2 v!1))
                  (forall ((i Int))
                    (=> (and (>= i v!1) (< i v!2))
                        (= (select v!3 (- i v!1)) (select v!0 i))))
                  (interp (and (= (len v!0) 3)
                               (= (select v!0 0) 1)
                               (= (select v!0 1) 2)
                               (= (select v!0 2) 3)))
                  (interp (and (= v!1 0)))
                  (interp (and (= v!2 2)))))))
`
This produces the following output:

unsat
(= 1 (select v!0 0))
(let ((a!1 (= (<= (+ v!1 (* (- 1) (:var 0))) 0) (>= (:var 0) 0))))
  (and a!1 (= 0 v!1)))
(= (<= (+ v!2 (* (- 1) (:var 0))) 0) (>= (:var 0) 2))
(= 1 (select v!3 0))

The problem appears to be free variables that are introduced in proofs involving quantifiers and arithmetic. Since these symbols aren't in the vocabulary of the original formula, they could be soundly quantified universally.  However, the reason these variables come out in the interpolant seems to be the rule that the conclusion of a sub-proof in the A vocabulary can be taken as an interpolant. This rule doesn't take into account free variables.

**Comment by NikolajBjorner** [comment] 2017-09-25 20:09
This is a duplicate of two bugs filed by Jasmin Blanchette. It will be fixed when we add lambdas, see the branch bind under https://github.com/nikolajbjorner/z3.git. You will have to ensure interpolant reconstruction works with binders.

**Comment by kenmcmil** [comment] 2017-09-25 21:39
Oh boy, we get lambdas?

Meanwhile, I have fixed this by just universally quantifying the free variables. I'm a little worried about what happens if you have two with the same DeBruijn index and different sorts. Horrible things, I assume. 

Pull request is coming...

**Comment by mschwerhoff** [comment] 2017-10-02 09:46
@NikolajBjorner Lambdas, higher-order functions? Sounds intriguing! Any docs or tests or something I could look at to get a sneak preview?

**Comment by NikolajBjorner** [comment] 2017-10-02 14:37
They are not ready yet.

**Comment by NikolajBjorner** [comment] 2018-07-05 20:21
fixed with addition of lambda

**Closed by NikolajBjorner** 2018-07-05 20:21 UTC

**Comment by NikolajBjorner** [comment] 2018-07-06 16:55
but why?

Added in extension to arrays as Z3 already treats arrays as function 
spaces (using the as-array operator).

Two examples:
https://github.com/Z3Prover/z3test/blob/master/regressions/smt2/ho.smt2
https://github.com/Z3Prover/z3test/blob/master/regressions/smt2/memset.smt2

Support is very rudimentary, and mostly lambdas are syntactic sugar, which may be adequate.
The ho.smt2 example illustrates one capability of extensional reasoning that goes slightly beyond the
realm of marcos.

Internalization prior to search performs a closure conversion, such that (lambda (bound) (body bound free)) 
is represented as nLambda(free), and the equation:
 (forall (bound) (= (select (nLambda free) bound) (body bound free)))
The equation is tagged so that MBQI doesn't get trapped satisfying it.

**Comment by mschwerhoff** [comment] 2018-07-11 09:58
I guess I'm just easily intrigued :-)

"Added in extension to arrays": does that mean that they are only usable in combination with arrays, i.e. not with uninterpreted functions? E.g. is something like 

    (assert (forall ((F (Int → Bool))) (=> (F x) (F y))))

supported?

**Comment by NikolajBjorner** [comment] 2018-07-11 13:50
What is (Int → Bool)? SMT-LIB2 does not even have such syntax. OTOH, there is syntax, such as (Array D R), or I could have  introduced another type constructor, -> or => and written (-> D R), but we already have arrays and already treat them semantically as function spaces. The puritan approach would be to separate the first-order theory of arrays from function spaces, yet I am not sure why this would be useful.

**Comment by mschwerhoff** [comment] 2018-07-12 07:35
Sorry for the confusion: I made up the syntax (Int → Bool) and intended it to denote the type of functions from Int to Bool. The above was meant to say "forall functions F from Int to Bool, F(X) ==> F(y)", where F could be any uninterpreted function (e.g. `(declare-fun foo (Int) Bool)`).
