### ISSUE TITLE
Soundness/Performance Bug with fp.sqrt

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#222] opened 2015-09-18 22:47 UTC
On the `unstable` branch, at commit d4b66538f93a4e9b255690bf127ffae3f4cc493c, consider the following input:

```
(set-logic QF_FP)
(declare-fun x0 () (_ FloatingPoint 3 4))
(check-sat)
(assert (= (fp.sqrt RNE x0) (fp.sqrt RNE (fp #b0 #b000 #b001))))
(check-sat)
```

Z3 incorrectly reports that this is `unsat`.  In this case, it's not necessary to reason about what `fp.sqrt` does in order to see that this is incorrect; if it is treated as an uninterpreted function, then a satisfying result would be `x0 =  (fp #b0 #b000 #b001)`.

The `unsat` result is specific to the small number of bits used.  If things are expanded to be 32 bits, then Z3 reports `sat`.  Such an expanded version is shown below:

```
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun x0 () Float32)
(check-sat)
(assert (= (fp.sqrt RNE x0) (fp.sqrt RNE (fp #b0 #b00000000 #b00000000000000000000001))))
(check-sat)
(get-model)
```

However, I noticed in this situation that Z3 hangs relative to MathSAT5, with MathSAT5 taking under 100ms, whereas Z3 takes nearly 9 seconds.  I'm not sure if this is related to the same underlying issue or not, but I figured it's worth reporting.

**Comment by kyledewey** [comment] 2015-09-18 22:51
On the initial uses of `(check-sat)` before the `assert`: removing these has no effect on the soundness issues reported (still `unsat` on small problems and `sat` on larger problems), but it does dramatically influence performance (Z3 is more on par with MathSAT5 without the initial `(check-sat)`).

**Comment by wintersteiger** [comment] 2015-09-21 15:52
This looks like a bug, thanks for the report. 

Regarding performance: Z3 will try to use a solver that doesn't support incremental queries when there is only one `(check-sat)` command. When it sees the second `(check-sat)`, it will automatically switch to a solver that supports those features, but which is usually slower (in this case likely because the incremental SAT solver does not implement many features that in a non-incremental setting improve performance). So, this is expected, but it may change in the future when we get the fast SAT solver to do incrementality without a big performance penalty).

**Comment by wintersteiger** [comment] 2015-09-21 20:00
This is now fixed in unstable and from my perspective no tests fail. Could you check and confirm that fp.sqrt now works as intended?

**Comment by kyledewey** [comment] 2015-09-21 21:13
Sure; I'll be running that within the next few days.

**Comment by wintersteiger** [comment] 2015-09-29 10:34
Closing this as fixed. If new problems come up please open a new issue or ask us to re-open this one.

**Closed by wintersteiger** 2015-09-29 10:34 UTC
Labels: bug
