### ISSUE TITLE
Soundness bug in QF_FP

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2925] opened 2020-02-02 11:42 UTC
Hi,
z3 gives wrong answer on the following file:

[qf_fp.smt2](https://github.com/Z3Prover/z3/files/4144008/qf_fp.smt2.zip)

All the formulas at every level in the assertion stack are satisfiable, but z3 returns:

sat
unsat

While CVC4 return:

sat
sat

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

commit: 3dc822c12706e2cfe3dd392747098b6c93295881

**Comment by wintersteiger** [comment] 2020-02-03 11:14
Likely a duplicate of #2827 (in progress).

**Comment by numairmansur** [comment] 2020-03-15 15:14
This seems fixed in the latest release @NikolajBjorner

**Comment by wintersteiger** [comment] 2020-07-16 12:05
After additional checks, I can confirm this is fixed.

**Closed by wintersteiger** 2020-07-16 12:05 UTC
