### ISSUE TITLE
Soundness bug in QF_UFLIA

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2826] opened 2019-12-26 04:21 UTC
Hi,
On the latest nightly build , z3 gives wrong answer on the following example

[qf_uflia.smt2.zip](https://github.com/Z3Prover/z3/files/4001347/qf_uflia.smt2.zip)
.
All the formulas at every level in the assertion stack are satisfiable.
On the attached file (QF_UFLIA), z3 returns:

$ /z3-nightly/bin/z3 qf_uflia.smt2

sat
sat
sat
sat
sat
unsat

CVC4 return the correct result:
sat
sat
sat
sat
sat
sat

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

**Comment by NikolajBjorner** [comment] 2019-12-26 22:47
triage suggests it is a duplicate of #2829

**Closed** 2019-12-30 00:34 UTC
