### ISSUE TITLE
z3str3 ast_manager LEAKED 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2668] opened 2019-10-30 21:34 UTC
Hi,
For this formula, 
```
(declare-fun a () String)
(declare-fun b () String)
(declare-fun c () String)
(declare-fun aa () String)
(assert (>= (- (str.indexof (str.substr a 0 (str.len (str.substr b (str.len aa) (str.len c)))) "*" 0) 0) 0))
(assert (>= (- (str.indexof (str.substr b 0 (str.len c)) "*" 0) 0) 0))
(assert (str.in.re b (re.++ (str.to.re aa) (str.to.re c))))
(check-sat)
```
z3str3 will throw out the following message:
```
$ z3 smt.string_solver=z3str3 file.smt2
unknown
ast_manager LEAKED: 13
Leaked: #1140 := (str.++ t0!tmp12[t0!tmp12] $$_str9!tmp48[$$_str9!tmp48])
(= x3!tmp20[x3!tmp20] #1140)
id: 1615
```

OS: Ubuntu 18.04
Revision: 18b8089

**Comment by NikolajBjorner** [comment] 2019-11-14 02:57
@mtrberzi

**Comment by NikolajBjorner** [comment] 2019-11-22 07:04
I don't get the leak, but there is one suggestion:

Change

    app * theory_str::mk_nonempty_str_var() {

to

   app_ref theory_str::mk_nonempty_str_var() {

where 
        app* a = mk_fresh_const(name.c_str(), string_sort);

gets replaced by

        app_ref a(mk_fresh_const(name.c_str(), string_sort), m);

There are a few places where mk_nonempty_str_var() is called and the result is assigned to expr*.
This has to be changed to expr_ref or app_ref assignment.

**Comment by mtrberzi** [comment] 2019-11-22 19:10
That sounds sensible. I'll open a new PR for it shortly.

**Comment by NikolajBjorner** [comment] 2019-11-29 19:21
I cannot reproduce the leak message any longer

**Closed by NikolajBjorner** 2019-11-29 19:21 UTC
Labels: string, z3str3
