### ISSUE TITLE
Assertion Violation on NRA formula at ./src/math/polynomial/polynomial.cpp Line: 801

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2926] opened 2020-02-02 13:57 UTC
Hi,
For this formula
```
(declare-fun a () Real) 
(declare-fun b () Real) 
(declare-fun c () Real) 
(declare-fun n () Real) 
(declare-fun o () Real) 
(declare-fun d () Real) 
(declare-fun p () Real) 
(declare-fun q () Real)
(declare-fun e () Real) 
(declare-fun f () Real) 
(declare-fun r () Real) 
(declare-fun g () Real) 
(declare-fun s () Real) 
(declare-fun h () Real) 
(declare-fun i () Real) 
(assert (not (exists ((j Real)) (let ((?k (>= r 0)) (?l (<= r (/ 0 0))) (?t (/ (* r r) (* 2 (- (- b (- 680.2932226634903)) o)))) (?m (* (/ 1 2) (+ (* (* 2 f) r) 0)))) (=>  (and (and (and  (and (and (and  (and  (and (=> (and (<= 0 j f)) (and  (<= j g))) (>= f 0)) (= (/ c d) s)) (> (/ a n) (+ (+ s ?t) (* (+ (/ q e) 1) (+ (* (/ q 2) (* g g)) (* g r)))))) ?k) ?l) (< (/ a n) i)) (> (- (- b (- 680.2932226634903)) o) 0)) (>= q 0)) (or (or (= h 2) (< p ?m)) (> (/ a n) (+ ?m ?t)))))))) 
(assert (= a (* n p))) 
(assert (= p (/ a n))) 
(assert (= b (+ (+ e o) (- 680.2932226634903))))
(assert (= d (/ c p))) 
(assert (= p (/ c d)))
(check-sat)
```
z3 throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/math/polynomial/polynomial.cpp
Line: 801
m_monomials.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Revision: 805ac74

**Comment by NikolajBjorner** [comment] 2020-02-03 04:05
produces unsat

**Comment by muchang** [comment] 2020-02-04 03:39
Hi Nikolaj,
I built z3 with configure:`./configure -d`.
z3 can produce unsat but throws out an assertion violation on my side:
```
$./z3  test.smt2 
unsat
ASSERTION VIOLATION
File: ../src/math/polynomial/polynomial.cpp
Line: 801
m_monomials.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
A
$cat test.smt2
(declare-fun a () Real) 
(declare-fun b () Real) 
(declare-fun c () Real) 
(declare-fun n () Real) 
(declare-fun o () Real) 
(declare-fun d () Real) 
(declare-fun p () Real) 
(declare-fun q () Real)
(declare-fun e () Real) 
(declare-fun f () Real) 
(declare-fun r () Real) 
(declare-fun g () Real) 
(declare-fun s () Real) 
(declare-fun h () Real) 
(declare-fun i () Real) 
(assert (not (exists ((j Real)) (let ((?k (>= r 0)) (?l (<= r (/ 0 0))) (?t (/ (* r r) (* 2 (- (- b (- 680.2932226634903)) o)))) (?m (* (/ 1 2) (+ (* (* 2 f) r) 0)))) (=>  (and (and (and  (and (and (and  (and  (and (=> (and (<= 0 j f)) (and  (<= j g))) (>= f 0)) (= (/ c d) s)) (> (/ a n) (+ (+ s ?t) (* (+ (/ q e) 1) (+ (* (/ q 2) (* g g)) (* g r)))))) ?k) ?l) (< (/ a n) i)) (> (- (- b (- 680.2932226634903)) o) 0)) (>= q 0)) (or (or (= h 2) (< p ?m)) (> (/ a n) (+ ?m ?t)))))))) 
(assert (= a (* n p))) 
(assert (= p (/ a n))) 
(assert (= b (+ (+ e o) (- 680.2932226634903))))
(assert (= d (/ c p))) 
(assert (= p (/ c d)))
(check-sat)
```

**Comment by NikolajBjorner** [comment] 2020-02-04 03:43
the assert is almost for sure timing related. It doesn't repro in my setup. 
It is also benign because the memory gets reclaimed correctly in the small object allocator.
So could you create a reliable repro? I will close until then.

**Comment by muchang** [comment] 2020-02-10 12:58
Hi Nikolaj, 
I double-checked the bug on several machines, it can be consistently reproduced.
The OS we used is Ubuntu 18.04, it may be an OS-specific bug.
Could you try it on Ubuntu OS or a similar OS?

**Comment by zhendongsu** [comment] 2020-02-10 16:42
I'm also able to reproduce the crash reliably on a Ubuntu machine (18.04): 
```
[506] % for i in $(seq 1 5); do
> timeout -s 9 8 z3 small.smt2
> done
unsat
ASSERTION VIOLATION
File: ../src/math/polynomial/polynomial.cpp
Line: 801
m_monomials.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
Killed
unsat
ASSERTION VIOLATION
File: ../src/math/polynomial/polynomial.cpp
Line: 801
m_monomials.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
Killed
unsat
ASSERTION VIOLATION
File: ../src/math/polynomial/polynomial.cpp
Line: 801
m_monomials.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
Killed
unsat
ASSERTION VIOLATION
File: ../src/math/polynomial/polynomial.cpp
Line: 801
m_monomials.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
Killed
unsat
ASSERTION VIOLATION
File: ../src/math/polynomial/polynomial.cpp
Line: 801
m_monomials.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
Killed
[507] % 
```

**Comment by NikolajBjorner** [comment] 2020-03-12 18:25
closing: it is related to a timeout and here the destructor is checking that memory was reclaimed in a normal way. The memory will be reclaimed anyway by the destructor, so the behavior in release mode is correct.

**Closed by NikolajBjorner** 2020-03-12 18:25 UTC
Labels: no-repro
