### ISSUE TITLE
Z3 optimization returns Unknown 

### ISSUE THREAD

**Issue by mm95** [Z3Prover/z3#1011] opened 2017-05-08 05:53 UTC
Hello,

I used Z3 optimizations for a small benchmark (binary search) specified in SMT2 formula.
First, I get the minimum and maximum of a special variable (output) in formula, 
then create new constraint that represents "output" must be bigger than its min value and smaller than its max value. This constraint is added to negation of formula. But when I want from optimizer to return me the   min and max value of "output" in negation of formula, it return unknown.
The log file of Z3 from the start of program was attached.
Thanks so much.
[z3.log.txt](https://github.com/Z3Prover/z3/files/982465/z3.log.txt)

**Comment by NikolajBjorner** [comment] 2017-05-23 16:02
I have been unable to reproduce what your issue is from the low level log. If you have an smt2 file it would be perhaps easier to figure out what is going on. Do you have non-linear arithmetic? This is a common reason why Z3 returns unknown.

**Comment by NikolajBjorner** [comment] 2018-07-10 10:13
closing as there is no repro to work from and Z3 has changed significantly since the bug was reported.

**Closed by NikolajBjorner** 2018-07-10 10:13 UTC
Labels: no-repro
