### ISSUE TITLE
Incorrect model on QF_NRA formula

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3229] opened 2020-03-10 12:27 UTC
Hi,
For this formula:
```
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(assert (= c 0))
(check-sat)
(assert (> (* a b) 0))
(check-sat)
(get-model)
```
Z3  gives an invalid model:
```
(model 
  (define-fun c () Real
    0.0)
  (define-fun b () Real
    0.0)
  (define-fun a () Real
    0.0)
)
```
if I feed this model to the formula, Z3 reports unsat.

OS: Ubuntu 18.04
Commit: a51d65d

**Comment by NikolajBjorner** [comment] 2020-03-10 21:10
duplicate of #3230

**Closed by NikolajBjorner** 2020-03-10 21:10 UTC
