### ISSUE TITLE
ASSERTION VIOLATION, File: ../src/qe/qe_mbp.cpp Line: 404

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#7259] opened 2024-06-19 02:33 UTC
Hi,
For this instance, z3 https://github.com/Z3Prover/z3/commit/bf3615d4fbc017f0da036ac2fe3a3dce09922cd9 debug build
```
$ cat small.smt2 
(declare-fun v () (Array Bool Bool))
(assert (forall ((a Int) (va (Array Bool Bool))) (or (= a 0) (va (= v va)))))
(check-sat-using qsat)
$ z3 small.smt2 
ASSERTION VIOLATION
File: ../src/qe/qe_mbp.cpp
Line: 404
Failed to verify: !model.is_false(f)

```

**Comment by NikolajBjorner** [comment] 2024-06-19 22:38
this has to be a duplicate of another similar bug for qe_qel and finite domain arrays.

**Closed by NikolajBjorner** 2024-06-19 22:38 UTC

**Comment by levnach** [comment] 2026-06-07 15:48
z3 from the Nightly build crashes on the following input file(s).

**z3 Nightly build:** tag `Nightly`, commit [`241c6211d`](https://github.com/Z3Prover/z3/commit/241c6211d6e0da7dd4ef8904314aa3db0775db30) (`Z3 version 4.17.0`)

**Crashing input(s):**
- [`inputs/issues/iss-7259/small.smt2`](https://github.com/Z3Prover/bench/blob/main/inputs/issues/iss-7259/small.smt2)

z3 crashes when run on the file(s) above.

The crash is observed on Ubuntu 24.04.4 LTS (x86_64).

**Comment by NikolajBjorner** [comment] 2026-07-13 18:52
Still reproduces on current master (Z3 4.17.0, build hashcode `038b367d6`), but the assertion has **moved**: the failure is now at `qe_mbp.cpp:412` (was `:404`):

```
ASSERTION VIOLATION
File: src/qe/qe_mbp.cpp
Line: 412
Failed to verify: !model.is_false(f)
```

Reproduced with the reported input (`check-sat-using qsat`, assertions-enabled build), crashing in ~1.8s. So the underlying MBP model-validation issue is not yet fixed.
