### ISSUE TITLE
dom-simplify invalid model on UFLIA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3075] opened 2020-02-23 05:05 UTC
Hi,
For this formula:
```
(declare-fun c (Int) Int)
(declare-fun br (Int) Int)
(declare-fun cn (Int) Int)
(declare-fun cm (Int) Int)
(declare-fun a (Int) Int)
(declare-fun g () Int)
(declare-fun h () Int)
(declare-fun d () Int)
(declare-fun j () Int)
(declare-fun f () Int)
(declare-fun co () Int)
(declare-fun k () Int)
(declare-fun l () Int)
(declare-fun m () Int)
(declare-fun cp () Int)
(assert
(let ((aa j) (e co) (b k) (i f) (n (br co)) (ba d)
      (bf (c l)) (bg m) (bh (c cp)) (bi (cn g))
      (bj cn) (bn (cn k)) (bt cm) (bx (cm j)) (cg (a l)))
 (and
  (or
   (and
    (or
     (and
      (or
       (and
        (or
         (and
          (or
           (and
            (or
             (and
              (or (= (a h) k) (= (a h) l) (= n h))
              (= (a j) f l) (distinct (a co) m) (= (a k) f k))
             (distinct n j) (= cg f) (distinct cg co)
             (= cg k) (= cg l) (= cg m) (= cg cp))
            (= (a cp) cp) (distinct g h)
            (distinct g d)))
          (distinct g l) (distinct h f) (distinct d k) (distinct d l)))
        (distinct d cp) (distinct j f) (distinct j co) (distinct j k)
        (distinct j l) (distinct j m) (= j cp))
       (distinct f m) (distinct f cp))
      (distinct co k) (distinct k cp) (distinct l m) (distinct l cp))
     (> g 1))
    (<= 0 h 11) (< k 1) (<= 0 m)))
  (= (c (c (a (ite (< (- g cp) 11) (- g cp) g))))
   (c (c (a (ite (< (+ g h) 11) (+ g h) g))))))))
(check-sat-using (then dom-simplify smt))
```
Z3  gives an invalid model:
```
(define-fun f () Int
    (- 58574))
  (define-fun g () Int
    3)
  (define-fun k () Int
    (- 72022))
  (define-fun l () Int
    (- 2))
  (define-fun cp () Int
    (- 3))
  (define-fun m () Int
    0)
  (define-fun d () Int
    (- 4))
  (define-fun h () Int
    6)
  (define-fun j () Int
    (- 3))
  (define-fun co () Int
    0)
  (define-fun a ((x!0 Int)) Int
    (ite (= x!0 6) (- 1)
    (ite (= x!0 (- 72022)) (- 58573)
    (ite (= x!0 (- 3)) (- 3)
    (ite (= x!0 9) 59991
      1)))))
  (define-fun br ((x!0 Int)) Int
    (- 4))
  (define-fun c ((x!0 Int)) Int
    (ite (= x!0 0) 26829
    (ite (= x!0 59991) 22797
      0)))
  (define-fun cn ((x!0 Int)) Int
    0)
  (define-fun cm ((x!0 Int)) Int
    0)
```
if I feed this model to the formula, Z3 throws out an error:
```
(error "line 40 column 10: unknown constant cn")
sat
```
and CVC4 gives unsat.

OS: Ubuntu 18.04
Commit: c71da17

**Comment by NikolajBjorner** [comment] 2020-02-24 17:04
almost for sure duplicate of #3081

The old arithmetic solver is fine: z3 3075.smt2 /v:10 /st smt.arith.solver=2 model_validate=true smt.auto_config=false

**Closed** 2020-02-25 10:18 UTC
