### ISSUE TITLE
String theory, buggy model

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1555] opened 2018-03-26 22:44 UTC
For this input:

```
(set-logic ALL)
(declare-fun s0 () String)
(declare-fun s1 () String)
(declare-fun s2 () Int)
(define-fun s4 () Bool (>= s2 0))
(define-fun s5 () Int (str.len s0))
(define-fun s6 () Bool (< s2 s5))
(define-fun s7 () Bool (and s4 s6))
(define-fun s8 () Bool (not s7))
(define-fun s9 () Int (str.indexof s0 s1 s2))
(define-fun s10 () Int (- s5 s2))
(define-fun s11 () String (str.substr s0 s2 s10))
(define-fun s12 () Int (str.indexof s11 s1))
(define-fun s13 () Int (+ s2 s12))
(define-fun s14 () Bool (= s9 s13))
(define-fun s15 () Bool (or s8 s14))
(assert (not s15))
(check-sat)
(get-value (s0))
(get-value (s1))
(get-value (s2))
```

Z3 produces:

```
sat
((s0 "\x01\x00\x00\x00\x00"))
((s1 "\x00"))
((s2 1))
```

However, I think the input is actually `unsat`. (I can try to "minimize" it if necessary, I haven't tried hard in case the bug is obvious to you. Let me know.) In any case, the given model is not correct. Indeed, z3 confirms the issue itself:

```
$ z3 model_validate=true b.smt2
sat
(error "line 18 column 10: an invalid model was generated")
((s0 "\x01\x00\x00\x00\x00"))
((s1 "\x00"))
((s2 1))
```

**Comment by NikolajBjorner** [comment] 2018-03-26 23:12
Duplicate of #1397

**Closed by NikolajBjorner** 2018-03-26 23:12 UTC
Labels: duplicate
