### ISSUE TITLE
Incorrect bound variable handling in quant-intro proofs

### ISSUE THREAD

**Issue by blanchette** [Z3Prover/z3#1201] opened 2017-08-08 15:16 UTC
Consider the following problem:

```
(set-option :produce-proofs true)
(set-logic AUFLIA)
(declare-sort A$ 0)
(declare-sort B$ 0)
(declare-sort C$ 0)
(declare-sort D$ 0)
(declare-sort E$ 0)
(declare-fun f$ (A$ B$) Bool)
(declare-fun n$ () A$)
(assert (! (not (=> (forall ((?v0 A$)) (and (forall ((?v1 B$)) (f$ n$ ?v1)) (forall ((?v1 C$) (?v2 B$)) (f$ ?v0 ?v2)))) (forall ((?v0 E$) (?v1 D$) (?v2 A$)) (or (= ?v2 n$) (forall ((?v3 D$) (?v4 B$)) (f$ ?v2 ?v4)))))) :named a0))
(check-sat)
(get-proof)

```

Invoking Z3 (repository version or 4.4.0, no difference), the proof contains a term of the form `f$ ?v2 ?v2`, which arises as a result of a quant-intro rule. I've enclosed the proof below. However, the sort constraints on `f$` make such a term impossible. Looking more closely at the proof, it would appear that there is some confusion between two bound variables with the same name, one shadowing the other, arising in the "(quant-intro @x59 (= $x42 $x60))" step.

Unsurprisingly, this leads to a reconstruction failure in Isabelle/HOL. The bug occurs very rarely and is not critical for us.

```
unsat
((set-logic AUFLIA)
(declare-fun ?v2!1 () B$)
(declare-fun ?v2!0 () A$)
(proof
(let (($x109 (f$ ?v2!0 ?v2!1)))
(let (($x111 (not $x109)))
(let (($x220 (f$ n$ ?v2!1)))
(let (($x224 (not $x220)))
(let (($x547 (or $x224 $x111)))
(let (($x98 (= ?v2!0 n$)))
(let (($x105 (not $x98)))
(let (($x114 (and $x105 $x111)))
(let (($x63 (forall ((?v2 A$) )(! (let (($x46 (forall ((?v2 B$) )(! (f$ ?v2 ?v2) :qid k!10))
))
(or (= ?v2 n$) $x46)) :qid k!10))
))
(let (($x81 (not $x63)))
(let (($x100 (forall ((?v2 B$) )(! (f$ ?v2!0 ?v2) :qid k!10))
))
(let ((@x116 (nnf-neg (refl (~ $x105 $x105)) (sk (~ (not $x100) $x111)) (~ (not (or $x98 $x100)) $x114))))
(let (($x52 (forall ((?v0 A$) )(! (let (($x46 (forall ((?v2 B$) )(! (f$ ?v0 ?v2) :qid k!10))
))
(let (($x31 (forall ((?v1 B$) )(! (f$ n$ ?v1) :qid k!10))
))
(and $x31 $x46))) :qid k!10))
))
(let (($x72 (or (not $x52) $x63)))
(let (($x42 (forall ((?v0 E$) (?v1 D$) (?v2 A$) )(! (let (($x40 (forall ((?v3 D$) (?v4 B$) )(! (f$ ?v2 ?v4) :qid k!10))
))
(or (= ?v2 n$) $x40)) :qid k!10))
))
(let (($x36 (forall ((?v0 A$) )(! (let (($x35 (forall ((?v1 C$) (?v2 B$) )(! (f$ ?v0 ?v2) :qid k!10))
))
(let (($x31 (forall ((?v1 B$) )(! (f$ n$ ?v1) :qid k!10))
))
(and $x31 $x35))) :qid k!10))
))
(let (($x37 (=> $x36 $x42)))
(let (($x27 (not $x37)))
(let (($x60 (forall ((?v0 E$) (?v1 D$) (?v2 A$) )(! (let (($x46 (forall ((?v2 B$) )(! (f$ ?v2 ?v2) :qid k!10))
))
(or (= ?v2 n$) $x46)) :qid k!10))
))
(let (($x46 (forall ((?v2 B$) )(! (f$ ?0 ?v2) :qid k!10))
))
(let (($x57 (or (= ?0 n$) $x46)))
(let (($x40 (forall ((?v3 D$) (?v4 B$) )(! (f$ ?0 ?v4) :qid k!10))
))
(let ((@x59 (monotonicity (elim-unused (= $x40 $x46)) (= (or (= ?0 n$) $x40) $x57))))
(let ((@x67 (trans (quant-intro @x59 (= $x42 $x60)) (elim-unused (= $x60 $x63)) (= $x42 $x63))))
(let (($x31 (forall ((?v1 B$) )(! (f$ n$ ?v1) :qid k!10))
))
(let (($x49 (and $x31 $x46)))
(let (($x35 (forall ((?v1 C$) (?v2 B$) )(! (f$ ?0 ?v2) :qid k!10))
))
(let ((@x51 (monotonicity (elim-unused (= $x35 $x46)) (= (and $x31 $x35) $x49))))
(let ((@x70 (monotonicity (quant-intro @x51 (= $x36 $x52)) @x67 (= $x37 (=> $x52 $x63)))))
(let ((@x79 (monotonicity (trans @x70 (rewrite (= (=> $x52 $x63) $x72)) (= $x37 $x72)) (= $x27 (not $x72)))))
(let ((@x119 (mp~ (not-or-elim (mp (asserted $x27) @x79 (not $x72)) $x81) (trans (sk (~ $x81 (not (or $x98 $x100)))) @x116 (~ $x81 $x114)) $x114)))
(let ((@x123 (and-elim @x119 $x111)))
(let (($x614 (forall ((?v0 A$) (?v2 B$) (?v1 B$) )(! (let (($x30 (f$ n$ ?v1)))
(let (($x576 (not $x30)))
(let (($x590 (or $x576 (not (f$ ?v0 ?v2)))))
(not $x590)))) :pattern ( (f$ ?v0 ?v2) (f$ n$ ?v1) ) :qid k!10))
))
(let (($x128 (forall ((?v0 A$) )(! (let (($x46 (forall ((?v2 B$) )(! (f$ ?v0 ?v2) :qid k!10))
))
(let (($x31 (forall ((?v1 B$) )(! (f$ n$ ?v1) :qid k!10))
))
(not (or (not $x31) (not $x46))))) :qid k!10))
))
(let (($x608 (forall ((?v0 A$) (?v2 B$) (?v1 B$) )(! (let (($x30 (f$ n$ ?v1)))
(let (($x576 (not $x30)))
(let (($x590 (or $x576 (not (f$ ?v0 ?v2)))))
(not $x590)))) :qid k!10))
))
(let (($x30 (f$ n$ ?0)))
(let (($x576 (not $x30)))
(let (($x590 (or $x576 (not (f$ ?2 ?1)))))
(let (($x599 (not $x590)))
(let (($x573 (forall ((?v0 A$) )(! (let (($x559 (forall ((?v2 B$) )(! (f$ ?v0 ?v2) :pattern ( (f$ ?v0 ?v2) ) :qid k!10))
))
(let (($x564 (not $x559)))
(let (($x550 (forall ((?v1 B$) )(! (f$ n$ ?v1) :pattern ( (f$ n$ ?v1) ) :qid k!10))
))
(let (($x555 (not $x550)))
(let (($x567 (or $x555 $x564)))
(not $x567)))))) :qid k!10))
))
(let (($x605 (forall ((?v0 A$) )(! (forall ((?v2 B$) (?v1 B$) )(! (let (($x30 (f$ n$ ?v1)))
(let (($x576 (not $x30)))
(let (($x590 (or $x576 (not (f$ ?v0 ?v2)))))
(not $x590)))) :qid k!10))
 :qid k!10))
))
(let (($x600 (forall ((?v2 B$) (?v1 B$) )(! (let (($x30 (f$ n$ ?v1)))
(let (($x576 (not $x30)))
(let (($x590 (or $x576 (not (f$ ?0 ?v2)))))
(not $x590)))) :qid k!10))
))
(let (($x559 (forall ((?v2 B$) )(! (f$ ?0 ?v2) :pattern ( (f$ ?0 ?v2) ) :qid k!10))
))
(let (($x564 (not $x559)))
(let (($x550 (forall ((?v1 B$) )(! (f$ n$ ?v1) :pattern ( (f$ n$ ?v1) ) :qid k!10))
))
(let (($x555 (not $x550)))
(let (($x567 (or $x555 $x564)))
(let (($x570 (not $x567)))
(let (($x591 (exists ((?v2 B$) (?v1 B$) )(! (let (($x30 (f$ n$ ?v1)))
(let (($x576 (not $x30)))
(or $x576 (not (f$ ?0 ?v2))))) :qid k!10))
))
(let (($x581 (exists ((?v2 B$) )(! (let (($x45 (f$ ?0 ?v2)))
(not $x45)) :pattern ( (f$ ?0 ?v2) ) :qid k!10))
))
(let (($x577 (exists ((?v1 B$) )(! (let (($x30 (f$ n$ ?v1)))
(not $x30)) :pattern ( (f$ n$ ?v1) ) :qid k!10))
))
(let ((@x586 (monotonicity (pull-quant (= $x555 $x577)) (pull-quant (= $x564 $x581)) (= $x567 (or $x577 $x581)))))
(let ((@x598 (monotonicity (trans @x586 (pull-quant (= (or $x577 $x581) $x591)) (= $x567 $x591)) (= $x570 (not $x591)))))
(let ((@x607 (quant-intro (trans @x598 (pull-quant (= (not $x591) $x600)) (= $x570 $x600)) (= $x573 $x605))))
(let ((@x563 (quant-intro (refl (= (f$ ?1 ?0) (f$ ?1 ?0))) (= $x46 $x559))))
(let ((@x557 (monotonicity (quant-intro (refl (= $x30 $x30)) (= $x31 $x550)) (= (not $x31) $x555))))
(let ((@x569 (monotonicity @x557 (monotonicity @x563 (= (not $x46) $x564)) (= (or (not $x31) (not $x46)) $x567))))
(let ((@x575 (quant-intro (monotonicity @x569 (= (not (or (not $x31) (not $x46))) $x570)) (= $x128 $x573))))
(let ((@x616 (trans @x575 (trans @x607 (pull-quant (= $x605 $x608)) (= $x573 $x608)) (= $x128 $x608))))
(let ((@x622 (trans @x616 (quant-intro (refl (= $x599 $x599)) (= $x608 $x614)) (= $x128 $x614))))
(let ((@x130 (quant-intro (rewrite (= $x49 (not (or (not $x31) (not $x46))))) (= $x52 $x128))))
(let ((@x93 (monotonicity (nnf-pos (refl (~ $x30 $x30)) (~ $x31 $x31)) (nnf-pos (refl (~ (f$ ?1 ?0) (f$ ?1 ?0))) (~ $x46 $x46)) (~ $x49 $x49))))
(let ((@x96 (mp~ (not-or-elim (mp (asserted $x27) @x79 (not $x72)) $x52) (nnf-pos @x93 (~ $x52 $x52)) $x52)))
(let ((@x623 (mp (mp @x96 @x130 $x128) @x622 $x614)))
(let (($x201 (not $x547)))
(let (($x225 (or (not $x614) $x201)))
(let ((@x205 ((_ quant-inst ?v2!0 ?v2!1 ?v2!1) $x225)))
(unit-resolution @x205 @x623 (unit-resolution (def-axiom (or $x547 $x109)) @x123 $x547) false))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

```

**Comment by NikolajBjorner** [comment] 2017-08-11 13:23
this would be a duplicate of #628. Proof reconstruction is "broken" when it comes to name capture. The proper fix requires substantial rework

**Comment by blanchette** [comment] 2017-08-11 14:45
Indeed, it's most likely the same thing. I had forgotten about the previous bug report!

**Comment by NikolajBjorner** [comment] 2017-08-11 14:46
Neither lost, nor forgotten on this side, just not an easy fix. Sorry.

**Closed as completed** 2018-12-12 18:27 UTC
Labels: duplicate
