### ISSUE TITLE
Unknown result: a simple bit extraction operation for a bitvector

### ISSUE THREAD

**Issue by kooshanabedian** [Z3Prover/z3#873] opened 2017-01-23 15:08 UTC
Hi,
I have hit a problem with extracting bits from a bitvector and translating each individual bit into a bool expression. Here is what I have done 

```

std::stringstream name1;
name1 << "bit_" << i << "_" << j;

expr var_bit = sctx->ctx.bool_const(name1.str().c_str());
expr tboolbit = (sctx->ctx.bv_val(1,1) == foundexpr.extract(j,j));
expr fboolbit = (sctx->ctx.bv_val(0,1) == foundexpr.extract(j,j));

fctx->formula_bit = fctx->formula_bit &&
	(((var_bit == sctx->ctx.bool_val(0)) || (var_bit == sctx->ctx.bool_val(1))) &&
	 (((var_bit == sctx->ctx.bool_val(0)) && fboolbit) || ((var_bit == sctx->ctx.bool_val(1)) && tboolbit)));
```

This is placed within a for loop which cycles through all bits of _foundexpr_ for each _j_. The issue is that **tboolbit** and **fboolbit** cause the push(), add(formula_bit), check() sequence to return an "unknown" result. de Moura explains [here](https://stackoverflow.com/questions/11197344/z3-produces-unknown-for-assertions-without-quantifiers) that this could be triggered by

> 
> - Run out of time or memory
> - The quantifier-free fragment is undecidable (e.g., nonlinear integer arithmetic)
> - The quantifier-free fragment is too expensive, and/or the procedure implemented in Z3 is incomplete.
> 

I am convinced that it is not a matter of time or memory overshoot, but I can't really soak it in or figure it out how such expressions could be undecidable or even incomplete for Z3.

**Comment by NikolajBjorner** [comment] 2017-01-23 15:15
The use of extract and comparison is correct. You can be more economical in the encoding because tboolbit is true if and only if fboolbit is false so you just need one of them. 
You could dump the solver state using the method to_smt2 on the solver and obtain repros that expose whatever the issue may be.

**Comment by kooshanabedian** [comment] 2017-01-23 15:31
Thanks.
OK. I did the optimization, and the attached file is what I got. I still don't have a clue on the cause. I get the unknown result yet. But curiously, when I directly ran Z3 over this file it returns sat !

[smt.txt](https://github.com/Z3Prover/z3/files/724114/smt.txt)

**Comment by NikolajBjorner** [comment] 2017-01-23 15:55
what does solver::reason_unknown() say?

**Comment by kooshanabedian** [comment] 2017-01-23 15:59
Surprisingly,

> incomplete

**Comment by NikolajBjorner** [comment] 2017-01-23 16:02
The solver you are using is possibly configured using tactics or some logic.
The other way to debug this is to extract a "log" file, Z3_open_log before any other calls to Z3. Save the log file, then rerun it from Z3's command line. It should produce the same "incomplete" answer then.

**Comment by kooshanabedian** [comment] 2017-01-23 16:24
That's it!
I've used "simplify", "solve-eqs", "bit-blast", and "sat" respectively, conjoining with & (and then) operator.
I suspect the incompleteness rises over the use of "solve-eqs" which I've included to discharge some heavy sequence of 'xor' constraints. It would have tried to dismantle bitvector extraction-comparison pairs but it fails.

Thank you very much. Sorry about wasting your time over this misuse.

**Comment by NikolajBjorner** [comment] 2017-01-23 16:30
No problem. We always learn from how the API gets used. 

It doesn't fully reproduce from SMT2. Replacing (check-sat) by 
(check-sat-using (and-then simplify solve-eqs bit-blast sat))
produces sat.

The bit-blaster and sat backend are somewhat limited in the formulas they can handle, so internally we ensure that the formulas end up in the format they accept. However, it becomes tricky when the same tractics are exposed for arbitrary combinations. In some cases I ended up making the sat backend less dependent on prior normalizations.

**Comment by kooshanabedian** [comment] 2017-01-23 17:21
Got it. I really appreciate your explanation.
Anyway, is "solve-eqs" really a good tactic to deal with xor constraints? Is there any other procedure to melt down such formulae before bitblasting?

**Comment by NikolajBjorner** [comment] 2017-01-23 17:25
There isn't anything special to deal with xor, so maybe solve-eqs is the best we have at the time.

**Comment by kooshanabedian** [comment] 2017-01-23 17:38
Thank you.

**Comment by NikolajBjorner** [comment] 2017-02-01 23:31
Can we close this, or do you have a scenario that we can handle better?

**Comment by kooshanabedian** [comment] 2017-02-02 08:45
I assume you can close it.
It happened that I came to use the _smt_ tactic at the end of my strategy chain. I also found **Z3_tactic_par_or** tactic combinator very fortunate, since the previous troubled strategy happened to actually deliver pretty well in cases when bitvector extraction enablers just cancelled out early on during simplifications. So, after all, I decided to use this structure (below), and I have no idea how could this possibly be automatically decided within z3; rather than just falling back to the most general solver of all:

```
inline z3::tactic mk_tactics(z3::context& ctx, SolverConfig* config){
		z3::tactic tact = z3::tactic(ctx, "simplify");
		z3::params tp0(ctx);
		tp0.set("push_ite_bv", true);
		tp0.set("push_ite_arith", true);
		tp0.set("cache-all", true);
		z3::params elim_and(ctx);
		z3::tactic qfaufbv(ctx, "qfaufbv");
		z3::tactic solve_eqs(ctx, "solve-eqs");
		z3::tactic simplify(ctx, "simplify");
		z3::tactic bit_blast(ctx, "bit-blast");
		z3::tactic tseitin_cnf(ctx, "tseitin-cnf");
		z3::tactic sat(ctx, "sat");
		z3::tactic aig(ctx, "aig");
		z3::tactic smt(ctx, "smt");
		z3::tactic fpa2bv(ctx, "fpa2bv");
		z3::tactic bvarray2uf(ctx, "bvarray2uf");
		z3::tactic ackermannize_bv(ctx, "ackermannize_bv");
		elim_and.set("elim_and", true);
		Z3_tactic ts[6];
		z3::tactic t0 = simplify;
		z3::tactic t1 = simplify;
		z3::tactic t2 = simplify;
		z3::tactic t3 = simplify;
		z3::tactic t4 = simplify;
		z3::tactic t5 = simplify;
		
                t0 = t0 & ackermannize_bv & with(qfaufbv, tp0) & with(simplify, elim_and) & bit_blast & sat & smt;
		if (config->setGaussianEliminationTactic) t1 = t1 & solve_eqs;
		if (config->setBitBlastTactic) t1 = t1 & bit_blast;
		if (config->setCNFConversionTactic) t1 = t1 & tseitin_cnf;
		if (true) t1 = t1 & sat;
		if (true) t1 = t1 & smt;
		if (config->setBitBlastTactic) t2 = t2 & bit_blast;
		if (config->setCNFConversionTactic) t2 = t2 & tseitin_cnf;
		if (true) t2 = t2 & sat;
		if (true) t2 = t2 & smt;
		if (config->setGaussianEliminationTactic) t3 = t3 & solve_eqs;
		if (config->setBitBlastTactic) t3 = t3 & bit_blast;
		if (config->setCNFConversionTactic) t3 = t3 & tseitin_cnf;
		if (true) t3 = t3 & aig;
		if (true) t3 = t3 & sat;
		if (true) t3 = t3 & smt;
		if (config->setBitBlastTactic) t4 = t4 & bit_blast;
		if (config->setCNFConversionTactic) t4 = t4 & tseitin_cnf;
		if (true) t4 = t4 & aig;
		if (true) t4 = t4 & sat;
		if (true) t4 = t4 & smt;
		t5 = t5 & fpa2bv & bvarray2uf & ackermannize_bv & qfaufbv & with(simplify, elim_and) & bit_blast & sat & smt;
		ts[0] = t0.operator _Z3_tactic *();
		ts[1] = t1.operator _Z3_tactic *();
		ts[2] = t2.operator _Z3_tactic *();
		ts[3] = t3.operator _Z3_tactic *();
		ts[4] = t4.operator _Z3_tactic *();
		ts[5] = t5.operator _Z3_tactic *();
		tact = tact & z3::tactic(ctx, Z3_tactic_par_or(ctx, 6, ts));
		return tact;
	}
```

**Comment by NikolajBjorner** [comment] 2017-02-02 17:22
well, that API usage is definitely not for beginners.
As a takeaway, I can see we are not exposing tactic_par_or or some ways for you to use it conveniently from C++.

**Comment by kooshanabedian** [comment] 2017-02-03 13:01
Thanks. It's kind of you to notice that. Yes, both _par_or_ and  _par_and_ combinators are just exposed through C API. Either way, they are awesome.

**Closed** 2017-02-13 12:38 UTC
