### ISSUE TITLE
ld failed when installing z3 on mac osx 10.11.2

### ISSUE THREAD

**Issue by xiedingbao** [Z3Prover/z3#381] opened 2015-12-17 04:01 UTC
I tried to build z3 (latest version from git) on my mac but got a ld failure.

g++ -o z3  shell/datalog_frontend.o shell/dimacs_frontend.o shell/gparams_register_modules.o shell/install_tactic.o shell/main.o shell/mem_initializer.o shell/opt_frontend.o shell/smtlib_frontend.o shell/z3_log_frontend.o api/api.a opt/opt.a parsers/smt/smtparser.a tactic/portfolio/portfolio.a sat/sat_solver/sat_solver.a tactic/ufbv/ufbv_tactic.a tactic/fpa/fpa_tactics.a tactic/smtlogics/smtlogic_tactics.a tactic/nlsat_smt/nlsat_smt_tactic.a muz/fp/fp.a muz/duality/duality_intf.a muz/ddnf/ddnf.a muz/bmc/bmc.a muz/tab/tab.a muz/clp/clp.a muz/pdr/pdr.a muz/rel/rel.a muz/transforms/transforms.a muz/dataflow/dataflow.a muz/base/muz.a duality/duality.a qe/qe.a tactic/sls/sls_tactic.a smt/tactic/smt_tactic.a tactic/bv/bv_tactics.a smt/smt.a smt/proto_model/proto_model.a smt/params/smt_params.a ast/rewriter/bit_blaster/bit_blaster.a ast/pattern/pattern.a ast/macros/macros.a ast/fpa/fpa.a ast/simplifier/simplifier.a ast/proof_checker/proof_checker.a parsers/smt2/smt2parser.a cmd_context/extra_cmds/extra_cmds.a cmd_context/cmd_context.a interp/interp.a solver/solver.a tactic/aig/aig_tactic.a math/subpaving/tactic/subpaving_tactic.a nlsat/tactic/nlsat_tactic.a tactic/arith/arith_tactics.a sat/tactic/sat_tactic.a tactic/core/core_tactics.a math/euclid/euclid.a math/grobner/grobner.a parsers/util/parser_util.a ast/substitution/substitution.a tactic/tactic.a model/model.a ast/normal_forms/normal_forms.a ast/rewriter/rewriter.a ast/ast.a math/subpaving/subpaving.a math/realclosure/realclosure.a math/interval/interval.a math/simplex/simplex.a math/hilbert/hilbert.a nlsat/nlsat.a sat/sat.a math/polynomial/polynomial.a util/util.a  -lpthread  -fopenmp
0  0x107bfa342  __assert_rtn + 144
1  0x107c0dc89  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3225
2  0x107c0592e  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 388
3  0x107c33ccf  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 761
4  0x107c331e2  archive::File<x86_64>::justInTimeforEachAtom(char const*, ld::File::AtomHandler&) const + 122
5  0x107c4da75  ld::tool::InputFiles::searchLibraries(char const*, bool, bool, bool, ld::File::AtomHandler&) const + 265
6  0x107c56db8  ld::tool::Resolver::resolveUndefines() + 160
7  0x107c59117  ld::tool::Resolver::resolve() + 79
8  0x107bfb060  main + 812
A linker snapshot was created at:
	/tmp/z3-2015-11-17-114525.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-253.9/src/ld/parsers/macho_relocatable_file.cpp, line 1835.
collect2: error: ld returned 1 exit status
make: *** [z3] Error 1

**Comment by NikolajBjorner** [comment] 2015-12-17 05:08
Note that this error message is internal to your compiler. Perhaps updating it to a patched version could address the error.

**Comment by xiedingbao** [comment] 2015-12-17 06:19
Build successfully when changing the compiler to clang!

**Comment by wintersteiger** [comment] 2015-12-17 11:53
Great, thanks for letting us know! I'm closing the issue as the problem is fixed, but could you perhaps let us know what the version numbers of the failing tools were?

**Closed by wintersteiger** 2015-12-17 11:53 UTC

**Comment by xiedingbao** [comment] 2015-12-17 13:12
The version of the g++ and ld on my mac:

Dingbaos-MacBook-Pro:~ xiedingbao$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-253.9
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: Apple LLVM 7.0.2 (clang-700.1.81)
Dingbaos-MacBook-Pro:~ xiedingbao$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.1.0/4.8.4/lto-wrapper
Target: x86_64-apple-darwin14.1.0
Configured with: ./configure
Thread model: posix
gcc version 4.8.4 (GCC)
