### ISSUE TITLE
Initialized value for variables

### ISSUE THREAD

**Issue by yuazh81** [Z3Prover/z3#2453] opened 2019-07-31 20:36 UTC
Hi,
I have a lot of variables (Int, Real)to be determined. I would like to set the initialized values for variables. Initialized values should be kept if no constraints has been added to those variables. Initialized values should be changed  if there exists constraints.How to do it in z3py?

**Comment by LeventErkok** [comment] 2019-07-31 21:44
Possible duplicate of https://github.com/Z3Prover/z3/issues/1704

**Comment by NikolajBjorner** [comment] 2019-08-01 05:08
Note that the "eval" method on models does by default not assign a value to variables that are not mentioned in the model. So if a set of constraints do not mention a particular variable x and mdl is a model for the the constraints, then mld.eval(x) is going to be x. You can then create 

    def my_eval(mdl, x):
          v = mdl.eval(x)
          if v.eq(x):
             return 0
          else:
             return v

**Comment by yuazh81** [comment] 2019-08-01 07:36
> Possible duplicate of #1704
@NikolajBjorner  @LeventErkok 
It is really what I want. But any method to implement it through python API?

**Comment by NikolajBjorner** [comment] 2019-08-01 08:29
Sorry, the question isn't clear. There is no reference to optimization solver or other solver in my answer. The issue #1704 is specific to strings so is possibly not related to your question.

**Comment by yuazh81** [comment] 2019-08-01 08:35
@NikolajBjorner My problems is that I have many variables (Int or Real). If there is no constraint for some of variables, the output of those variables is zero in the solver. But if there exists some constraints for some of variables, the output of the variables should obey the constraint.
So one way to implement it is the use of soft_constraint. I do not know any other way to implement in Python except the optimize.add_soft for the python api.

**Comment by yuazh81** [comment] 2019-08-01 08:38
@NikolajBjorner 
An example is that:
x, y = Ints('x y')
s = Solver()
s.add(x > 10)

s.check()
s.model()

So I expect the output : x==11, y == 0 for example. not the output: x==11, y == 10

**Comment by NikolajBjorner** [comment] 2019-08-01 08:43
from z3 import *
x, y = Ints('x y')
s = Solver()
s.add(x > 10)
s.check()

def my_eval(mdl, x):
    v = mdl.eval(x)
    if v.eq(x):
        return 0
    else:
        return v

mdl = s.model()
print(my_eval(mdl, x))
print(my_eval(mdl, y))

**Comment by yuazh81** [comment] 2019-08-01 09:04
@NikolajBjorner 
Any methods to get the result directly from
 print s.model()?

**Comment by NikolajBjorner** [comment] 2019-08-01 09:05
no. You can inspect the implementation in z3.py

**Closed by NikolajBjorner** 2019-08-01 09:05 UTC

**Comment by LeventErkok** [comment] 2019-08-01 21:11
@yuazh81 if I may chime in for future requests like this: There's a (fairly vibrant) stack-overflow site for z3 end-user discussions: https://stackoverflow.com/questions/tagged/z3

Posting these sorts of questions there first would be more appropriate. If that leads to nowhere (or  if it is determined some real z3 issue exists), then you can move it to the z3 issue tracker.
