### ISSUE TITLE
Soudness bug on QF_S with regex 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4376] opened 2020-05-18 12:35 UTC
Hi,
For this case, Z3  gives an incorrect answer:
```
[589] % z3-4.8.5 small.smt2
sat
[590] % z3-4.8.6 small.smt2
sat
[591] % z3-4.8.7 small.smt2
sat
[592] % z3-4.8.8 small.smt2
unsat
[593] % z3release small.smt2
unsat
[594] % cat small.smt2
(declare-fun a () String)
(assert
 (xor
 (= (str.in.re a (str.to.re "B"))
  (str.in.re a (re.union (str.to.re "B") (str.to.re "BB"))))
 (= (str.in.re a (re.union (re.inter (str.to.re "A") re.allchar) (str.to.re "B")))
  (str.in.re a (re.union (str.to.re "A") (str.to.re "B"))))))
(check-sat)
[595] %
```
The formula is sat (e.g., with a ="BB").

OS: Ubuntu 18.04
Commit: 1c760b0

**Comment by zhendongsu** [comment] 2020-05-18 17:16
Murphy, this is a bug in seq, not z3str3 (z3str3 does seem to hang on it though). 

@mtrberzi

**Comment by mtrberzi** [comment] 2020-05-18 17:25
Likely duplicate of an existing known issue with `re.inter`

**Comment by zhendongsu** [comment] 2020-05-18 17:33
> Likely duplicate of an existing known issue with `re.inter`

You meant the reason for z3str3 to hang on it?   I don't see an open bug in z3's default seq solver that looked similar/related. 

Hope you could fix the `re.inter` issue (and the others) as there are quite some unsoundness instances for z3str3, and it is very difficult to know whether they are duplicates or not.  Thanks.

**Comment by NikolajBjorner** [comment] 2020-07-27 02:27
moved to #4339

**Closed by NikolajBjorner** 2020-07-27 02:27 UTC
Labels: string
