### ISSUE TITLE
Invalid model for QF_FP formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3462] opened 2020-03-22 05:04 UTC
Hi,
For this formula:
```
(define-sort FPN () (_ FloatingPoint 46 53))
(declare-fun a () FPN)
(declare-fun y () FPN)
(declare-fun b () FPN)
(assert (= (fp.mul roundTowardZero a y) b))
(check-sat)
```
Z3  gives an invalid model:
```
[606] % z3 model_validate=true small.smt2
sat
(error "line 6 column 10: an invalid model was generated")
[607] % 
[607] % cat small.smt2
(define-sort FPN () (_ FloatingPoint 46 53))
(declare-fun a () FPN)
(declare-fun y () FPN)
(declare-fun b () FPN)
(assert (= (fp.mul roundTowardZero a y) b))
(check-sat)
```

OS: Ubuntu 18.04
Commit: 8717c7d

**Comment by rainoftime** [comment] 2020-04-21 07:46
Another test from https://github.com/Z3Prover/z3/issues/4039
NOTE: need to set timeout for z3 to trigger the issue
~~~~
(set-logic QF_FPLRA)
(set-option :model_validate true)
(declare-const fpv3 Float32)
(declare-const fpv4 Float32)
(declare-const v0 Bool)
(declare-const v2 Bool)
(declare-const v1 Bool)
(declare-const v5 Bool)
(declare-const v8 Bool)
(declare-const v10 Bool)
(declare-const v13 Bool)
(declare-const v14 Bool)
(declare-const v16 Bool)
(declare-const r0 Real)
(declare-const r1 Real)
(declare-const r7 Real)
(declare-const v18 Bool)
(assert v5)
(declare-const fpv5 Float32)
(declare-const fpv6 Float32)
(push 1)
(declare-const v19 Bool)
(declare-const fpv7 Float32)
(assert (and (xor v18 (fp.gt fpv5 fpv6 ((_ to_fp 8 24) RNA 0.3777009132) ((_ to_fp 8 24) RNA 0.3777009132)) v19 v8 (fp.geq (fp.div RNA fpv3 ((_ to_fp 8 24) RTN 732517.0)) (fp.abs fpv4) ((_ to_fp 8 24) RNA 0.3777009132) (fp.abs fpv4))) v13 v0 v16 v19 (fp.lt fpv4 fpv3 ((_ to_fp 8 24) RNA 0.3777009132) ((_ to_fp 8 24) RTN 732517.0)) v14 (fp.lt (fp.abs fpv5) (fp.abs fpv5) fpv7 (fp.abs fpv5) fpv4) v13))
(push 1)
(assert (and v5 (> r7 0.5866255) (>= 0.0 r1)))
(check-sat)
(pop 1)
(assert (not (distinct v10 v13 (> r7 0.5866255))))
(check-sat)
~~~

**Comment by wintersteiger** [comment] 2020-07-16 12:53
None of these reports are reproducible. 

@zhendongsu when reporting model validation problems, always include a printout of the model Z3 produced. Things have changed since this was first reported and Z3 finds completely different models now. Even when I try to use many different random seeds, I can't find one that triggers your or any other model validation error though.

@rainoftime your problem is completely different from the others, it just happens to be a model validation error too. It isn't reproducible either though.

I'm closing this issue. If you find more problems please submit new issues. I suspect that the actual underlying problem to all these issues may have been bugs in the bit-vector theory that have long been fixed.

**Closed by wintersteiger** 2020-07-16 12:53 UTC
