### ISSUE TITLE
Z3 incorrect model on QF_NRA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2889] opened 2020-01-26 01:58 UTC
Hi,
For this formula,
```
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun e () Real)
(assert (= (+ a e) (+ b (/ c d))))
(assert (> e 0.0))
(assert (> e 1.0))
(check-sat)
(get-model)
```
z3 gives an incorretc model:
```
(model 
  (define-fun c () Real
    (- 1.0))
  (define-fun a () Int
    0)
  (define-fun d () Real
    0.0)
  (define-fun b () Int
    1)
  (define-fun e () Real
    1.0)
)
```
in which e=1.0 cannot satisfy e > 1.0.

OS: Ubuntu 18.04 
Revision: 5497022

**Comment by NikolajBjorner** [comment] 2020-01-27 02:00
duplicate of #2890

**Closed by NikolajBjorner** 2020-01-27 02:00 UTC
