### ISSUE TITLE
Can't replay unsolvable query.

### ISSUE THREAD

**Issue by kren1** [Z3Prover/z3#1712] opened 2018-06-29 13:56 UTC
I'm generating some queries in string theory with KLEE. After a while I get this error:

```
smt tactic failed to show goal to be sat/unsat (incomplete (theory  seq)),
```

So I tried to pin point the query that's not solvable. I have an smt2 log and a z3.log of all the queries (attached [logs.zip](https://github.com/Z3Prover/z3/files/2149614/logs.zip)).

The smt2 log is created by calling `Z3_solver_to_string()` before each query. 

The interesting thing is that the smt2 log replays fine, reporting `sat` for the last query. However the Z3 log does not replay reporting `Error at line 167376: invalid scaped character`.

Is the invalid escaped character error somehow realted to the failed to show goal one? Any other ideas what might be wrong?

Thanks

**Comment by NikolajBjorner** [comment] 2018-06-29 16:14
The "unknown" is due to rather limited power of the seq solver. The good news is that there are some improvements in the pipeline and you can also try the z3str3 solver. The non-reproducibility of "unknown" over the generated smt2 file is due to that the seq solver is not confluent: it may give up in some cases where with other random seeds / search orders it succeeds.

The error is because the pretty printer that creates the log doesn't properly escape characters, so the reader can't consume the strings.
The offending line is: S "\0-0\/.(\/0,\092x00\092x00"
There are single \ characters in the string, which shouldn't be there.
The log you have is for version 4.6.1. We are hard at work on 4.8, so the log will not even load with the current version. The code in src/api/z3_logger.h is supposed to avoid such escape characters while creating a log, but it seems to not do so. I have added what should be a fix for this (remainder of signed characters is non-positive when the character is negative) so we can get well-formed logs going forward.

**Comment by kren1** [comment] 2018-06-30 13:49
Thanks for the quick response and the logging fix.

I see how the seq solver can sometimes give up and succeed in other cases, but I'm consistently seeing it succeed with smt2 file and fail when used through API. I'm wondering if I can tune the settings so they are more inline with what happens with smt2 file.

**Closed** 2018-07-10 21:14 UTC
Labels: string
