### ISSUE TITLE
Debug branch: assertion violation at old_vector.h:370 (arith.solver = 6)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3518] opened 2020-03-26 04:16 UTC
Hi, for the following formula
~~~~
(set-option :smt.arith.solver 6)
(declare-const v3 Bool)
(declare-const v4 Bool)
(declare-const r1 Real)
(declare-const r5 Real)
(declare-const r6 Real)
(declare-const v7 Bool)
(assert (and v4 v7 (>= r6 4488880046.0 (/ r5 0.0) r1 r1) v3 v7))
(check-sat)
~~~~

z3 debug branch (Commit cc8fe2f) throws out an assertion violation:
~~~~
File: ../src/util/old_vector.h
Line: 370
idx < size()
~~~~

**Comment by NikolajBjorner** [comment] 2020-03-26 17:12
@levnach - same root cause as #3517

**Comment by levnach** [comment] 2020-03-26 17:25
Fixed by rebasing with master

**Closed by levnach** 2020-03-26 17:25 UTC
Labels: Debug
