### ISSUE TITLE
Invalid model bug in debug build

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4862] opened 2020-12-06 04:38 UTC
This bug seems different from the previous ones since it's only triggered in debug build. 
```
[584] % z3release model_validate=true small.smt2
sat
(
 (define-fun X () (_ FloatingPoint 11 53)
  (fp #b1 #b01011100010 #x83b6fffeff76e))
 (define-fun Y () (_ FloatingPoint 9 53)
  (fp #b1 #b000000000 #x00000003076e0))
)
sat
unsat
[585] % z3debug model_validate=true small.smt2
sat
(error "line 5 column 10: an invalid model was generated")
(
 (define-fun X () (_ FloatingPoint 11 53)
  (fp #b0 #b00000000000 #x0001a2bffffff))
 (define-fun Y () (_ FloatingPoint 9 53)
  (_ +oo 9 53))
)
sat
unsat
[586] % 
[586] % cat small.smt2
(declare-fun X () (_ FloatingPoint 11 53))
(declare-fun Y () (_ FloatingPoint 9 53))
(assert (fp.leq X (fp #b0 #b10011111110 #xFFFFFFFFFFFFF)))
(assert (= Y ((_ to_fp 9 53) RNE X)))
(check-sat)
(get-model)
(reset)
(define-fun X () (_ FloatingPoint 11 53) (fp #b1 #b01011100010 #x83b6fffeff76e))
(define-fun Y () (_ FloatingPoint 9 53) (fp #b1 #b000000000 #x00000003076e0))
(assert (fp.leq X (fp #b0 #b10011111110 #xFFFFFFFFFFFFF)))
(assert (= Y ((_ to_fp 9 53) RNE X)))
(check-sat)
(reset)
(define-fun X () (_ FloatingPoint 11 53) (fp #b0 #b00000000000 #x0001a2bffffff))
(define-fun Y () (_ FloatingPoint 9 53) (_ +oo 9 53))
(assert (fp.leq X (fp #b0 #b10011111110 #xFFFFFFFFFFFFF)))
(assert (= Y ((_ to_fp 9 53) RNE X)))
(check-sat)
[587] %
```
The debug build gives an invalid model, but the release build doesn't.

Commit: 0c93c7a

**Comment by NikolajBjorner** [comment] 2021-07-31 20:55
fpa2bv tactic behaves differently in release/debug mode:

```
C:\z3\build>..\release\z3 4862.smt2 model_validate=true /v:10
(simplifier :num-exprs 7 :num-asts 181 :time 0.00 :before-memory 19.51 :after-memory 19.51)
(simplifier :num-exprs 7 :num-asts 181 :time 0.00 :before-memory 19.51 :after-memory 19.51)
(propagate-values :num-exprs 7 :num-asts 181 :time 0.00 :before-memory 19.51 :after-memory 19.51)
(fpa2bv :num-exprs 881 :num-asts 1190 :time 0.00 :before-memory 19.51 :after-memory 19.51)
(propagate-values :num-exprs 881 :num-asts 1190 :time 0.00 :before-memory 19.51 :after-memory 19.51)
(simplifier :num-exprs 1530 :num-asts 4805 :time 0.00 :before-memory 19.51 :after-memory 19.83)

C:\z3\build>z3 4862.smt2 model_validate=true /v:10
(simplifier :num-exprs 7 :num-asts 181 :time 0.00 :before-memory 18.66 :after-memory 18.66)
(simplifier :num-exprs 7 :num-asts 181 :time 0.00 :before-memory 18.66 :after-memory 18.66)
(propagate-values :num-exprs 7 :num-asts 181 :time 0.00 :before-memory 18.66 :after-memory 18.66)
(fpa2bv :num-exprs 879 :num-asts 1186 :time 0.12 :before-memory 18.66 :after-memory 18.76)
(propagate-values :num-exprs 879 :num-asts 1186 :time 0.00 :before-memory 18.76 :after-memory 18.76)
```

The number of expressions after fpa2bv differs.

**Comment by NikolajBjorner** [comment] 2021-07-31 22:18
They start diverging with:
https://github.com/Z3Prover/z3/blob/ada873631e8ee7b65cc07ee12c5d45ad481f2f94/src/ast/fpa/fpa2bv_converter.cpp#L194
This code is perhaps coupled with bv2fpa_converter.

**Comment by NikolajBjorner** [comment] 2021-08-01 00:39
Another note: currently the release build produces the incorrect model while the debug build does not. 
So the behavior has flipped. 

To avoid divergence between debug and release builds the fpa functionality would benefit from being uniform.

**Comment by wintersteiger** [comment] 2022-06-04 13:58
Can't repro this anymore and I think this a duplicate of the problem fixed in https://github.com/Z3Prover/z3/commit/c24f438e51cc9af302e400d36e1f1b73a4bb0d9a, so I'm closing this.

**Closed by wintersteiger** 2022-06-04 13:58 UTC
Labels: Floats
