### ISSUE TITLE
Inner function "array-ext" appears in model

### ISSUE THREAD

**Issue by 0-14N** [Z3Prover/z3#292] opened 2015-11-04 05:06 UTC
Hi,

I am using the Java API based on the nightly build libraries on OS X, and when I tried to use z3 to handle array, under some cases, it will return models in which there is "array-ext". 
According to this post: http://stackoverflow.com/questions/17215640/getting-concrete-values-from-a-model-containing-array-ext, "array-ext" should never appear in model. 
Is this a bug? Thanks.

**Comment by wintersteiger** [comment] 2015-11-04 13:13
Yes that sounds like a bug. Do you have an example so we can reproduce the problem?

**Comment by 0-14N** [comment] 2015-11-04 16:04
(declare-datatypes () ((ArrayTest3 (ArrayTest3_nil))))
(declare-fun |0!!this!0| () ArrayTest3)
(declare-fun |0!r0!0| () ArrayTest3)
(declare-fun |0!!parameter0!0| () (Array Int Int))
(declare-fun |0!r1!0| () (Array Int Int))
(declare-fun |0!i3!0| () Int)
(declare-fun |0!$i0!0| () Int)
(declare-fun length_of_int ((Array Int Int)) Int)
(declare-fun |0!$i1!0| () Int)
(declare-fun |0!$i2!0| () Int)
(declare-fun |0!r1!1| () (Array Int Int))
(declare-fun |0!i3!1| () Int)
(declare-fun |0!$i0!1| () Int)
(declare-fun |0!$i1!1| () Int)
(declare-fun |0!$i2!1| () Int)
(declare-fun |0!r1!2| () (Array Int Int))
(declare-fun |0!i3!2| () Int)
(declare-fun |0!$i0!2| () Int)

(declare-fun |0!!this!!0| () ArrayTest3)
(declare-fun |0!r0!!0| () ArrayTest3)
(declare-fun |0!!parameter0!!0| () (Array Int Int))
(declare-fun |0!r1!!0| () (Array Int Int))
(declare-fun |0!$i0!!0| () Int)
(declare-fun |0!i3!!0| () Int)
(declare-fun |0!$i1!!0| () Int)
(declare-fun |0!$i2!!0| () Int)
(declare-fun |0!r1!!1| () (Array Int Int))
(declare-fun |0!i3!!1| () Int)
(declare-fun |0!$i1!!1| () Int)
(declare-fun |0!$i2!!1| () Int)
(declare-fun |0!r1!!2| () (Array Int Int))
(declare-fun |0!i3!!2| () Int)

(compute-interpolant (let ((a!1 (not (and (= (length_of_int |0!r1!2|) (length_of_int |0!r1!!2|))
                     (= |0!r1!2| |0!r1!!2|))))
      (a!2 (and (interp (and (interp true) (= |0!r0!0| |0!!this!0|)))
                (= |0!r1!0| |0!!parameter0!0|)))
      (a!18 (and (interp (and (interp true) (= |0!r0!!0| |0!!this!!0|)))
                 (= |0!r1!!0| |0!!parameter0!!0|))))
(let ((a!3 (and (interp (and (interp a!2) (= |0!i3!0| 0)))
                (= |0!$i0!0| (length_of_int |0!r1!0|))
                (>= |0!$i0!0| 0)))
      (a!19 (interp (and (interp a!18)
                         (= |0!$i0!!0| (length_of_int |0!r1!!0|))
                         (>= |0!$i0!!0| 0)))))
(let ((a!4 (interp (and (interp a!3) (not (>= |0!i3!0| |0!$i0!0|)))))
      (a!20 (interp (and a!19 (= |0!i3!!0| (- |0!$i0!!0| 1))))))
(let ((a!5 (interp (and a!4 (= |0!$i1!0| (select |0!r1!0| |0!i3!0|)))))
      (a!21 (interp (and a!20 (not (< |0!i3!!0| 0))))))
(let ((a!6 (interp (and a!5 (= |0!$i2!0| (+ |0!$i1!0| 1)))))
      (a!22 (interp (and a!21 (= |0!$i1!!0| (select |0!r1!!0| |0!i3!!0|))))))
(let ((a!7 (interp (and a!6 (= |0!r1!1| (store |0!r1!0| |0!i3!0| |0!$i2!0|)))))
      (a!23 (interp (and a!22 (= |0!$i2!!0| (+ |0!$i1!!0| 1))))))
(let ((a!8 (interp (and a!7 (= |0!i3!1| (+ |0!i3!0| 1)))))
      (a!24 (interp (and a!23
                         (= |0!r1!!1| (store |0!r1!!0| |0!i3!!0| |0!$i2!!0|))))))
(let ((a!9 (interp (and a!8 (= |0!i3!1| (+ |0!i3!0| 1)))))
      (a!25 (interp (and a!24 (= |0!i3!!1| (+ |0!i3!!0| (- 1)))))))
(let ((a!10 (interp (and a!9
                         (= |0!$i0!1| (length_of_int |0!r1!1|))
                         (>= |0!$i0!1| 0))))
      (a!26 (interp (and a!25 (= |0!i3!!1| (+ |0!i3!!0| (- 1)))))))
(let ((a!11 (interp (and a!10 (not (>= |0!i3!1| |0!$i0!1|)))))
      (a!27 (interp (and a!26 (not (< |0!i3!!1| 0))))))
(let ((a!12 (interp (and a!11 (= |0!$i1!1| (select |0!r1!1| |0!i3!1|)))))
      (a!28 (interp (and a!27 (= |0!$i1!!1| (select |0!r1!!1| |0!i3!!1|))))))
(let ((a!13 (interp (and a!12 (= |0!$i2!1| (+ |0!$i1!1| 1)))))
      (a!29 (interp (and a!28 (= |0!$i2!!1| (+ |0!$i1!!1| 1))))))
(let ((a!14 (interp (and a!13 (= |0!r1!2| (store |0!r1!1| |0!i3!1| |0!$i2!1|)))))
      (a!30 (interp (and a!29
                         (= |0!r1!!2| (store |0!r1!!1| |0!i3!!1| |0!$i2!!1|))))))
(let ((a!15 (interp (and a!14 (= |0!i3!2| (+ |0!i3!1| 1)))))
      (a!31 (interp (and a!30 (= |0!i3!!2| (+ |0!i3!!1| (- 1)))))))
(let ((a!16 (interp (and a!15 (= |0!i3!2| (+ |0!i3!1| 1)))))
      (a!32 (interp (and a!31 (= |0!i3!!2| (+ |0!i3!!1| (- 1)))))))
(let ((a!17 (interp (and a!16
                         (= |0!$i0!2| (length_of_int |0!r1!2|))
                         (>= |0!$i0!2| 0)))))
  (and (= |0!!this!0| |0!!this!!0|)
       (= (length_of_int |0!!parameter0!0|) (length_of_int |0!!parameter0!!0|))
       (= |0!!parameter0!0| |0!!parameter0!!0|)
       a!1
       (interp (and a!17 (>= |0!i3!2| |0!$i0!2|)))
       (interp (and a!32 (< |0!i3!!2| 0)))))))))))))))))))))

**Comment by wintersteiger** [comment] 2015-11-04 16:40
@kenmcmil can you take a look at this one? I suspect this may be a bug in the array interpolation procedures.

**Comment by kenmcmil** [comment] 2015-11-04 20:00
Here we are talking about interpolants, not models. For the extension array theory I have been allowing array-ext in interpolants since in practice this worked better than the alternative (replacing occurrences of array-ext with instances of its definitional axiom). Having said that I have found that it is better to switch array extensionality off when it is not needed, which is a common case in program analysis (at least for C-like languages with no array comparison operator). 

If it's useful, we could add an option to replace phi(array-ext(a,b)) with this:

exists x. (select(a,x) != select(b,x) \/ a = b) & phi(x)

I don't know how useful this would be in practice. An alternative would be to make array-ext available in smt2. 

A little more information about the application would help to decide what is most useful.

**Comment by NikolajBjorner** [comment] 2015-11-06 02:12
Doesn't seem as a bug to me: interpolation is free to introduce extensionality function symbols especially as this is the quantifier-free way to produce interpolants in the presence of extensionality.
There is one issue: Z3 does not support parsing this function or creating it over the API so you can't feed results of interpolation back to Z3.

**Comment by NikolajBjorner** [comment] 2015-11-09 14:29
Closing this as an issue: interpolation should be allowed to use array-ext and the API now supports these.

**Closed by NikolajBjorner** 2015-11-09 14:29 UTC
