### ISSUE TITLE
Issue with tactic

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5932] opened 2022-03-29 01:38 UTC
Hi,
For this instance, z3 https://github.com/Z3Prover/z3/commit/b0605a9d364d4d89e42713dd60baec604981aea2 gives `unsat` with `(check-sat-using qe)`.
```
$ z3 small.smt2
unsat
sat
$ cat small.smt2
(declare-fun a () Bool)
(declare-fun v () String)
(assert (forall ((v Int)) (exists ((V Bool)) (or a (= a (= 0 v))))))
(assert (forall ((a Int)) (= 0 (str.indexof v v))))
(check-sat-using qe)
(check-sat)
```

**Comment by merlinsun** [comment] 2022-03-31 06:59
Another instance with `smt.bv.eq_axioms`:
```
$ cat small.smt2
(declare-const x Bool)
(set-option :smt.bv.eq_axioms false)
(declare-fun a () String)
(declare-fun va () Int)
(assert (forall ((V Int)) (= a (str.++ a))))
(assert (forall ((v Int)) (or x (= va v))))
(check-sat-using qe)
(check-sat)
$ z3 small.smt2
unsat
sat
```

**Comment by NikolajBjorner** [comment] 2022-04-01 04:55
This is a duplicate of an old bug on qe

**Closed** 2022-04-01 20:47 UTC
