### ISSUE TITLE
NuGet for 32-bit

### ISSUE THREAD

**Issue by NN---** [Z3Prover/z3#5700] opened 2021-12-07 21:18 UTC
Both packages Microsoft.Z3 and Microsoft.Z3.x64 provide only 64-bit build.
There is [Microsoft.Z3.x86](https://www.nuget.org/packages/Microsoft.Z3.x86/), however it is unlisted and deprecated.
The Releases tab does contain 32-bit. The only missing part is publishing it as a NuGet package.

https://www.nuget.org/profiles/z3prover

**Comment by NikolajBjorner** [comment] 2021-12-08 04:31
@dsyme - are you using nuget? You added some capability around x86.

**Comment by NN---** [comment] 2021-12-22 10:58
@NikolajBjorner Is there any expectation when 32-bit NuGet will be released ?
Thanks.

**Comment by NikolajBjorner** [comment] 2021-12-22 15:37
Can you test the nightly? https://github.com/Z3Prover/z3/releases/download/Nightly/Microsoft.Z3.4.8.14.nupkg
If it works, I will spin up a 4.14

**Comment by NN---** [comment] 2021-12-22 19:17
Compiling project to x86 platform results with libz3.dll 64-bit and not 32-bit as expected.

And a warning:

```
1>warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "Microsoft.Z3, Version=4.8.14.0", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

**Comment by NikolajBjorner** [comment] 2021-12-22 19:22
Thanks for the feedback, I will then set up a test on my end.

**Comment by NikolajBjorner** [comment] 2021-12-22 20:32
I have a x86 project and loaded the nightly package using the win-x86 dll and it works on my end.

The part that doesn't work is installing nuget packages locally. I get an error related to what is discussed here https://stackoverflow.com/questions/14942374/nuget-package-files-not-being-copied-to-project-content-during-build
but have been unable to resolve it in a clean way (I just end up manually copying the x86 dll into the folder where the project is looking for it. I expect this error to be orthogonal to x86 support, so will have to assume it does in fact work based on the nightly.

**Comment by NN---** [comment] 2021-12-23 07:50
I tried to build a project using old Project style and Project Sdk style:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Z3" Version="4.8.14" />
  </ItemGroup>

</Project>
```

Both give the warning:


1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2298,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "C:\Users\Q\.nuget\packages\microsoft.z3\4.8.14\lib\netstandard1.4\Microsoft.Z3.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by NikolajBjorner** [comment] 2021-12-23 22:34
Version 4.14 is now out and contains win-x86. I tested with framework 6.0. Maybe dotnet core isn't working and it will not suffice for you. We will then have to debug this further to get the build right. The effort involved in round-tripping packaging means that it could take some time to handle this properly.

**Comment by NikolajBjorner** [comment] 2021-12-24 03:24
The root cause must be related to how we package for netstandard.
It is done using the script:

```
    for f in os.listdir(packages):
        print(f)
        if f.endswith(".zip") and classify_package(f):
            os_name, package_dir, ext, dst = classify_package(f)
            path = os.path.abspath(os.path.join(packages, f))
            zip_ref = zipfile.ZipFile(path, 'r')
            zip_ref.extract(f"{package_dir}/bin/libz3.{ext}", f"{tmp}")
            mk_dir(f"out/runtimes/{dst}/native")
            replace(f"{tmp}/{package_dir}/bin/libz3.{ext}", f"out/runtimes/{dst}/native/libz3.{ext}")            
            if "x64-win" in f:
                mk_dir("out/lib/netstandard1.4/")
                if symbols:
                    zip_ref.extract(f"{package_dir}/bin/libz3.pdb", f"{tmp}")
                    replace(f"{tmp}/{package_dir}/bin/libz3.pdb", f"out/runtimes/{dst}/native/libz3.pdb") 
                files = ["Microsoft.Z3.dll"]                
                if symbols:
                    files += ["Microsoft.Z3.pdb", "Microsoft.Z3.xml"]
                for b in files:
                    zip_ref.extract(f"{package_dir}/bin/{b}", f"{tmp}")
                    replace(f"{tmp}/{package_dir}/bin/{b}", f"out/lib/netstandard1.4/{b}")
```
in https://github.com/Z3Prover/z3/blob/6b0dc6d144c2f593429422c0bf12a6d3dd049673/scripts/mk_nuget_task.py#L67
To package for mixed mode the Microsoft.Z3.dll file would need some platform specific versioning in some netstandard directory. If we can't do this, then a separate x86 Nuget package would be required.

**Comment by NikolajBjorner** [comment] 2021-12-25 21:42
It would seem that we need platform specific versions of Microsoft.Z3.dll.
The downloads
https://github.com/Z3Prover/z3/releases/download/z3-4.8.14/z3-4.8.14-x64-win.zip
https://github.com/Z3Prover/z3/releases/download/z3-4.8.14/z3-4.8.14-x86-win.zip
contain different versions of Microsoft.Z3.dll and the manifest (ildasm, sorry this is probably some decades old technology) suggests the native bindings require (unsurprisingly) architecture specifics.

The patchy approach is to copy over the right version of Microsoft.Z3.dll for the nuget package used by x86.
This is something you can do already.
The more satisfactory approach is to fix this. I guess there are two options:
- create a stand-alone x86 Nuget release
- figure out how to package nuget with side-by side versions of Microsoft.Z3.dll. I looked a little into this, but the information I could find looks largely opaque to me (it say perhaps more about how I am wired than whether it is possible).

**Comment by NikolajBjorner** [comment] 2021-12-25 21:50
Note though, that this has been considered before.
Commit 504b6559ab19dd4454531b1fbf031742538fd6fc removes a 
comment about inability to build for AnyCPU implying "it should just work" as is 
(my test suggested it worked for me but cannot rule out something is lost in translation).

**Comment by NN---** [comment] 2021-12-26 11:42
Is it possible to create AnyCPU build for Microsoft.Z3.dll with platform dependent implementation in lib\x86 and lib\x64 ?

**Comment by NikolajBjorner** [comment] 2021-12-27 03:36
I the change log suggests it might, but I don't recall the conditions and haven't found them online.

**Comment by NN---** [comment] 2022-01-08 11:44
Any update ?

I understand making big change is more difficult, could you provide 2 packages meanwhile ?
During publishing I can choose the right architecture.

**Comment by NikolajBjorner** [comment] 2022-01-09 01:14
There is a separate package for x86 https://www.nuget.org/packages/Microsoft.Z3.x86/

**Comment by NN---** [comment] 2022-01-09 06:07
I remember it was deprecated, this why I didn't try it.
Thank !

**Comment by NikolajBjorner** [comment] 2022-01-09 18:25
It was deprecated until yesterday. I uploaded a new image yesterday and made it public again. It took some round-trips to tinker with the build script (you can look at github history for what was done). 

As Z3 is open source, it is in principle possible for users who have specific needs to undertake such steps - the audience for x86 nuget packages for z3 is going to be limited. You are invited to add pull requests with updates. In the end there is a question of whose bandwidth gets consumed to support a given feature.

**Comment by NN---** [comment] 2022-01-09 18:27
I see. Thank you!

[AsmDude](https://github.com/HJLebbink/asm-dude) VS extension uses Z3 library and supports all VS versions.

**Comment by NikolajBjorner** [comment] 2022-01-09 18:35
Thanks for the pointer!

**Comment by NikolajBjorner** [comment] 2022-01-11 04:38
I guess it is now possible to close this issue

**Closed by NikolajBjorner** 2022-01-11 04:38 UTC
Labels: build/release
