### ISSUE TITLE
Assertion violation for NRA instance at nlsat_solver.cpp:867

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3154] opened 2020-03-05 06:56 UTC
Hi,
For the following formulas:
~~~~
(set-logic NRA)
(set-option :nlsat.check_lemmas true)
(set-option :nlsat.inline_vars true)
(declare-const v2 Bool)
(declare-const v4 Bool)
(declare-const r1 Real)
(declare-const r4 Real)
(declare-const r8 Real)
(assert (=> v4 v2))
(assert (= (* 17 r8 6340602.091 r1 0.231076) r4 0.6 r1 (* 17 r8 6340602.091 r1 0.231076)))
(assert v4)
(check-sat)
~~~~

Z3 throws out an assertion violation:
~~~~
ASSERTION VIOLATION
../src/nlsat/nlsat_solver.cpp
Line: 867
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

OS: Ubuntu 16.04
Commit: 6cbcd13

**Comment by NikolajBjorner** [comment] 2020-03-05 07:04
seems duplicate of previous bug that used inline_vars

**Closed by NikolajBjorner** 2020-03-05 07:04 UTC
