### ISSUE TITLE
String generated that violates regex (values outside range)

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#2072] opened 2019-01-07 16:00 UTC
When one run z3 on windows with the attached file, one gets an output that violates the regex.
The regex states all characters are in [A-Z]. Yet other characters are included as well.

[logString.txt](https://github.com/Z3Prover/z3/files/2733349/logString.txt)

```
PS C:\experiments> z3 .\logString.txt
(:name "Z3")
(:version "4.8.4 - build hashcode b40c2b2926ed")
sat
sat
sat
(($In$1050$0$1$ ""))
sat
sat
(($$$$l$0$10000000$-1$-1$ 8))
sat
(($$$$t$7$10000007$-1$-1$ "\x00"))
sat
sat
(($$$$t$7$10000007$-1$-1$ "\xfa"))
sat
(($$$$t$5$10000005$-1$-1$ "\x00"))
sat
sat
(($$$$t$5$10000005$-1$-1$ "\xf6"))
sat
(($$$$t$4$10000004$-1$-1$ "\x00"))
sat
sat
(($$$$t$4$10000004$-1$-1$ "\xe0"))
sat
(($$$$t$8$10000008$-1$-1$ "\x00"))
sat
sat
(($$$$t$8$10000008$-1$-1$ "\xfe"))
sat
(($$$$t$6$10000006$-1$-1$ "\x00"))
sat
sat
(($$$$t$6$10000006$-1$-1$ "\xf6"))
sat
(($$$$t$3$10000003$-1$-1$ "K"))
sat
unsat
unsat
sat
(($$$$t$3$10000003$-1$-1$ "A"))
sat
(($$$$t$2$10000002$-1$-1$ "K"))
sat
unsat
unsat
sat
(($$$$t$2$10000002$-1$-1$ "N"))
sat
(($$$$t$1$10000001$-1$-1$ "S"))
sat
unsat
unsat
sat
(($$$$t$1$10000001$-1$-1$ "C"))
sat
(($In$1050$0$1$ "CNA\xe0\xf6\xf6\xfa\xfe"))
PS C:\experiments>
```

Note that z3str3 crashes on this file, after producing:
```
PS C:\experiments> z3 smt.string_solver=z3str3 .\logString.txt
(:name "Z3")
(:version "4.8.4 - build hashcode b40c2b2926ed")
sat
sat
sat
(($In$1050$0$1$ "aaaaaaaaaaa"))
sat
sat
(($$$$l$0$10000000$-1$-1$ 9))
sat
(($$$$t$7$10000007$-1$-1$ "q"))
sat
sat
(($$$$t$7$10000007$-1$-1$ "\x07"))
```

**Comment by NikolajBjorner** [comment] 2019-01-07 16:23
Are you expecting something like: 

(:name "Z3")
(:version "4.8.5")
sat
sat
sat
(($In$1050$0$1$ ""))
sat
sat
(($$$$l$0$10000000$-1$-1$ 8))
sat
(($$$$t$7$10000007$-1$-1$ "K"))
sat
unsat
(error "line 72 column 36: model is not available")
unsat
(error "line 76 column 36: model is not available")
unsat
unsat
(error "line 84 column 36: model is not available")
unsat
(error "line 88 column 36: model is not available")
unsat
unsat
(error "line 96 column 36: model is not available")
unsat
(error "line 100 column 36: model is not available")
unsat
unsat
(error "line 108 column 36: model is not available")
unsat
(error "line 112 column 36: model is not available")
unsat
unsat
(error "line 120 column 36: model is not available")
unsat
(error "line 124 column 36: model is not available")
unsat
unsat
unsat
unsat
(error "line 140 column 36: model is not available")
unsat
(error "line 144 column 36: model is not available")
unsat
unsat
unsat
unsat
(error "line 160 column 36: model is not available")
unsat
(error "line 164 column 36: model is not available")
unsat
unsat
unsat
unsat
(error "line 180 column 36: model is not available")
unsat
(error "line 184 column 26: model is not available")

**Comment by NikolajBjorner** [comment] 2019-01-07 17:10
It is probably a duplicate of #2071

**Comment by pjljvandelaar** [comment] 2019-01-08 12:05
Thanks for solving the bug.
The crash in z3str3 is still present.

And z3 and z3str3 have different answers on the first few problems:
Z3 reports
```
PS C:\TorXakis.experiments> z3 .\logString.txt
(:name "Z3")
(:version "4.8.5 - build hashcode 14f3ff0b6325")
sat
sat
sat
(($In$1050$0$1$ ""))
sat
sat
(($$$$l$0$10000000$-1$-1$ 8))
sat
(($$$$t$7$10000007$-1$-1$ "K"))
sat
unsat
(error "line 72 column 36: model is not available")
```
while z3str3 reports
```
PS C:\TorXakis.experiments> z3 smt.string_solver=z3str3 .\logString.txt
(:name "Z3")
(:version "4.8.5 - build hashcode 14f3ff0b6325")
sat
sat
sat
(($In$1050$0$1$ "aaaaaaaaaaa"))
sat
sat
(($$$$l$0$10000000$-1$-1$ 9))
sat
(($$$$t$7$10000007$-1$-1$ "q"))
sat
sat
(($$$$t$7$10000007$-1$-1$ "\x07"))
```
before crashing.

So one of them must be wrong.
According to me, z3str3 is wrong (since "\x07" is not in [A-Z]).

So the remaining problems (crash + wrong solve) seem z3str3 issues.

**Comment by NikolajBjorner** [comment] 2019-10-14 03:56
@mtrberzi

**Comment by mtrberzi** [comment] 2019-10-15 14:55
Still seeing invalid models after the related fix, so taking a look at this one

**Comment by mtrberzi** [comment] 2019-10-15 15:49
It looks like we are not seeing the user-defined function in z3str3, so the regex solver is never used (hence the model can be anything...)

@NikolajBjorner for a user-defined function defined in `define-funs-rec` is it expected that the simplifier/rewriter will expand it? If not, what's the suggested way to handle these functions in a theory solver?

**Comment by NikolajBjorner** [comment] 2019-10-15 16:10
recursive functions are expanded by theory_recfun. The usual theory combination approach is used to integrate recursive functions with other theories. Thus, theory_str is not responsible for unfolding their definitions. 
The rewriter also has hooks to handle rewriting in the presence of recursive functions.

**Comment by mtrberzi** [comment] 2019-10-15 16:13
OK, so the definition could be expanded by another theory solver - got it. That means I likely have to pick up these terms during the search.

**Comment by mtrberzi** [comment] 2019-10-17 19:19
I have a potential fix that I will PR after some testing. The issue I identified regarding not picking up new string terms during the search seems to be the root cause. Z3str3 timeouts on some of the later check-sat calls but the "obvious" invalid models are now corrected (SAT with a valid model) on all of the earlier calls that Z3str3 is able to solve.

**Comment by mtrberzi** [comment] 2019-10-22 00:48
Found #2646 while testing this patch, want to fix that first as it's much easier and should help me make sure I didn't introduce any errors while fixing this.

**Comment by mtrberzi** [comment] 2019-10-22 21:48
Opened #2651

**Closed** 2019-10-24 22:20 UTC
Labels: string, z3str3
