### ISSUE TITLE
Solution soundness issue on string formula

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#5099] opened 2021-03-13 14:45 UTC
z3 04ac5f03f70a9ab
~~~~
z3  xx.smt2 
sat
cvc4 -q --strings-exp xx.smt2 
unsat
~~~~
~~~~
(declare-fun str1 () String)
(declare-fun str2 () String)
(declare-fun str4 () String)
(assert (= false false false false (distinct (str.to_int (str.++ str4 str1)) 0) false))
(assert (str.prefixof "Qs" (str.++ (str.++ str4 str1) str2)))
(check-sat)
~~~~

**Comment by wintered** [comment] 2021-03-15 15:20
Issue is likely a duplicate of https://github.com/Z3Prover/z3/issues/5096 posted earlier.

**Closed** 2021-03-15 16:43 UTC
