### ISSUE TITLE
friend operator of z3::expr should not be "inlined" inside class

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#241] opened 2015-10-13 08:32 UTC
This will prevent using function pointer to reference those operators.

e.g. I can't write the following code
```
z3::expr (*plus_op)(z3::expr const &, z3::expr const &) = &z3::operator+
```
unless
```
class z3::expr {
...
friend z3::expr operator+(z3::expr const &, z3::expr const &) {...}
...
};
```
changed to
```
class z3::expr {
...
};
friend z3::expr operator+(z3::expr const &, z3::expr const &) {...}
```

**Comment by cgcgbcbc** [comment] 2015-10-13 09:41
Or I need to declare every friend operator in the file where I want use function pointer to reference the operator.

**Comment by wintersteiger** [comment] 2015-10-19 12:41
Is this a duplicate of #218 for the `operator+` or do you want both changes at the same time?

**Comment by cgcgbcbc** [comment] 2015-10-19 12:53
I think they may be of the same issue, according to `The C++ Programming Language 3rd Edition (Stroustrap), p279`, if a friend function's argument access class members, it should be found. There must be something wrong with apple's compiler.

ref: http://stackoverflow.com/a/8304007/2581091

**Comment by NikolajBjorner** [comment] 2015-10-30 22:37
cgcgbcbc, does this address your issue?

**Comment by cgcgbcbc** [comment] 2015-10-31 06:02
@NikolajBjorner  yep

**Comment by wintersteiger** [comment] 2015-10-31 13:29
Great, thanks for letting us know!

**Closed by wintersteiger** 2015-10-31 13:29 UTC
