### ISSUE TITLE
Soundness bug in QF_LIA 

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2871] opened 2020-01-20 18:36 UTC
Hi,
Z3 returns wrong answer on the following files. 
[1.smt2](https://github.com/Z3Prover/z3/files/4087415/1.smt2.zip)
[2.smt2.zip](https://github.com/Z3Prover/z3/files/4087417/2.smt2.zip)
[3.smt2.zip](https://github.com/Z3Prover/z3/files/4087418/3.smt2.zip)
[4.smt2.zip](https://github.com/Z3Prover/z3/files/4087419/4.smt2.zip)
[5.smt2.zip](https://github.com/Z3Prover/z3/files/4087420/5.smt2.zip)
[6.smt2.zip](https://github.com/Z3Prover/z3/files/4087421/6.smt2.zip)
[7.smt2.zip](https://github.com/Z3Prover/z3/files/4087422/7.smt2.zip)
[8.smt2.zip](https://github.com/Z3Prover/z3/files/4087423/8.smt2.zip)
[9.smt2.zip](https://github.com/Z3Prover/z3/files/4087424/9.smt2.zip)
[10.smt2.zip](https://github.com/Z3Prover/z3/files/4087425/10.smt2.zip)

Every formula at each level in the assertion stack is satisfiable. But z3 would return unsat at some level. For example for file 1.smt2, i get:

sat
sat
sat
sat
sat
sat
unsat
sat
sat
sat
sat

CVC4 gives me:

sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

$ git log -1
commit 321bad2c84c9bb0c58f44d5797bdf993b47b09d4
Author: Christoph M. Wintersteiger <cwinter@microsoft.com>
Date:   Mon Jan 20 17:06:35 2020 +0000
    Fix for implicit consts in FPA models. Fixes #2865.

**Comment by NikolajBjorner** [comment] 2020-01-20 20:08
Are these the smallest repros possible?

**Comment by numairmansur** [comment] 2020-01-20 20:13
I am sorry they actually aren't. I can run the minimiser and edit the PR with smaller files.

**Comment by numairmansur** [comment] 2020-01-21 07:47
Here are some relatively small examples:

[small1.smt2](https://github.com/Z3Prover/z3/files/4089754/small1.smt2.zip)
[small2.smt2](https://github.com/Z3Prover/z3/files/4089755/small2.smt2.zip)
[small3.smt2](https://github.com/Z3Prover/z3/files/4089756/small3.smt2.zip)
[small4.smt2](https://github.com/Z3Prover/z3/files/4089757/small4.smt2.zip)

**Comment by NikolajBjorner** [comment] 2020-01-21 16:49
@levnach The master branch creates a lia conflict with empty explanation. This seems to have been fixed in the levnach branch, or at least I don't easily repro.

**Comment by NikolajBjorner** [comment] 2020-01-21 17:28
in the gomory cut code, the case where a non-basic variable has integer assignment there is no tracking of the explanations on the bounds of that variable. Seems it is necessary to add explanations, as sketched below.

```
 if (p.coeff().is_int()) {
                    // m_fj will be zero and no monomial will be added
                    if (at_lower(j)) {
                        m_ex.push_justification(column_lower_bound_constraint(j));            
                    }
                    if (at_upper(j)) {
                        m_ex.push_justification(column_upper_bound_constraint(j));
                    }
                    continue;
                }
```

**Comment by levnach** [comment] 2020-01-21 19:29
Integrated to levnach fork.

**Comment by NikolajBjorner** [comment] 2020-01-21 20:31
not really, it is #if 0'ed out at the moment. Can you check if just one bound is required and otherwise check correctness?

**Comment by levnach** [comment] 2020-01-21 21:18
The Gomory cut is based on a precondition, as https://lara.epfl.ch/w/_media/projects:simplexdplltreport.pdf points out, that each non-basic variable is not free and has a value at its lower or upper bound. Therefore, at least one of the bound constraints needs to be provided; and the new code does it.

**Comment by NikolajBjorner** [comment] 2020-01-22 15:19
I am not sure about this being the real issue. The legacy solver also skips this case and integral columns shouldn't contribute to non-integrality of the base variables.

Running on small1.smt2 it looks like the offending row does not have the property that the basic variable is the sum of non-basic variables. This is an assumption for applying the cut. 
What is a quick way to check this pre-condition (check that the row evaluates to 0).

**Comment by levnach** [comment] 2020-01-22 19:31
lar_solver::row_is_correct(unsigned i), where i is the index of the row.

**Comment by NikolajBjorner** [comment] 2020-01-22 20:30
Right, the rows are not correct and this is why gomory provides the wrong result. It assumes the rows are correct. I pushed a filter on incorrect rows, but a root cause understanding of whether this is legal would be useful.

**Comment by NikolajBjorner** [comment] 2020-01-22 20:31
https://github.com/Z3Prover/z3/commit/ad965ac89663016d6842a89fbab1583605d2ddf7

**Comment by levnach** [comment] 2020-01-23 01:34
The row becomes incorrect during the "find_cube()" rounding. Currently there is indication in lar_solver that this rounding has happened. I should track it and restore the tableau in this case.

**Comment by NikolajBjorner** [comment] 2020-01-24 23:45
we should be good now.

**Closed by NikolajBjorner** 2020-01-24 23:45 UTC
