### ISSUE TITLE
configure failure with python2

### ISSUE THREAD

**Issue by Drup** [Z3Prover/z3#302] opened 2015-11-09 16:14 UTC
See [this gist](https://gist.github.com/Drup/792aa5cc5e271e3f04e1). The final line is: 
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 26: ordinal not in range(128)
```

It works correctly with python3

**Comment by wintersteiger** [comment] 2015-11-09 16:36
Can't reproduce this, I must be using a different compiler. Could you add the output of `g++ --version` and of `clang++ --version`?

**Comment by Drup** [comment] 2015-11-09 16:42
```
% g++ --version
g++ (GCC) 5.2.0
Copyright © 2015 Free Software Foundation, Inc.

% clang++ --version
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by wintersteiger** [comment] 2015-11-09 16:51
Looks like Python 2.x doesn't like that copyright character (\xa9) in the output of g++. Will have to figure out why it's trying to decode ASCII instead of UTF-8.

**Comment by wintersteiger** [comment] 2015-11-13 17:15
I just committed a fix for this problem, but I'm unable to properly test it here. Could you report back whether this also fixes your problems?

**Comment by wintersteiger** [comment] 2015-11-20 08:28
This should be fixed, so I'm closing the issue. Feel free to create a new one if further problems remain.

**Closed by wintersteiger** 2015-11-20 08:28 UTC
Labels: bug
