### ISSUE TITLE
(model_evaluator.array_equalities=false) Refutation soundness bug in LRA logic

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4776] opened 2020-11-05 09:14 UTC
This formula should be sat since a=0 is a model, while Z3 with model_evaluator.array_equalities=false reports unsat:
```
[513] % z3release small.smt2
sat
[514] % z3release model_evaluator.array_equalities=false small.smt2
unsat
[515] % 
[515] % cat small.smt2
(declare-fun a () Real)
(assert (forall ((b Real)) (= (= b a) (= b 0))))
(check-sat)
[516] %
```
Commit: d0d06c2

**Comment by NikolajBjorner** [comment] 2020-11-09 20:16
duplicate of #3047

**Closed by NikolajBjorner** 2020-11-09 20:16 UTC
