### ISSUE TITLE
Assertion violation at src/smt/smt_internalizer.cpp:475

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3627] opened 2020-03-31 19:27 UTC
```
% z3 bug.smt2
ASSERTION VIOLATION
File: ../src/smt/smt_internalizer.cpp
Line: 475
b_internalized(n)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
ASSERTION VIOLATION
File: ../src/util/old_vector.h
Line: 375
idx < size()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
% cat bug.smt2
(set-option :trace  true)  
(declare-fun a () Real) 
(declare-fun b () Real)  
(declare-fun c () Real) 
(declare-fun d () Real) 
(declare-fun g () Real) 
(declare-fun e () Real) 
(declare-fun f () Real) 
(assert (not (= 0 d))) 
(assert (not (= (and (= c f)(< (* (+ (* (mod b g) e))) 0.0 e a)  
(<= 0.0 b g))(< 0 (*(+ e (mod b f))) 0))))  
(check-sat) 
```

OS: Ubuntu 18.04
Commit: 0ff97d5

**Comment by NikolajBjorner** [comment] 2020-03-31 19:32
duplicate of  #3625

**Closed by NikolajBjorner** 2020-03-31 19:32 UTC
