### ISSUE TITLE
Closing context from Java segfaults

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#719] opened 2016-08-22 16:48 UTC
Hi @NikolajBjorner 

unfortunately after 4720d578a4e70decfab8afb5c49b008f1ca4a01d and b080e3a216b7127d36be5562f46a00ab4f25e65e every context closure operation segfaults for us:

```
Stack: [0x00007f9479e05000,0x00007f9479f06000],  sp=0x00007f9479f02ab0,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libz3.so+0x2156d4]  ast_manager::~ast_manager()+0x584
```

**Comment by cheshire** [comment] 2016-08-22 17:10
If I use the debug build, I get a slightly more helpful error message:

```
Stack: [0x00007f9ad135a000,0x00007f9ad145b000],  sp=0x00007f9ad1457920,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libz3.so+0x12fa54]  vector<parameter, true, unsigned int>::begin() const+0xc
C  [libz3.so+0x12fa14]  decl_info::get_parameters() const+0x1c
C  [libz3.so+0x27e1d4]  ast_manager::~ast_manager()+0x3a6
C  [libz3.so+0x157155]  void deallocf<ast_manager>(char const*, int, ast_manager*)+0x28
C  [libz3.so+0x156675]  scoped_ptr<ast_manager>::~scoped_ptr()+0x27
C  [libz3.so+0x15336c]  api::context::~context()+0x28a
C  [libz3.so+0x15698d]  void deallocf<api::context>(char const*, int, api::context*)+0x28
C  [libz3.so+0x1544c8]  Z3_del_context+0x6b
C  [libz3java.so+0x1aa1c]  Java_com_microsoft_z3_Native_INTERNALdelContext+0x20
j  com.microsoft.z3.Native.INTERNALdelContext(J)V+0
j  com.microsoft.z3.Native.delContext(J)V+1
j  org.sosy_lab.java_smt.solvers.z3.Z3SolverContext.close()V+33
j  org.sosy_lab.java_smt.test.SolverBasedTest0.closeSolver()V+4
v  ~StubRoutines::call_stub
```

**Comment by wintersteiger** [comment] 2016-08-22 18:20
Thanks for the report! Did you get any warnings about memory leaks in debug mode?

**Comment by cheshire** [comment] 2016-08-23 10:13
Yes, it says: "ast_manager LEAKED: 28"

**Comment by wintersteiger** [comment] 2016-08-23 13:32
@NikolajBjorner could you take a look at this? I recently saw a similar case where the new garbage collection code at ast.cpp:1437:

    mark_array_ref(mark, to_func_decl(n)->get_info()->get_num_parameters(), to_func_decl(n)->get_info()->get_parameters());

threw a segfault because `...->get_info()` returned 0 (possibly after previously freeing (parts of) some objects due to leaks).

**Comment by NikolajBjorner** [comment] 2016-08-23 14:45
info fields are optional. The GC didn't check for this. Should be fixed by now.

**Comment by cheshire** [comment] 2016-08-23 16:16
@NikolajBjorner Nope, still segfaulting, now on floats theory:

```
ast_manager LEAKED: 22
Leaked: FloatingPoint
Leaked: Bool
Leaked: Int
Leaked: NaN
id: 8
Leaked: +zero
id: 19
Leaked: -oo
id: 10
Leaked: +oo
id: 9
Leaked: Real
Leaked: decl x :: FloatingPoint[8:23]
(fp.mul roundNearestTiesToEven fp.numeral[@1] x)
id: 12
ast_manager LEAKED: 8
```

```
Stack: [0x00007f465f739000,0x00007f465f83a000],  sp=0x00007f465f8367d8,  free space=1013k
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.microsoft.z3.Native.INTERNALdelContext(J)V+0
j  com.microsoft.z3.Native.delContext(J)V+1
j  org.sosy_lab.java_smt.solvers.z3.Z3SolverContext.close()V+33
```

**Comment by NikolajBjorner** [comment] 2016-08-23 17:04
Do you have a more detailed stack?

**Comment by cheshire** [comment] 2016-08-23 17:09
Actually, last message was:

```
Leaked: fp.numeral[@1]
id: 20
```

I do not have the full stack, you can see the whole error at http://metaworld.me/hs_err_pid19020.log

**Comment by cheshire** [comment] 2016-08-23 17:10
Oh wait, I do, sorry:

```
C  [libz3.so+0x276be1]  decl_info::del_eh(ast_manager&)+0x53
C  [libz3.so+0x281868]  ast_manager::delete_node(ast*)+0x8f6
C  [libz3.so+0x27e69a]  ast_manager::~ast_manager()+0x86c
C  [libz3.so+0x157155]  void deallocf<ast_manager>(char const*, int, ast_manager*)+0x28
C  [libz3.so+0x156675]  scoped_ptr<ast_manager>::~scoped_ptr()+0x27
C  [libz3.so+0x15336c]  api::context::~context()+0x28a
C  [libz3.so+0x15698d]  void deallocf<api::context>(char const*, int, api::context*)+0x28
C  [libz3.so+0x1544c8]  Z3_del_context+0x6b

``

**Comment by NikolajBjorner** [comment] 2016-08-23 17:20
I would need a repro or more details for this one. Can you dump a log?

**Comment by cheshire** [comment] 2016-08-23 17:27
We have a heisenbug here :)

After enabling path logging, now I get:

```
ASSERTION VIOLATION
File: ../src/ast/rewriter/rewriter_def.h
Line: 172
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

**Comment by cheshire** [comment] 2016-08-23 17:29
Log @ http://metaworld.me/z3_segfault.log

**Comment by NikolajBjorner** [comment] 2016-08-31 01:28
were you able to repro the problem using the log? I am not.

**Comment by NikolajBjorner** [comment] 2016-08-31 01:37
got repro after adding lines:

R
P 0x7f161053d868
C 8

**Comment by NikolajBjorner** [comment] 2016-08-31 03:08
Additional analysis of the log file shows that there is a leak from above Z3. The reference count to the expressions that are simplified are incremented twice but decremented only once. Z3 doesn't crash now, so in a sense the issue is fixed. If you believe the caller-side reference count should not leak, then it would make sense to look into how the simplified expressions are managed.

**Comment by cheshire** [comment] 2016-09-02 10:26
Thanks, seems to work!

**Closed** 2016-09-02 10:31 UTC
Labels: bug
