### ISSUE TITLE
Z3 segfaults from interrupts

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#595] opened 2016-05-11 12:55 UTC
Hi,

I have many benchmarks where Z3 dies with a segfault when interrupted.
From my understanding, it happens when Z3 is in a state where it does not expect an interrupt (e.g. `is_numeral_ast`).

To be fair, the documentation for `Z3_interrupt` does say "This procedure can be used to interrupt: solvers, simplifiers and tactics.".
However in our application a listener on a different thread creates an interrupt, and it has no way of knowing in which state Z3 is currently in.
Would it be possible to make Z3 more amenable to interruptions?

**Comment by NikolajBjorner** [comment] 2016-05-11 12:59
Sure, we try to fix crashes encountered as a consequence of interrupts. It really helps when there are non-timer dependent repros. For example, the resource counter can be used to reproduce interrupts in fairly reliable ways (except when Z3 uses timers internally). Internally, Z3 checks a resource manager for whether an interrupt happened. Interrupts are treated the same way as timeouts and as resource limits.

**Comment by NikolajBjorner** [comment] 2016-05-16 03:45
any chance of a repro or stack trace?

**Comment by cheshire** [comment] 2016-05-24 13:18
@NikolajBjorner It's difficult to communicate it.
If I generate a random boolean formula, give it to Z3, than interrupt it on a different thread, and repeat all that in a loop, I get all kinds of different errors, including segfaults and messages about corrupted double linked lists. All of that is done in Java though.
I will try to generate a log file from Z3, I suppose that should be enough.

**Comment by NikolajBjorner** [comment] 2016-05-24 15:10
Log files will not work directly because the log is rerun sequentially. 
The last interrupt will be interpreted after the call that crashed completed.
But, it is a starting point, I could try to set resource limits on the log file. Resource limits and interrupts are handled by the same code.

**Comment by PhilippWendler** [comment] 2016-06-30 11:19
I have a case where the replay log from a segfault on interrupt also does lead to a segfault when it is replayed. It is reproducible with revision e518d4a. The file is too large to upload it on GitHub, so I created an [archive with replay log and core dump](http://students.fim.uni-passau.de/~wendler/Z3-segfault-interrupt-is_app.zip). The segfault is in `Z3_is_app`.

It would be great if this could be fixed, because this segfault happens quite often with my use case.

**Comment by NikolajBjorner** [comment] 2016-07-01 01:07
The caller is passing in a pointer which is "null". I can make the API resilient against null pointers here, but the cause of the grief must be somewhere else. The code above is passing in something it shouldn't.

**Comment by PhilippWendler** [comment] 2016-07-01 06:29
Ah, thank your for your answer. With this information I started looking around, and indeed, we call `Z3_model_get_const_interp` and pass the result to `Z3_is_app` without checking for `null`. This is a bug on our side and we will fix it.

However, I find it strange that this only ever happens to us immediately after calling `Z3_interrupt`. If I do not interrupt Z3 it seems I get a normal result, not `null` from `Z3_model_get_const_interp`. Could it be that this function returns `null` in case of interrupts? If yes, this would mean that it is not possible to distinguish between an interrupt and "doesn't matter" value. Could you change this? We can work around it because we know when we interrupt Z3, but for other people I guess this might lead to wrong interpretations about models.

If it matters, we are using your Java API, so an exception from `modelGetConstInterp` in case of interrupt would be the best choice IMHO.

**Comment by PhilippWendler** [comment] 2016-07-01 10:15
I have one other case where Z3 segfaults after an interrupt. I call `Z3_get_interpolant` (making sure that I do not pass `null` for any parameter), and while this is running I interrupt Z3. Then Z3 segfaults in `model_core::get_manager()`. This seems more like an internal Z3 problem.

I have [this crash dump from the JVM](https://github.com/Z3Prover/z3/files/343161/hs_err_pid19108.txt) (created with a debug build of Z3 in revision e518d4a5fe3b824d5e9deb3d16eb1faa248a52d8). It contains a full stack trace, so maybe you are able to infer from it what the problem is.

I also have a replay log, but as you expected the segfault does not occur when replaying it. I uploaded it [here](http://students.fim.uni-passau.de/~wendler/z3-segmentation-fault-interrupt-model_core-get_manager.log.bz2) because it has 292 MB.

**Comment by NikolajBjorner** [comment] 2016-07-01 16:27
> If it matters, we are using your Java API, so an exception from  modelGetConstInterp  in case of interrupt would be the best choice IMHO.

Not sure how to address it based on your use case: the log I have does not exercise interrupts or timeouts. The code that retrieves a constant interpretation (modelGetConstInterp) does not check timeouts or interrupts.

I added a patch based on your crash dump stack in your last comment.

**Comment by PhilippWendler** [comment] 2016-07-02 08:44
Weird. We do not use Z3 timeouts, but the null result from `Z3_model_get_const_interp` occurs precisely when we interrupt Z3. Anyway, by checking the result for null we can avoid this problem, so the current state is fine for us.

Thanks for fixing the other segfault, I can confirm that it works.

This means that all instances of segfaults connected to interrupts that I could produce with my current set of tests seem to be fixed. I don't know if @cheshire has more such problems, but for me this issue could be closed.

Thanks again for working on this and fixing these problems so fast!

**Closed** 2016-07-03 17:38 UTC
