### ISSUE TITLE
Simplifcation produces nondeterministic results

### ISSUE THREAD

**Issue by rhelmot** [Z3Prover/z3#2359] opened 2019-06-22 04:21 UTC
The following script loads an expression, and then simplifies it twice. The second result (and all results afterwards?) contain an extra clause.

```python
import z3

f = z3.parse_smt2_string("""
(declare-fun canonical_0 () (_ BitVec 64))
(assert
 (let ((?x1404 (ite (bvsge (_ bv0 64) canonical_0) (_ bv0 64) canonical_0)))
 (bvule (ite (bvuge (_ bv8 64) ?x1404) ?x1404 (_ bv8 64)) (_ bv8 64))))
""")[0]

tactics = z3.Then(
    z3.Tactic("simplify"),
    z3.Tactic("unit-subsume-simplify"),
)

print(tactics(f))
print('----------------')
print(tactics(f))
```

output:

```
[[ULE(Extract(3,
              0,
              If(And(If(canonical_0 <= 0,
                        0,
                        Extract(63, 4, canonical_0)) ==
                     0,
                     ULE(If(canonical_0 <= 0,
                            0,
                            Extract(3, 0, canonical_0)),
                         8)),
                 If(canonical_0 <= 0, 0, canonical_0),
                 8)),
      8)]]
----------------
[[Extract(63,
          4,
          If(And(If(canonical_0 <= 0,
                    0,
                    Extract(63, 4, canonical_0)) ==
                 0,
                 ULE(If(canonical_0 <= 0,
                        0,
                        Extract(3, 0, canonical_0)),
                     8)),
             If(canonical_0 <= 0, 0, canonical_0),
             8)) ==
  0,
  ULE(Extract(3,
              0,
              If(And(If(canonical_0 <= 0,
                        0,
                        Extract(63, 4, canonical_0)) ==
                     0,
                     ULE(If(canonical_0 <= 0,
                            0,
                            Extract(3, 0, canonical_0)),
                         8)),
                 If(canonical_0 <= 0, 0, canonical_0),
                 8)),
      8)]]
```

I don't know if either or both of the simplifications are correct, but even if they're both correct it's very weird...

**Comment by NikolajBjorner** [comment] 2019-06-22 21:50
weird, but I can currently not reproduce it

**Comment by rhelmot** [comment] 2019-06-22 21:51
:cold_sweat: 

I can reproduce it (on linux) with both the python bindings built from master and with the z3 from `pip install z3-solver`

**Comment by NikolajBjorner** [comment] 2019-06-22 22:09
With my latest cmake based build:

root@nikolaj-sl2:~/z3/build/python# cp /mnt/c/z3/build/python/2359.py .
root@nikolaj-sl2:~/z3/build/python# python 2359.py
[[ULE(Extract(3,
              0,
              If(And(If(canonical_0 <= 0,
                        0,
                        Extract(63, 4, canonical_0)) ==
                     0,
                     ULE(If(canonical_0 <= 0,
                            0,
                            Extract(3, 0, canonical_0)),
                         8)),
                 If(canonical_0 <= 0, 0, canonical_0),
                 8)),
      8)]]
----------------
[[ULE(Extract(3,
              0,
              If(And(If(canonical_0 <= 0,
                        0,
                        Extract(63, 4, canonical_0)) ==
                     0,
                     ULE(If(canonical_0 <= 0,
                            0,
                            Extract(3, 0, canonical_0)),
                         8)),
                 If(canonical_0 <= 0, 0, canonical_0),
                 8)),
      8)]]

**Comment by rhelmot** [comment] 2019-06-22 23:32
I hate this so much. The issue is apparently only reproducable under pypy, which indicates it's probably a garbage collection issue. I'll investigate further.

**Comment by rhelmot** [comment] 2019-06-23 00:26
This sucks wildly. The angr testcase that the reduced example is based on also fails in the same way under cpython, but the reduced example passes. Nondeterminism indeed...

**Comment by NikolajBjorner** [comment] 2019-06-23 00:27
Is it a new regression?

**Comment by rhelmot** [comment] 2019-06-23 00:29
It is a new regression upon trying to upgrade angr's z3 dependency from 4.5.1 to 4.8.5.

**Comment by NikolajBjorner** [comment] 2019-06-23 00:39
OK, gives some idea. Possibly the unit-subsume-simplify tactic isn't re-entrant.
Try creating two different tactics for the two invocations.

tactics1 = z3.Then(
    z3.Tactic("simplify"),
    z3.Tactic("unit-subsume-simplify"),
)
tactics2 = z3.Then(
    z3.Tactic("simplify"),
    z3.Tactic("unit-subsume-simplify"),
)

print(tactics1(f))
print('----------------')
print(tactics2(f))

in the meanwhile I will look for clues in the tactic.

**Comment by rhelmot** [comment] 2019-06-23 00:40
making that change still produces the undesirable behavior

**Comment by NikolajBjorner** [comment] 2019-06-23 00:45
Add to script:

enable_trace("before_simplifier")
enable_trace("after_simplifier")
enable_trace("unit_subsumption_tactic")

Paste log

**Comment by rhelmot** [comment] 2019-06-23 00:55
```
-------- [before_simplifier] operator() ../src/tactic/core/simplify_tactic.cpp:48 ---------
(goal
  (let ((a!1 (ite (bvuge #x0000000000000008
                         (ite (bvsge #x0000000000000000 canonical_0)
                              #x0000000000000000
                              canonical_0))
                  (ite (bvsge #x0000000000000000 canonical_0)
                       #x0000000000000000
                       canonical_0)
                  #x0000000000000008)))
    (bvule a!1 #x0000000000000008)))
------------------------------------------------
-------- [after_simplifier] operator() ../src/tactic/core/simplify_tactic.cpp:69 ---------
(goal
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 63 4)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (= a!2 #x000000000000000)))
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 3 0)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (bvule a!2 #x8))))
------------------------------------------------
-------- [unit_subsumption_tactic] prune_clause ../src/smt/tactic/unit_subsumption_tactic.cpp:102 ---------
Removing clause 0
------------------------------------------------
-------- [unit_subsumption_tactic] reduce_core ../src/smt/tactic/unit_subsumption_tactic.cpp:73 ---------
(goal
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 3 0)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (bvule a!2 #x8))))
(goal
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 3 0)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (bvule a!2 #x8))))
------------------------------------------------
-------- [before_simplifier] operator() ../src/tactic/core/simplify_tactic.cpp:48 ---------
(goal
  (let ((a!1 (ite (bvuge #x0000000000000008
                         (ite (bvsge #x0000000000000000 canonical_0)
                              #x0000000000000000
                              canonical_0))
                  (ite (bvsge #x0000000000000000 canonical_0)
                       #x0000000000000000
                       canonical_0)
                  #x0000000000000008)))
    (bvule a!1 #x0000000000000008)))
------------------------------------------------
-------- [after_simplifier] operator() ../src/tactic/core/simplify_tactic.cpp:69 ---------
(goal
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 63 4)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (= a!2 #x000000000000000)))
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 3 0)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (bvule a!2 #x8))))
------------------------------------------------
-------- [unit_subsumption_tactic] reduce_core ../src/smt/tactic/unit_subsumption_tactic.cpp:73 ---------
(goal
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 63 4)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (= a!2 #x000000000000000)))
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 3 0)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (bvule a!2 #x8))))
(goal
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 63 4)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (= a!2 #x000000000000000)))
  (let ((a!1 (and (= (ite (bvsle canonical_0 #x0000000000000000)
                          #x000000000000000
                          ((_ extract 63 4) canonical_0))
                     #x000000000000000)
                  (bvule (ite (bvsle canonical_0 #x0000000000000000)
                              #x0
                              ((_ extract 3 0) canonical_0))
                         #x8))))
  (let ((a!2 ((_ extract 3 0)
               (ite a!1
                    (ite (bvsle canonical_0 #x0000000000000000)
                         #x0000000000000000
                         canonical_0)
                    #x0000000000000008))))
    (bvule a!2 #x8))))
------------------------------------------------
```

**Comment by NikolajBjorner** [comment] 2019-06-23 01:01
Good. The second time, the subsumption tactic does not remove clause 0.
The log
-------- [unit_subsumption_tactic] prune_clause ../src/smt/tactic/unit_subsumption_tactic.cpp:102 ---------
Removing clause 0
is missing

The subsumption tactic calls the SMT solver to check if it can remove clauses.
Somehow it can't.

I can try to repro your repro by setting up a similar environment. 
Instructions for dummies are appreciated.
To figure out where to place blame I may have to enable additional trace flags that are used by the smt solver. There are many such traces. The most important are "before_search" and "after_search"
(add enable_trace("before_search") and enable_trace("after_search") to your script).
To start with send me a version with those traces, but this seems not too simple to figure out.

**Comment by rhelmot** [comment] 2019-06-23 01:28
[z3-trace.txt with before_search and after_search](https://github.com/Z3Prover/z3/files/3317397/z3-trace.txt)

Here's the most basic repro instruction:

```
docker run -it pypy:3.5
# inside the container
pip install z3-solver
cat >z3_bug.py
[paste the script here]
[ctrl-d]
pypy3 z3_bug.py
```

but of course this doesn't get you a debug build or anything. I'm fairly sure you should just be able to install git/build-essential/etc and clone/build z3 to make it all work.

**Comment by NikolajBjorner** [comment] 2019-06-23 18:55
thanks, I now have a repro on pypy 2.7. Sorry, the before_search/after_search log options were not useful.

**Comment by NikolajBjorner** [comment] 2019-06-23 21:33
I believe I see why: 
In the first round, the simplifier pushes extract over ite because the reference count on both branches is 1.
In the second round, the pypy gc has not collected the result of the first round yet, so the reference count on the branches is > 1. The rewrite step that helps in the first round is disabled.
The relevant code would be:
https://github.com/Z3Prover/z3/blob/master/src/ast/rewriter/bv_rewriter.cpp#L788

In light of this scenario, I will try to figure out what could be a reasonable approach. For example, making the solver more resilient against global reference counts that are not relevant to expansion factors or something systematic.

**Comment by NikolajBjorner** [comment] 2019-07-03 07:10
I believe we can close this:
1. The update restores the previous behavior
2. Generally, the state of the solver depends on the reference counts of expressions. The python GC controls this and this is not under control unless you can invoke the GC explicitly.

**Closed** 2019-07-09 11:09 UTC

**Comment by rhelmot** [comment] 2020-01-18 03:03
For what it's worth, I've been noticing more instances of this cropping up lately. I haven't been able to get any of them to reproduce outside "just run this angr testcase", though. Do you care? Should we care about this in general?

**Comment by NikolajBjorner** [comment] 2020-01-18 04:19
Z3 should not have internal non-determinism. There are only a few exceptions to this statement:
when Z3 is run using a built-in tactic for selected theories, such as non-linear integer arithmetic, it tries a few tactics with short timeouts. The use of wall-clock timeout introduces non-determinism. Applications that cannot tolerate non-determism should avoid these tactics. For default incremental mode, there is no such problem and bit-vector solving isn't using timeouts.

External non-determinsm introduced by GC (python, ocaml, .net, java) will have to be handled at the application layer. Use a single solver, pin all expressions every created by the caller,... It is easier with C++ because reference counting is not delegated to a GC.

We care a lot about avoid internal non-determism. It can be a show-stopper for some applications and makes bug repros problematic. For the python GC non-determinism, not sure. I added some reference counting sensitive simplification not too long ago. It is probable that I would like to do this in some cases where and/or gets flattened to avoid a nasty overhead of flattening. To implement this in a way that is agnostic to external references, is not easy and probably not practical (it requires identifying a set of roots prior to uses of the simplifier and tell the simplifier about nodes reachable from the roots and it has to be done in a way that doesn't break the simplifier where it is used without this facility).

**Comment by rhelmot** [comment] 2020-01-22 00:24
Is there a listing of which tactics are dependent on clock time and reference counts? I searched through the wiki and the tactic headers but couldn't find anything.

As an aside which isn't really related to this issue, and I recognize that this is a really complicated request, can you recommend any resource or jumping-off point for learning how to decide which tactics are useful for different problems? I am realizing now that the list of tactics and parameters that angr uses for simplification is chosen very naively.
