### ISSUE TITLE
PadRight SMT is Unsat

### ISSUE THREAD

**Issue by arranf** [Z3Prover/z3#1067] opened 2017-06-08 12:19 UTC
I'm trying to model a PadRight function in SMT. Where for a given string to pad `s`, a string to pad with `x`, and a number of times to pad `y` a string `result` will be `s` of size y, padded with additional repeated characters from `x`.

For instance the following SMT should produce `F_`. If I changed the consts to `s="Foo"; x="_Pad"; y=16` I would expect `result` to be `Foo_Pad_Pad_Pad_`

The SMT below is apparently unsat but I can't figure out why. This is my first stab at SMT so I'm sure some of it isn't idiomatic but I do think it should work!

```
(declare-const s String)
(declare-const x String)
(declare-const y Int)

(declare-const result String)

(declare-const slen Int)
(declare-const padlen Int)

(assert (= s "F"))
(assert (= x "_"))
(assert (= y 2))
(assert (= padlen (str.len x)))
(assert (= slen (str.len s)))

(assert (= result s))
(assert (forall ((i Int)) (implies ( and (>= i slen) (<= i y) ) (= (str.at result i) (str.at x (mod i padlen))))))

(check-sat)
(get-model)
```

**Comment by delcypher** [comment] 2017-06-08 12:29
Surely 

```
(assert (= s "F"))
```

and 

```
(assert (= result s))
(assert (forall ((i Int)) (implies ( and (>= i slen) (<= i y) ) (= (str.at result i) (str.at x (mod i padlen))))))
```

contradict each other? You're asserting that `s` must be the string `"F"` but must also be equal to `result` which is not equal to `"F"`.

**Comment by delcypher** [comment] 2017-06-08 12:40
@arranf Note if you're ever unsure why Z3 thinks something is unsatisfiable asking for it to give you the unsat core might help.

```
(set-option :produce-unsat-cores true)
(declare-const s String)
(declare-const x String)
(declare-const y Int)

(declare-const result String)

(declare-const slen Int)
(declare-const padlen Int)

(assert (!(= s "F") :named a0))
(assert (!(= x "_") :named a1))
(assert (!(= y 2) :named a2))
(assert (!(= padlen (str.len x)) :named a3))
(assert (!(= slen (str.len s)) :named a4))

(assert (!(= result s) :named a6))
(assert (! (forall ((i Int)) (implies ( and (>= i slen) (<= i y) ) (= (str.at result i) (str.at x (mod i padlen))))) :named a7) )

(check-sat)
(get-unsat-core)
```

This reports

```
unsat
(a0 a6)
```

This is actually wrong though, `a7` should also be in the unsat core too. 

@NikolajBjorner @wintersteiger is this is a bug or this is expected behaviour due to the use of the quantifier?

**Comment by arranf** [comment] 2017-06-08 12:47
Thanks that's really helpful. I took out the line `(assert (= result s))` which you highlighted, I still seems unsat. So I assume something on the line with the quantifier is making it unsatisfiable. I requested the unsat-core and I get the following output
```
unknown
(error "line 20 column 15: unsat core is not available")
```

Can I ask why you have the negations in your version above?

**Comment by delcypher** [comment] 2017-06-08 12:52
@arranf 
> Can I ask why you have the negations in your version above?

Those aren't negations. This is SMT-LIB's syntax for putting an attribute on expression.  E.g.

```
(! (<some expression) : named foo)
```

In the example I gave using the unsat core I'm giving each expression given to `(assert )`  the `:named` attribute (e.g. `a0`, `a1`). This is needed when you request the unsat core because when the unsat core is reported it is given in terms of the named attributes.

**Comment by wintersteiger** [comment] 2017-06-08 13:03
Looks like a bug to me! Just `a0` and `a6` gives `(and (= s "F") (= result s))` and that's clearly satisfiable.

**Comment by delcypher** [comment] 2017-06-08 13:49
@arranf I tried rewriting this to avoid quantifiers. I wish I knew how to tell Z3 to explicitly unroll a universally quantified expression.

```
(declare-const s String)
(declare-const x String)
(declare-const y Int)

(declare-const result String)

(declare-const slen Int)
(declare-const padlen Int)
(define-fun result_cond ((i Int)) Bool
  (=>
    (and (>= i 0) (< i (+ slen (* y padlen))))
    (=
      (str.at result i)
      (ite
          (< i slen)
          (str.at s i)
          (ite
            (< i (+ slen (* y padlen)))
            (str.at x (mod i padlen))
            (str.at result i) ; dummy shouldn't be reachable due to =>
          )
      )
    )
  )
)

(assert (!(= s "Foo") :named a0))
(assert (!(= x "_") :named a1))
(assert (!(= y 3) :named a2))
(assert (!(= padlen (str.len x)) :named a3))
(assert (!(= slen (str.len s)) :named a4))

; unrolled quantifier
; Do this as many times as needed
(assert (result_cond 0))
(assert (result_cond 1))
(assert (result_cond 2))
(assert (result_cond 3))
(assert (result_cond 4))
(assert (result_cond 5))

(check-sat)
(get-model)
```

Z3 says sat for this but it gives an invalid model (it says `result` is the empty string).

```
(model 
  (define-fun slen () Int
    3)
  (define-fun s () String
    "Foo")
  (define-fun result () String
    "")
  (define-fun y () Int
    3)
  (define-fun x () String
    "_")
  (define-fun padlen () Int
    1)
)
```

What's really weird is if I add `(set-option :produce-unsat-cores true)` to the SMTLIB file then Z3 reports `unsat` which is clearly wrong.

If I tell Z3 to use the new string solver like this

```
./z3 smt.string_solver=z3str3 arranf.smt2
```

It gives a correct model for `result`

```
sat
(model 
  (define-fun slen () Int
    3)
  (define-fun s () String
    "Foo")
  (define-fun result () String
    "Foo___C")
  (define-fun y () Int
    3)
  (define-fun x () String
    "_")
  (define-fun padlen () Int
    1)
)
```

If I set `(set-option :produce-unsat-cores true)` for this query then Z3 crashes.

**Comment by NikolajBjorner** [comment] 2017-06-14 02:07
The handling of str.at was wrong causing unsoundness and wrong models in the default string solver.
Thanks for trying z3str3 which has several advantages.

**Comment by NikolajBjorner** [comment] 2017-06-20 21:49
closing as bug was addressed.

**Closed by NikolajBjorner** 2017-06-20 21:49 UTC
