### ISSUE TITLE
aborting Z3

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2621] opened 2019-10-09 11:17 UTC
When using Z3 4.7.1, typing `ctrl+c` successfully aborts Z3 execution.

However, when using Z3 4.8.4 and 4.8.6, `ctrl+c` often does not work. If I repetitively type `ctrl+c`, it sometimes aborts Z3, but not always.

Is it an intended behavior in later versions of Z3?

I am using Z3 as an underlying SMT solver in my tool written in OCaml.

**Comment by NikolajBjorner** [comment] 2019-10-09 16:08
Could be because the solver is within a phase where it isn't safe to cancel. 
It would safely exit when it exits that region.
In other cases, the solver isn't checking the cancellation flag when it could.
You can break Z3 in a debugger on your input to see where it is (assuming mixed mode debugging from OCaml works in your environment). 
Closing as there isnt anything reproducible.

**Closed by NikolajBjorner** 2019-10-09 16:08 UTC
