### ISSUE TITLE
Crash on using floating point and real transformation (version Win-64 bits 4.4.0)

### ISSUE THREAD

**Issue by GuillaumeLangelier** [Z3Prover/z3#156] opened 2015-07-10 14:52 UTC
The following smt2 code makes the last stable binary release (4.4.0) crash on windows 64 bits.

	(declare-const x Real)
	(declare-const y Real)
	(declare-const res Real)

	(define-fun NonLinProd( (num1 Real) (num2 Real) (result Real) ) Bool
		(and
			(fp.eq 
				((_ to_fp 11 53) roundTowardZero result) 
				(fp.mul roundTowardZero 
					((_ to_fp 11 53) roundTowardZero num1) 
					((_ to_fp 11 53) roundTowardZero num2)))
		)	
	)
	;(assert (= res 25))
	(assert (NonLinProd x y res))
	(check-sat)
	;(get-model)

Actually, if result and res are floating point numbers of the good type, it also crashes. If everything (num1, num2, x, y) is floating point, then it works fine.

While I am here, I might as well ask some question that are related to this piece of code. As you can see, I was playing with the translation between reals and floating point. 

* In the API documentation and in some StackOverflow answers, the following warning is mentioned concerning the function “to_real”. However, there is no similar warning for the function “to_fp”. Is the warning also true for “to_fp”?

>  Note that this type of conversion will often result in non-linear constraints over real terms.

* Depending on your answer from the first question, wouldn’t the code shown here be able to mix together reals and floating points without non-linear constraints?

* Does z3 support a fixed point precision numbers as opposed to floating point numbers or do you have any plans to introduce them? The exponent being a constant in this case would probably eliminate non-linear constraints. This kind of precision would be “good enough” for my needs and probably for many problems as well.

**Comment by wintersteiger** [comment] 2015-07-14 18:29
Does not reproduce in unstable, so I'm closing this as fixed.

Any interaction between floating point numbers and real numbers will automatically be non-linear, because the floating-point operations are highly non-linear, even discontinuous from the real-theory's point of view. The encoding shown here does not call real-multiplication directly, but fp.mul is just as non-linear a constraint, and in some ways it's even worse for the real-theory, because it doesn't see any constraints, but it still has to magically guess the right numbers (sometimes it gets lucky, but most of the times it won't). On this particular problem it doesn't get lucky even when we fix `res` to 25.0, as suggested. But, if we fix `res` to 0.0 then it does get lucky. So yes, the warning goes both ways. 

There are no fixed-point numbers and there are no plans to introduce them because they can trivially be constructed from floating-point numbers by fixing the exponent to some desired constant value, so there's really no need for a separate class of functions. Also, the lower limit for exponent bits is 3, so "almost fixed point numbers"  can be used without additional constraints. Further, simple bit-vectors can also be used trivially to represent fixed-point numbers by defining bv = x * 2^32 for a 32-bit fixed-point number.

**Closed by wintersteiger** 2015-07-14 18:29 UTC

**Comment by GuillaumeLangelier** [comment] 2015-07-15 15:18
Alright, thank you for your answers. I wouldn’t know how to have a constant exponent in smt2 for a floating point, but I guess it wouldn’t help me much anyway since you mention that fp.mul is also non-linear. I am aware it is possible to encore a fixed point number in a machine 32 bits integer but I read that bv2int and int2bv are considered uninterpreted functions so it is making this approach less useful in my case. Moreover, even if I can circumvent that, I am guessing bvmul, bvsdiv … are also non-linear which remains a problem for what I intend to do.
 
My goal (and hope) was to avoid non-linearity by transferring to a bit representation (a la CBMC) but just when needed and use the powerful SMT-solver for the rest of the formula. CBMC is transforming numbers into a bit representation and does the arithmetic calculation using circuits-like formulas. It uses a SAT-solver in the end. It is slower due to the increased number of Boolean variables and clauses, but it does find a model on some code sample containing non-linearity where an SMT encoding + z3 approach does not terminate. They say multiplication is complex also so maybe it is because they are avoiding parts of the formula that they come up with a solution.

Anyway, I guess I am going to try to attack the problem from another angle. 

Thank you again.
