### ISSUE TITLE
Crash with assertions enabled

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2563] opened 2019-09-17 15:29 UTC
Hi, for the following formula z3 (compiled with assertions enabled) crashes with  an assertion violation

```
(declare-fun a () String)                                                       
(declare-fun b () String)                                                       
(declare-fun c () String)                                                       
(assert                                                                         
  (not                                                                          
    (= (str.substr a 0 (str.len b)) "")                                         
  )                                                                             
)                                                                               
(assert                                                                         
  (and                                                                          
    (=                                                                          
      (ite                                                                      
        (=                                                                      
          (str.len                                                              
            (str.substr (str.replace (str.replace a b "") "29M8u" "") 1 (- (str.len c) 1))
          )                                                                     
          0                                                                     
        )                                                                       
        1                                                                       
        0                                                                       
      )                                                                         
      (ite                                                                      
        (=                                                                      
          (str.at (str.replace (str.replace a b "") "29M8u" "") 0)              
          ""                                                                    
        )                                                                       
        1                                                                       
        0                                                                       
      )                                                                         
      (ite                                                                      
        (=                                                                      
          (str.len (str.replace (str.replace a b "") "29M8u" ""))               
          0                                                                     
        )                                                                       
        1                                                                       
        0                                                                       
      )                                                                         
      0                                                                         
    )                                                                           
    (>=                                                                         
      (-                                                                        
        (str.len (str.replace (str.replace a b "") "29M8u" ""))                 
        1                                                                       
      )                                                                         
      0                                                                         
    )                                                                           
  )                                                                             
)                                                                               
(check-sat)                                                                           
```

```
ASSERTION VIOLATION
File: ../src/smt/theory_seq.cpp
Line: 2240
len1 == len2
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Revision: 69abe16

**Comment by NikolajBjorner** [comment] 2019-09-17 15:52
duplicate of #2562

**Closed by NikolajBjorner** 2019-09-17 15:52 UTC
