### ISSUE TITLE
(par-or t s) (or-else t s) only use the first tactic

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#269] opened 2015-10-28 09:08 UTC
The following problem can be solved quickly
```
(declare-fun NONDET_FLOAT_0 () Real)
(declare-fun lv_IN_1 () Real)
(declare-fun lv_n_8_1 () Bool)
(declare-fun lv_n_9_1 () Int)
(declare-fun lv_n_10_1 () Bool)
(declare-fun lv_n_164_1 () Real)
(declare-fun lv_n_165_1 () Real)
(assert (let ((a!1 (* (- 1.0)
              (/ (+ lv_IN_1
                    (* (- (/ 1.0 6.0)) lv_IN_1 lv_IN_1 lv_IN_1)
                    (* (/ 1.0 120.0) lv_IN_1 lv_IN_1 lv_IN_1 lv_IN_1 lv_IN_1)
                    (* (/ 1.0 5040.0)
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1))
                 (+ 1.0
                    (* (- (/ 1.0 2.0)) lv_IN_1 lv_IN_1)
                    (* (/ 1.0 24.0) lv_IN_1 lv_IN_1 lv_IN_1 lv_IN_1)
                    (* (/ 1.0 720.0)
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1
                       lv_IN_1))))))
(let ((a!2 (/ (+ lv_IN_1
                 a!1
                 (* (- (/ 1.0 6.0))
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1))
                 (* (/ 1.0 120.0)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1))
                 (* (/ 1.0 5040.0)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)))
              (+ 1.0
                 (* (- (/ 1.0 2.0)) (+ lv_IN_1 a!1) (+ lv_IN_1 a!1))
                 (* (/ 1.0 24.0)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1))
                 (* (/ 1.0 720.0)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1)
                    (+ lv_IN_1 a!1))))))
  (and (<= (/ 1.0 10.0) lv_n_165_1)
       (= lv_n_164_1 (+ lv_IN_1 a!1 (* (- 1.0) a!2)))
       (= lv_n_165_1 lv_n_164_1)
       lv_n_10_1
       (= lv_n_9_1 (ite lv_n_8_1 1 0))
       (= lv_n_10_1 (not (= lv_n_9_1 0)))
       (= lv_n_8_1 (not (<= (/ 13421773.0 33554432.0) lv_IN_1)))
       (not (<= lv_IN_1 (- (/ 13421773.0 33554432.0))))
       (= lv_IN_1 NONDET_FLOAT_0)))))
(check-sat-using (par-or qfnra smt))
```
But if the last line is replaced by `(check-sat-using (par-or smt qfnra))`, it will hangs.

**Comment by cgcgbcbc** [comment] 2015-10-28 09:14
Another example, the following problem can be solved by default smt solver but can't  be solved by qfnra tactic. And par-or seems return the first tactic's result.
```
(declare-fun NONDET_INT_32_0 () Int)
(declare-fun lv_n_1_1 () Int)
(declare-fun lv_n_8_1 () Bool)
(declare-fun lv_n_9_1 () Int)
(declare-fun lv_n_10_1 () Bool)
(declare-fun lv_n_18_1 () Bool)
(declare-fun lv_n_19_1 () Int)
(declare-fun lv_n_15_1 () Real)
(declare-fun lv_n_14_1 () Int)
(assert (and (= lv_n_19_1 0)
     (= lv_n_14_1 (* lv_n_1_1 lv_n_1_1))
     (= lv_n_15_1 (to_real lv_n_14_1))
     (= lv_n_18_1 (not (= lv_n_15_1 2.0)))
     (= lv_n_19_1 (ite lv_n_18_1 1 0))
     lv_n_10_1
     (= lv_n_9_1 (ite lv_n_8_1 1 0))
     (= lv_n_10_1 (not (= lv_n_9_1 0)))
     (= lv_n_8_1 (<= lv_n_1_1 10))
     (>= lv_n_1_1 (- 10))
     (= lv_n_1_1 NONDET_INT_32_0)))
(check-sat) ; unsat
(check-sat-using (then qfnra)) ; unknown
(check-sat-using (par-or smt qfnra)) ; unsat
(check-sat-using (par-or qfnra smt)) ; unknown, expect unsat!
```

**Comment by cgcgbcbc** [comment] 2015-10-28 09:15
And `(or-else)` has the same problem in the second example.

**Comment by wintersteiger** [comment] 2015-10-28 15:36
Thanks for the report, there was indeed a bug in the par-or tactic. It aborted when the first tactic finished, not when the first tactic finished & decided the problem.

Re-opening as the performance issue hasn't been resolved yet.

**Comment by wintersteiger** [comment] 2015-10-28 18:53
I had to take that last change back. The real issue was the documentation for par-or: The documentation said "until one of them succeeds" which does _not_ mean "until the problem is decided" it only means "until one of the tactics does not fail by throwing an exception". Therefore, par-or is aborted as soon as one of the sub-tactics returns "unknown". I have added a statement to the par-or comments in the various APIs.

**Comment by wintersteiger** [comment] 2015-10-28 18:56
To clarify further: In the case of the examples given, this tactic will give the right behaviour:

    (check-sat-using (par-or
        (then smt fail-if-undecided)
        (then qfnra fail-if-undecided)))

**Comment by wintersteiger** [comment] 2015-10-28 19:06
@NikolajBjorner 's commit just fixed the problem with the smt tactic not being interruptable, so all problems are fixed, closing the issue.

**Closed by wintersteiger** 2015-10-28 19:06 UTC

**Comment by cgcgbcbc** [comment] 2015-10-29 01:57
Thank you all very much !
