### ISSUE TITLE
Python Assertion Violation - unreachable code was reached when parallel.enable is True 

### ISSUE THREAD

**Issue by azewiusz** [Z3Prover/z3#4798] opened 2020-11-16 11:29 UTC
I get this message when running Solver in parallel mode with Python

```
ASSERTION VIOLATION
File: D:\a\1\s\src\ast/rewriter/rewriter_def.h
Line: 213
UNREACHABLE CODE WAS REACHED.
Z3 4.8.9.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
```
Code executed on an AMD Phenom II X6 (6 cores)
```python
s = z3.SolverFor("QF_BV")
z3.set_option("parallel.enable", True)
z3.set_option("parallel.threads.max", 6)
```
this error does not appear when running in non-parallel mode.

**Comment by azewiusz** [comment] 2020-11-16 13:32
Apparently the set_option has to be before constructor.

**Comment by NikolajBjorner** [comment] 2020-11-16 17:03
The unreachable error should never happen regardless of how options are set.

**Comment by kitlith** [comment] 2020-11-21 07:53
```
ASSERTION VIOLATION
File: ../src/ast/rewriter/rewriter_def.h
Line: 213
UNREACHABLE CODE WAS REACHED.
Z3 4.8.9.0
```

I'm also encountering this (exact?) bug, except it doesn't matter where i put set_param vs set_option. I don't have a minimal reproduction, heck I only have one known way of reproducing it (and running stuff through simplification causes it to stop reproducing), but I *can* reproduce it, and here's the script I've been using: https://gist.github.com/kitlith/b8465f62f8ffc1d951ba3ee007cee1b1

there's a block of comments detailing different possible parameters that i've been testing with, but the current setup consistently triggers the bug in a little over 30 seconds on my system.

**Comment by azewiusz** [comment] 2020-11-23 07:04
I closed this one over-zealously -
this one however came back in different example.
Example code that reproduces this issue: https://github.com/azewiusz/z3/blob/master/test.py

**Comment by NikolajBjorner** [comment] 2020-11-28 02:19
Repros on windows are somewhat elusive. In a loop, it eventually crashes after 192 invocations and then it isn't clear what the root cause might be.
If you are able to do mixed mode debugging and get a stack it might shed some light. Visual studio supported mixed-mode Python/Native debugging. Hopefully your environment does too.

**Comment by azewiusz** [comment] 2020-11-29 11:12
Here is what I managed to trace back, using Visual Studio 2017, It took quite a long time to stop at this exception.
[repro.txt](https://github.com/Z3Prover/z3/files/5612036/repro.txt)

**Comment by azewiusz** [comment] 2020-12-03 11:52
@NikolajBjorner - is it possible to investigate further with attached stack trace data ?

**Comment by NikolajBjorner** [comment] 2020-12-03 18:14
I looked at it, but this is not an easy bug to trace back to origins. The reference count on expressions is incorrect at the location of the crash, but the places where the reference counts are maligned could be many other places. In the past I rely on reliable reproducibility to narrow the root causes and it may take days to debug, and I don't have spare days floating around at the moment.

**Comment by azewiusz** [comment] 2020-12-03 18:38
@NikolajBjorner thanks for reply.

**Comment by kitlith** [comment] 2020-12-03 21:35
@azewiusz does running your expressions through simplification help mitigate the issue in your example? If so, maybe that can be stated as a workaround until it is fixed.

@NikolajBjorner would it help if someone provided remote access to a machine that does reproduce the issue consistantly?

**Comment by NikolajBjorner** [comment] 2020-12-18 07:03
Should be fixed now with #4899

**Comment by azewiusz** [comment] 2020-12-20 20:35
@kitlith, @NikolajBjorner  - I re-ran my code on latest version and could not recreate the issue. Looks to be fixed.

**Comment by NikolajBjorner** [comment] 2020-12-20 23:54
Yes, I thought I already closed this issue. But it was definitely under very similar circumstances and the same place. 
The text-based repro was relatively quick and consistent.
The root cause, though had to do with cloning some internal state. It was thread safe, but had enough reference counts outstanding to trigger incorrect expressions to be built.

**Closed by NikolajBjorner** 2020-12-20 23:54 UTC
