### ISSUE TITLE
timeout option is _not_ working in z3py

### ISSUE THREAD

**Issue by Ipsitakoley** [Z3Prover/z3#3065] opened 2020-02-21 10:41 UTC
from z3 import *
s = Solver()
s.set(timeout=3600000)

I have given a timeout of 1 hour.. But the solver still running while attempting to get a solution. It should stop after 1 hour.

**Comment by nunoplopes** [comment] 2020-02-22 18:56
Could you provide the formula please?
Without a full repro, it's impossible to debug this.

**Comment by NikolajBjorner** [comment] 2020-02-29 15:54
will close this the next few days without repro.

**Comment by antonper** [comment] 2020-03-09 16:43
Faced the similar issue, when tried to switch from 4.8.5 to 4.8.7. I have noticed that solver with 1000 ms timeout, in reality timeouts in 15 sec. The constraints are automatically generated. I will try to get update the issue with minimal example ASAP.

**Comment by NikolajBjorner** [comment] 2020-03-09 16:49
Thanks.
As a general comment it is not possible to address reports without repros.
The code base is immense. I just fixed a timeout due to an infinite loop, a different timeout was due to bit-blasting an enormous bit-vector expression. These scenarios were totally unrelated.
To ensure that z3 exits gracefully it checks for cancellation in select places. 
If a time-consuming computation goes on without cancellation checks (or a non-termination bug), it is can take much more than the user-specified timeout.

**Comment by antonper** [comment] 2020-03-09 17:06
Thank you @NikolajBjorner !
I attached the solver.sexpr() dump
[c.sexpr.zip](https://github.com/Z3Prover/z3/files/4307970/c.sexpr.zip)
This solver is exactly the one that didn't respect 1 sec timeout
I also noticed the regression of the default solver in 4.8.7 (compared to 4.8.5)
But with BV solver the runtime looks normal. Unfortunately looks like SolveFor('BV') don't expect 'timeout' param. What are the options to run the BV solver with timeout options?
Thank you for the help!

**Comment by NikolajBjorner** [comment] 2020-03-09 18:52
this one is a regression introduced by strengthening equality solving. In your case, this added functionality is a pure waste of time. A fix involves down-throttling it a bit.
You can disable it by: 

           z3 c.sexpr  tactic.solve_eqs.context_solve=false

**Comment by NikolajBjorner** [comment] 2020-03-09 19:00
The absence of timeout support on the solver object, when created by BV (and other logic), is a different miss. Added fix for this too.

**Comment by antonper** [comment] 2020-03-09 20:10
Thank you very much! I really appreciate your advises!

**Comment by NikolajBjorner** [comment] 2020-03-10 23:25
I think the reported issue was fixed. 
There are without doubt other sources of the soft timeout not being fully available, bug reports with repros like the one above will do the trick.

**Closed by NikolajBjorner** 2020-03-10 23:25 UTC
Labels: no-repro
