### ISSUE TITLE
Assertion violation at /src/qe/qsat.cpp

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5852] opened 2022-02-18 13:10 UTC
Hi,
For this instance, z3https://github.com/Z3Prover/z3/commit/2e00f2f32db7a05dbecbdb75ca7a1e1918a6a0a8 (debug)
```
$ z3debug delta.smt2
ASSERTION VIOLATION
File: ../src/qe/qsat.cpp
Line: 651
validate_defs("check_sat")
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
$ cat delta.smt2
(declare-fun v () Int)
(declare-fun a () (Array Bool Bool))
(assert (or (forall ((V Int)) (or (exists ((V Bool)) (or (exists ((V Int)) (not (select a (= (abs v) (abs (abs v))))))))))))
(assert (exists ((V Int)) (and (forall ((V Bool)) (select a true)))))
(check-sat-using (then solve-eqs qsat))
```

**Comment by NikolajBjorner** [comment] 2022-02-22 01:50
this was a duplicate of similar bug

**Closed by NikolajBjorner** 2022-02-22 01:50 UTC
