### ISSUE TITLE
Possible bug in Z3 str.to.int

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1334] opened 2017-10-30 09:04 UTC
I am experimenting with Z3 str.to.int to evaluate its performance.
I came across the following example which looks like a bug (also posted on [SO](https://stackoverflow.com/questions/47011112/possible-bug-in-z3-str-to-int)):

```
(declare-const si String)
(declare-const sj String)
(declare-const sk String)
(declare-const i     Int)
(declare-const j     Int)
(declare-const k     Int)

(assert (= (str.to.int si) i))
(assert (= (str.to.int sj) j))
(assert (= (str.to.int sk) (* k k)))
(assert (= (- j i) k))
(assert (> i 7422885))
(assert (< j 74228850))
(assert (< i j))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                  ;
; When I remove this comment everything works fine ;
;                                                  ;
;(assert (< 135 k))                                ;
;                                                  ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(check-sat)
(get-value (si sj sk i j k))
```
Output: (**that's a bug, right?**)

 ```
sat
((si "74228847")
 (sj "!0!")
 (sk "1")
 (i 74228847)
 (j 74228848)
 (k 1))
```

When I remove the comment I get this correct output:

```
sat
((si "74228713")
 (sj "74228849")
 (sk "18496")
 (i 74228713)
 (j 74228849)
 (k 136))
```

**Comment by NikolajBjorner** [comment] 2018-03-04 03:39
This was fixed and duplicate of https://github.com/Z3Prover/z3/issues/1500

**Closed by NikolajBjorner** 2018-03-04 03:39 UTC
