### ISSUE TITLE
Invalid model on QF_FP formula with fp.sqrt roundTowardPositive operators

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3496] opened 2020-03-23 17:06 UTC
Hi,
For this formula:
```
(define-sort FPN () (_ FloatingPoint 55 53))
(declare-fun a () FPN)
(declare-fun b () FPN)
(assert (= (fp.sqrt roundTowardPositive a) b))
(check-sat)
```
Z3  gives an invalid model:
```
[1510] % z3 model_validate=true small.smt2
sat
(error "line 5 column 10: an invalid model was generated")
[1511] % 
[1511] % cat small.smt2
(define-sort FPN () (_ FloatingPoint 55 53))
(declare-fun a () FPN)
(declare-fun b () FPN)
(assert (= (fp.sqrt roundTowardPositive a) b))
(check-sat)
```

OS: Ubuntu 18.04
Commit: f158ab8

**Comment by wintersteiger** [comment] 2020-07-17 13:47
Duplicate of #3776, the rounder had the same problem with huge exponents on all operations, including `fp.sqrt`.

**Closed** 2020-07-17 13:47 UTC
