### ISSUE TITLE
"Not an inequality" during interpolation

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#667] opened 2016-07-04 08:58 UTC
This [interpolation query](http://rise4fun.com/Z3/j0eO) ([replay log](https://github.com/Z3Prover/z3/files/345944/z3-interpolation-not-an-inequality.txt)) produces the error "not an inequality" with revision 
0d0d504d62735616bf38c8b2671ea91d68fb5fd2 of Z3. Is this a bug or a problem in the interpolation query?

**Comment by PhilippWendler** [comment] 2018-04-04 08:14
Could you please explain why this was closed? Is the replay log not enough?

Btw., I have reported [several interpolation problems](https://github.com/Z3Prover/z3/issues?q=interpolation%20created:2016-06..2016-07) almost two years ago, and it seems like nobody has looked at them yet. Is there any chance these could get fixed?

**Comment by wintersteiger** [comment] 2018-04-05 19:55
@NikolajBjorner assigned the no-repro label, i.e. he can't reproduce the problem on his side.

(But, yes, we also wonder when the interpolation problems will be fixed.)

**Comment by NikolajBjorner** [comment] 2018-04-10 12:44
Seems we are heading towards deprecating these features from the code base, around May or June, as they are prone to bit rot and they are not being maintained.

**Comment by NikolajBjorner** [comment] 2018-05-25 18:04
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.

**Closed by NikolajBjorner** 2018-05-25 18:04 UTC
Labels: no-repro
