### ISSUE TITLE
Spacer seg fault in `get_answer`

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#3646] opened 2020-04-01 08:06 UTC
Opening the issue to keep track of the seg fault, since I and @agurfinkel already talked about it.

z3 version: latest master
https://gist.github.com/leonardoalt/5f8c4194c1035bf3d255c0d914803175
z3 fp.xform.inline_linear=false fp.xform.inline_eager=false seg_fault.smt2

**Comment by NikolajBjorner** [comment] 2020-04-01 09:01
it uses arrays. Model evaluation returns terms using (as-array k!234).
Changing 

            if (num == 0 && (fid == null_family_id || is_uninterp)) { // || m_ar.is_as_array(f)) {

to
        if (num == 0 && (fid == null_family_id || is_uninterp) || m_ar.is_as_array(f)) {

ensures that as-array gets evaluated. 
Unfortunately this broke some assumptions in rewriter_def at some point
(constants that don't take any arguments are not supposed to be rewritten).
So it would be good to examine what regressions this change could do.

**Comment by agurfinkel** [comment] 2020-04-01 14:34
@NikolajBjorner I see issues with evaluation of strings at which point this code was added and then reverted. Are these the cases to look at for regression?

In general, is it reasonable to assume that it is desirable for model evaluator to never output `as_array` and instead expand arrays (either by lambdas or by a sequence of stores?)

@leonardoalt I will look whether I can do something to work around this at the spacer end. If not, this will take some time since I need to cache back `model_evaluator` and understand the regressions that @NikolajBjorner is talking about above.

**Comment by agurfinkel** [comment] 2020-04-01 14:36
For record keeping, the relevant commits seem to be 809b0ebca76e6ea9c03c4bc362ce4295526f6e3d and e65a5d0f4739ec7a89ec4500f5ab00ca9ca96de8

**Comment by leonardoalt** [comment] 2020-04-01 14:47
@agurfinkel no hurry, and thanks for looking into it

**Comment by agurfinkel** [comment] 2020-04-10 14:02
fixed by 44302f3f2afe19c4d535d9b4193d40493c5a19f2

@leonardoalt counterexamples should work now with arrays and datatypes. Please let me know if you run into more similar issues.

**Closed** 2020-04-10 14:01 UTC

**Comment by leonardoalt** [comment] 2020-04-14 14:33
@agurfinkel thanks, cex works fine now!
I ran into an issue (`Uninterpreted 'mod' in <null>`) with another test but seems unrelated, will open a separate issue.
