### ISSUE TITLE
Interpolation Failure

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#662] opened 2016-06-29 11:38 UTC
I am using Z3 with its Java API, and on one call to `getInterpolant` there is a exception with the message `interpolation failure`. I am using quantifiers, UFs, and linear arithmetic. The problem is reproducible with this [replay log](https://gist.github.com/PhilippWendler/cae2807300b09a3c00e6873e42e2710e/raw/78f207a569b1c2d01be4b3871d932f4e30b46ba6/z3-interpolation-failure.log) with the command-line Z3 binary from revision 8aee7129f69c8852ff1bf70dc29217d874292800.

**Comment by NikolajBjorner** [comment] 2016-06-29 12:10
Confirmed, the replay log throws the "interpolation failure" exception. It would require additional instrumentation and logging to narrow down the cause.

**Comment by PhilippWendler** [comment] 2016-06-29 13:45
Is there something I can help to make it easier to debug this? I have a test case for our application that triggers this reproducibly, so I could for example run a debug build or something like this.

**Comment by NikolajBjorner** [comment] 2016-06-30 00:01
OK

**Comment by PhilippWendler** [comment] 2016-06-30 07:05
Sorry, I don't understand why this issue was closed. Does it mean the problem can't be fixed?

I created a debug build of Z3 and rerun my test case, but the replay log does not seem to contain more information than the replay log of the production build (same file size), so if you need more information you would need to tell me how to extract it.

**Comment by wintersteiger** [comment] 2016-06-30 13:19
Reopening this as it wasn't clear what has happened. @NikolajBjorner: Did you assume that there will be a new bug report when @PhilippWendler has an interaction log or similar?

**Comment by NikolajBjorner** [comment] 2016-07-01 00:47
sorry, mistake, I was closing some issues and clicked around too fast.

**Comment by NikolajBjorner** [comment] 2018-05-25 18:03
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.

**Closed by NikolajBjorner** 2018-05-25 18:03 UTC
