### ISSUE TITLE
Soundness bug in QF_S in z3-seq

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2828] opened 2019-12-26 04:52 UTC
Hi,
On the latest nightly build z3-seq gives wrong answer on the following file:

[qf_s.smt2.zip](https://github.com/Z3Prover/z3/files/4001414/qf_s.smt2.zip)

All the formulas at every level in the assertion stack are satisfiable.

$ /z3-nightly/bin/z3 qf_s.smt2
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
unsat

While z3str3 and CVC4 return:

sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

**Comment by NikolajBjorner** [comment] 2020-01-25 00:08
Fixed, seems #2860 was a duplicate of this

**Closed by NikolajBjorner** 2020-01-25 00:08 UTC
Labels: string
