### ISSUE TITLE
Assertion violation for opt instance at theory_diff_logic_def.h:934

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3419] opened 2020-03-19 16:36 UTC
Hi, for the following instance, z3 (Commit e075f38) throws an assertion violation
[theory_diff_logic_def934.txt](https://github.com/Z3Prover/z3/files/4355746/theory_diff_logic_def934.txt)
~~~~
File: ../src/smt/theory_diff_logic_def.h
Line: 934
m_graph.is_feasible(edge_id)
~~~~

**Comment by NikolajBjorner** [comment] 2020-03-19 16:39
duplicate of #3417?

**Closed by NikolajBjorner** 2020-03-19 16:39 UTC
