### ISSUE TITLE
iZ3 - wrong interpolant

### ISSUE THREAD

**Issue by agriggio** [Z3Prover/z3#54] opened 2015-04-22 20:15 UTC
Here's another case where Z3 produces an incorrect interpolant (the
formula generated is not implied by A). I'm trying to understand what is
going on, but I haven't been able to identify the source of the problem
yet.

```
(set-logic QF_LRA)
(declare-fun t2.j.at2 () Real)
(declare-fun t1.i.at2 () Real)
(declare-fun t1.i.at1 () Real)
(declare-fun t1.k.at2 () Real)
(declare-fun t1.k.at1 () Real)
(declare-fun t1.loc_j.at2 () Real)
(declare-fun t1.loc_j.at1 () Real)
(declare-fun t2.j.at1 () Real)
(declare-fun t2.k.at2 () Real)
(declare-fun t2.k.at1 () Real)
(declare-fun t2.loc_i.at2 () Real)
(declare-fun t2.loc_i.at1 () Real)
(declare-fun t1.i.at0 () Real)
(declare-fun t1.k.at0 () Real)
(declare-fun t1.loc_j.at0 () Real)
(declare-fun t2.j.at0 () Real)
(declare-fun t2.k.at0 () Real)
(declare-fun t2.loc_i.at0 () Real)
(declare-fun t1.location.1.at2 () Bool)
(declare-fun t1.location.1.at1 () Bool)
(declare-fun t1.location.0.at2 () Bool)
(declare-fun t1.location.0.at1 () Bool)
(declare-fun t1.EVENT.0.at1 () Bool)
(declare-fun t2.EVENT.0.at1 () Bool)
(declare-fun t2.location.1.at2 () Bool)
(declare-fun t2.location.1.at1 () Bool)
(declare-fun t2.location.0.at2 () Bool)
(declare-fun t2.location.0.at1 () Bool)
(declare-fun t1.location.1.at0 () Bool)
(declare-fun t1.location.0.at0 () Bool)
(declare-fun t1.EVENT.0.at0 () Bool)
(declare-fun t2.EVENT.0.at0 () Bool)
(declare-fun t2.location.1.at0 () Bool)
(declare-fun t2.location.0.at0 () Bool)
;; A:
(define-fun .A () Bool
(let ((a!1 (not (and (= t2.k.at0 t2.k.at1)
                     (and (= t2.j.at0 t2.j.at1) (= t2.loc_i.at1 t2.loc_i.at0))
                     t2.location.1.at1
                     t2.location.0.at1)))
      (a!3 (and t2.EVENT.0.at0
                (and (not t2.location.0.at0) (not t2.location.1.at0))
                (not (<= 5 t2.k.at0))
                (not (and (= t2.k.at0 t2.k.at1)
                          (= t2.j.at0 t2.j.at1)
                          (= t1.i.at0 t2.loc_i.at1)
                          t2.location.1.at1
                          (not t2.location.0.at1)))))
      (a!4 (= (+ t2.j.at0 (* (- 1) t2.j.at1) t2.loc_i.at0) 0))
      (a!6 (= (+ t2.k.at0 (* (- 1) t2.k.at1)) (- 1)))
      (a!8 (not (and (not (and t2.location.0.at0 t2.location.0.at1))
                     (or t2.location.0.at0 t2.location.0.at1))))
      (a!9 (not (and (not (and t2.location.1.at0 t2.location.1.at1))
                     (or t2.location.1.at0 t2.location.1.at1))))
      (a!10 (and t1.EVENT.0.at0
                 (not (<= 5 t1.k.at0))
                 (and (not t1.location.0.at0) (not t1.location.1.at0))
                 (not (and (= t1.k.at0 t1.k.at1)
                           (= t1.i.at0 t1.i.at1)
                           (= t2.j.at0 t1.loc_j.at1)
                           t1.location.1.at1
                           (not t1.location.0.at1)))))
      (a!11 (= (+ t1.i.at0 (* (- 1) t1.i.at1) t1.loc_j.at0) 0))
      (a!13 (not (and (= t1.k.at0 t1.k.at1)
                      (and (= t1.i.at0 t1.i.at1) (= t1.loc_j.at1 t1.loc_j.at0))
                      t1.location.1.at1
                      t1.location.0.at1)))
      (a!15 (= (+ t1.k.at0 (* (- 1) t1.k.at1)) (- 1)))
      (a!17 (not (and (not (and t1.location.0.at0 t1.location.0.at1))
                      (or t1.location.0.at0 t1.location.0.at1))))
      (a!18 (not (and (not (and t1.location.1.at0 t1.location.1.at1))
                      (or t1.location.1.at0 t1.location.1.at1)))))
(let ((a!2 (not (and t2.EVENT.0.at0
                     (<= 5 t2.k.at0)
                     (and (not t2.location.0.at0) (not t2.location.1.at0))
                     a!1)))
      (a!5 (and t2.EVENT.0.at0
                (not t2.location.0.at0)
                t2.location.1.at0
                (not (and (= t2.k.at0 t2.k.at1)
                          (= t2.loc_i.at1 t2.loc_i.at0)
                          a!4
                          t2.location.0.at1
                          (not t2.location.1.at1)))))
      (a!7 (not (and a!6
                     (and (= t2.j.at0 t2.j.at1) (= t2.loc_i.at1 t2.loc_i.at0))
                     (not t2.location.0.at1)
                     (not t2.location.1.at1))))
      (a!12 (and t1.EVENT.0.at0
                 (not t1.location.0.at0)
                 t1.location.1.at0
                 (not (and (= t1.k.at0 t1.k.at1)
                           (= t1.loc_j.at1 t1.loc_j.at0)
                           a!11
                           t1.location.0.at1
                           (not t1.location.1.at1)))))
      (a!14 (not (and t1.EVENT.0.at0
                      (<= 5 t1.k.at0)
                      (and (not t1.location.0.at0) (not t1.location.1.at0))
                      a!13)))
      (a!16 (not (and a!15
                      (and (= t1.i.at0 t1.i.at1) (= t1.loc_j.at1 t1.loc_j.at0))
                      (not t1.location.0.at1)
                      (not t1.location.1.at1)))))
  (and true
       (= t1.i.at0 1)
       (= t1.k.at0 0)
       (not t1.location.0.at0)
       (not t1.location.1.at0)
       (= t2.j.at0 1)
       (= t2.k.at0 0)
       (not t2.location.0.at0)
       (not t2.location.1.at0)
       (<= t1.i.at0 144)
       (<= t2.j.at0 144)
       a!2
       (not a!3)
       (not a!5)
       (not (and t2.EVENT.0.at0 t2.location.0.at0 (not t2.location.1.at0) a!7))
       (not (and t2.EVENT.0.at0 a!1 t2.location.0.at0 t2.location.1.at0))
       (or t2.EVENT.0.at0
           (and (= t2.loc_i.at1 t2.loc_i.at0)
                (= t2.k.at0 t2.k.at1)
                (= t2.j.at0 t2.j.at1)
                a!8
                a!9))
       (not a!10)
       (not (and t1.EVENT.0.at0 t2.EVENT.0.at0))
       (or t1.EVENT.0.at0 t2.EVENT.0.at0)
       (not a!12)
       a!14
       (not (and t1.EVENT.0.at0 t1.location.0.at0 (not t1.location.1.at0) a!16))
       (not (and t1.EVENT.0.at0 a!13 t1.location.0.at0 t1.location.1.at0))
       (or t1.EVENT.0.at0
           (and (= t1.loc_j.at1 t1.loc_j.at0)
                (= t1.k.at0 t1.k.at1)
                (= t1.i.at0 t1.i.at1)
                a!17
                a!18))))))
;; B:
(define-fun .B () Bool
(let ((a!1 (not (and (= t2.k.at1 t2.k.at2)
                     (and (= t2.j.at1 t2.j.at2) (= t2.loc_i.at1 t2.loc_i.at2))
                     t2.location.1.at2
                     t2.location.0.at2)))
      (a!3 (and t2.EVENT.0.at1
                (and (not t2.location.0.at1) (not t2.location.1.at1))
                (not (<= 5 t2.k.at1))
                (not (and (= t2.k.at1 t2.k.at2)
                          (= t2.j.at1 t2.j.at2)
                          (= t1.i.at1 t2.loc_i.at2)
                          t2.location.1.at2
                          (not t2.location.0.at2)))))
      (a!4 (= (+ t2.j.at1 t2.loc_i.at1 (* (- 1) t2.j.at2)) 0))
      (a!6 (= (+ t2.k.at1 (* (- 1) t2.k.at2)) (- 1)))
      (a!8 (not (and (not (and t2.location.0.at1 t2.location.0.at2))
                     (or t2.location.0.at1 t2.location.0.at2))))
      (a!9 (not (and (not (and t2.location.1.at1 t2.location.1.at2))
                     (or t2.location.1.at1 t2.location.1.at2))))
      (a!10 (and t1.EVENT.0.at1
                 (and (not t1.location.0.at1) (not t1.location.1.at1))
                 (not (<= 5 t1.k.at1))
                 (not (and (= t1.k.at1 t1.k.at2)
                           (= t1.i.at1 t1.i.at2)
                           (= t2.j.at1 t1.loc_j.at2)
                           t1.location.1.at2
                           (not t1.location.0.at2)))))
      (a!11 (= (+ t1.i.at1 t1.loc_j.at1 (* (- 1) t1.i.at2)) 0))
      (a!13 (not (and (= t1.k.at1 t1.k.at2)
                      (and (= t1.i.at1 t1.i.at2) (= t1.loc_j.at1 t1.loc_j.at2))
                      t1.location.1.at2
                      t1.location.0.at2)))
      (a!15 (= (+ t1.k.at1 (* (- 1) t1.k.at2)) (- 1)))
      (a!17 (not (and (not (and t1.location.0.at1 t1.location.0.at2))
                      (or t1.location.0.at1 t1.location.0.at2))))
      (a!18 (not (and (not (and t1.location.1.at1 t1.location.1.at2))
                      (or t1.location.1.at1 t1.location.1.at2)))))
(let ((a!2 (not (and t2.EVENT.0.at1
                     (and (not t2.location.0.at1) (not t2.location.1.at1))
                     (<= 5 t2.k.at1)
                     a!1)))
      (a!5 (and t2.EVENT.0.at1
                t2.location.1.at1
                (not t2.location.0.at1)
                (not (and (= t2.k.at1 t2.k.at2)
                          (= t2.loc_i.at1 t2.loc_i.at2)
                          a!4
                          t2.location.0.at2
                          (not t2.location.1.at2)))))
      (a!7 (not (and a!6
                     (and (= t2.j.at1 t2.j.at2) (= t2.loc_i.at1 t2.loc_i.at2))
                     (not t2.location.0.at2)
                     (not t2.location.1.at2))))
      (a!12 (and t1.EVENT.0.at1
                 t1.location.1.at1
                 (not t1.location.0.at1)
                 (not (and (= t1.k.at1 t1.k.at2)
                           (= t1.loc_j.at1 t1.loc_j.at2)
                           a!11
                           t1.location.0.at2
                           (not t1.location.1.at2)))))
      (a!14 (not (and t1.EVENT.0.at1
                      (and (not t1.location.0.at1) (not t1.location.1.at1))
                      (<= 5 t1.k.at1)
                      a!13)))
      (a!16 (not (and a!15
                      (and (= t1.i.at1 t1.i.at2) (= t1.loc_j.at1 t1.loc_j.at2))
                      (not t1.location.0.at2)
                      (not t1.location.1.at2)))))
  (and true
       t2.location.1.at1
       (not t2.location.0.at1)
       (not t1.location.1.at1)
       (not t1.location.0.at1)
       (= t1.i.at1 1)
       (= t1.k.at1 0)
       (= t2.j.at1 1)
       (= t2.k.at1 0)
       (<= t1.i.at1 144)
       (<= t2.j.at1 144)
       a!2
       (not a!3)
       (not a!5)
       (not (and t2.EVENT.0.at1 t2.location.0.at1 (not t2.location.1.at1) a!7))
       (not (and t2.EVENT.0.at1 t2.location.1.at1 t2.location.0.at1 a!1))
       (or t2.EVENT.0.at1
           (and (= t2.loc_i.at1 t2.loc_i.at2)
                (= t2.k.at1 t2.k.at2)
                (= t2.j.at1 t2.j.at2)
                a!8
                a!9))
       (not a!10)
       (not (and t1.EVENT.0.at1 t2.EVENT.0.at1))
       (or t1.EVENT.0.at1 t2.EVENT.0.at1)
       (not a!12)
       a!14
       (not (and t1.EVENT.0.at1 t1.location.0.at1 (not t1.location.1.at1) a!16))
       (not (and t1.EVENT.0.at1 t1.location.1.at1 t1.location.0.at1 a!13))
       (or t1.EVENT.0.at1
           (and (= t1.loc_j.at1 t1.loc_j.at2)
                (= t1.k.at1 t1.k.at2)
                (= t1.i.at1 t1.i.at2)
                a!17
                a!18))
       (not (= t2.j.at2 1))
       (not (<= t2.j.at2 144))))))
;; interpolant computed:
(define-fun .I () Bool
(or (not (= 0 t2.k.at1))
    (not (= 1 t2.j.at1))
    (not (= 0 t1.k.at1))
    (not (= 1 t1.i.at1))))

(compute-interpolant (and (interp .A) .B))
(exit)

(push 1)
(assert (and .A (not .I)))
(check-sat)
(pop 1)
(exit)
```

**Comment by kenmcmil** [comment] 2015-05-18 17:30
Again, this problem could have to do with the use of Real.

**Comment by agriggio** [comment] 2015-05-19 09:56
Thanks for the reply. However, if I change the var types from `Real` to
`Int`, and the logic from `QF_LRA` to `AUFLIA` I get a different but
still wrong result. Here's the modified example (tried with the latest
revision from the unstable branch):

```
(set-logic AUFLIA)
(declare-fun t2.j.at2 () Int)
(declare-fun t1.i.at2 () Int)
(declare-fun t1.i.at1 () Int)
(declare-fun t1.k.at2 () Int)
(declare-fun t1.k.at1 () Int)
(declare-fun t1.loc_j.at2 () Int)
(declare-fun t1.loc_j.at1 () Int)
(declare-fun t2.j.at1 () Int)
(declare-fun t2.k.at2 () Int)
(declare-fun t2.k.at1 () Int)
(declare-fun t2.loc_i.at2 () Int)
(declare-fun t2.loc_i.at1 () Int)
(declare-fun t1.i.at0 () Int)
(declare-fun t1.k.at0 () Int)
(declare-fun t1.loc_j.at0 () Int)
(declare-fun t2.j.at0 () Int)
(declare-fun t2.k.at0 () Int)
(declare-fun t2.loc_i.at0 () Int)
(declare-fun t1.location.1.at2 () Bool)
(declare-fun t1.location.1.at1 () Bool)
(declare-fun t1.location.0.at2 () Bool)
(declare-fun t1.location.0.at1 () Bool)
(declare-fun t1.EVENT.0.at1 () Bool)
(declare-fun t2.EVENT.0.at1 () Bool)
(declare-fun t2.location.1.at2 () Bool)
(declare-fun t2.location.1.at1 () Bool)
(declare-fun t2.location.0.at2 () Bool)
(declare-fun t2.location.0.at1 () Bool)
(declare-fun t1.location.1.at0 () Bool)
(declare-fun t1.location.0.at0 () Bool)
(declare-fun t1.EVENT.0.at0 () Bool)
(declare-fun t2.EVENT.0.at0 () Bool)
(declare-fun t2.location.1.at0 () Bool)
(declare-fun t2.location.0.at0 () Bool)
;; A:
(define-fun .A () Bool
(let ((a!1 (not (and (= t2.k.at0 t2.k.at1)
                     (and (= t2.j.at0 t2.j.at1) (= t2.loc_i.at1 t2.loc_i.at0))
                     t2.location.1.at1
                     t2.location.0.at1)))
      (a!3 (and t2.EVENT.0.at0
                (and (not t2.location.0.at0) (not t2.location.1.at0))
                (not (<= 5 t2.k.at0))
                (not (and (= t2.k.at0 t2.k.at1)
                          (= t2.j.at0 t2.j.at1)
                          (= t1.i.at0 t2.loc_i.at1)
                          t2.location.1.at1
                          (not t2.location.0.at1)))))
      (a!4 (= (+ t2.j.at0 (* (- 1) t2.j.at1) t2.loc_i.at0) 0))
      (a!6 (= (+ t2.k.at0 (* (- 1) t2.k.at1)) (- 1)))
      (a!8 (not (and (not (and t2.location.0.at0 t2.location.0.at1))
                     (or t2.location.0.at0 t2.location.0.at1))))
      (a!9 (not (and (not (and t2.location.1.at0 t2.location.1.at1))
                     (or t2.location.1.at0 t2.location.1.at1))))
      (a!10 (and t1.EVENT.0.at0
                 (not (<= 5 t1.k.at0))
                 (and (not t1.location.0.at0) (not t1.location.1.at0))
                 (not (and (= t1.k.at0 t1.k.at1)
                           (= t1.i.at0 t1.i.at1)
                           (= t2.j.at0 t1.loc_j.at1)
                           t1.location.1.at1
                           (not t1.location.0.at1)))))
      (a!11 (= (+ t1.i.at0 (* (- 1) t1.i.at1) t1.loc_j.at0) 0))
      (a!13 (not (and (= t1.k.at0 t1.k.at1)
                      (and (= t1.i.at0 t1.i.at1) (= t1.loc_j.at1 t1.loc_j.at0))
                      t1.location.1.at1
                      t1.location.0.at1)))
      (a!15 (= (+ t1.k.at0 (* (- 1) t1.k.at1)) (- 1)))
      (a!17 (not (and (not (and t1.location.0.at0 t1.location.0.at1))
                      (or t1.location.0.at0 t1.location.0.at1))))
      (a!18 (not (and (not (and t1.location.1.at0 t1.location.1.at1))
                      (or t1.location.1.at0 t1.location.1.at1)))))
(let ((a!2 (not (and t2.EVENT.0.at0
                     (<= 5 t2.k.at0)
                     (and (not t2.location.0.at0) (not t2.location.1.at0))
                     a!1)))
      (a!5 (and t2.EVENT.0.at0
                (not t2.location.0.at0)
                t2.location.1.at0
                (not (and (= t2.k.at0 t2.k.at1)
                          (= t2.loc_i.at1 t2.loc_i.at0)
                          a!4
                          t2.location.0.at1
                          (not t2.location.1.at1)))))
      (a!7 (not (and a!6
                     (and (= t2.j.at0 t2.j.at1) (= t2.loc_i.at1 t2.loc_i.at0))
                     (not t2.location.0.at1)
                     (not t2.location.1.at1))))
      (a!12 (and t1.EVENT.0.at0
                 (not t1.location.0.at0)
                 t1.location.1.at0
                 (not (and (= t1.k.at0 t1.k.at1)
                           (= t1.loc_j.at1 t1.loc_j.at0)
                           a!11
                           t1.location.0.at1
                           (not t1.location.1.at1)))))
      (a!14 (not (and t1.EVENT.0.at0
                      (<= 5 t1.k.at0)
                      (and (not t1.location.0.at0) (not t1.location.1.at0))
                      a!13)))
      (a!16 (not (and a!15
                      (and (= t1.i.at0 t1.i.at1) (= t1.loc_j.at1 t1.loc_j.at0))
                      (not t1.location.0.at1)
                      (not t1.location.1.at1)))))
  (and true
       (= t1.i.at0 1)
       (= t1.k.at0 0)
       (not t1.location.0.at0)
       (not t1.location.1.at0)
       (= t2.j.at0 1)
       (= t2.k.at0 0)
       (not t2.location.0.at0)
       (not t2.location.1.at0)
       (<= t1.i.at0 144)
       (<= t2.j.at0 144)
       a!2
       (not a!3)
       (not a!5)
       (not (and t2.EVENT.0.at0 t2.location.0.at0 (not t2.location.1.at0) a!7))
       (not (and t2.EVENT.0.at0 a!1 t2.location.0.at0 t2.location.1.at0))
       (or t2.EVENT.0.at0
           (and (= t2.loc_i.at1 t2.loc_i.at0)
                (= t2.k.at0 t2.k.at1)
                (= t2.j.at0 t2.j.at1)
                a!8
                a!9))
       (not a!10)
       (not (and t1.EVENT.0.at0 t2.EVENT.0.at0))
       (or t1.EVENT.0.at0 t2.EVENT.0.at0)
       (not a!12)
       a!14
       (not (and t1.EVENT.0.at0 t1.location.0.at0 (not t1.location.1.at0) a!16))
       (not (and t1.EVENT.0.at0 a!13 t1.location.0.at0 t1.location.1.at0))
       (or t1.EVENT.0.at0
           (and (= t1.loc_j.at1 t1.loc_j.at0)
                (= t1.k.at0 t1.k.at1)
                (= t1.i.at0 t1.i.at1)
                a!17
                a!18))))))
;; B:
(define-fun .B () Bool
(let ((a!1 (not (and (= t2.k.at1 t2.k.at2)
                     (and (= t2.j.at1 t2.j.at2) (= t2.loc_i.at1 t2.loc_i.at2))
                     t2.location.1.at2
                     t2.location.0.at2)))
      (a!3 (and t2.EVENT.0.at1
                (and (not t2.location.0.at1) (not t2.location.1.at1))
                (not (<= 5 t2.k.at1))
                (not (and (= t2.k.at1 t2.k.at2)
                          (= t2.j.at1 t2.j.at2)
                          (= t1.i.at1 t2.loc_i.at2)
                          t2.location.1.at2
                          (not t2.location.0.at2)))))
      (a!4 (= (+ t2.j.at1 t2.loc_i.at1 (* (- 1) t2.j.at2)) 0))
      (a!6 (= (+ t2.k.at1 (* (- 1) t2.k.at2)) (- 1)))
      (a!8 (not (and (not (and t2.location.0.at1 t2.location.0.at2))
                     (or t2.location.0.at1 t2.location.0.at2))))
      (a!9 (not (and (not (and t2.location.1.at1 t2.location.1.at2))
                     (or t2.location.1.at1 t2.location.1.at2))))
      (a!10 (and t1.EVENT.0.at1
                 (and (not t1.location.0.at1) (not t1.location.1.at1))
                 (not (<= 5 t1.k.at1))
                 (not (and (= t1.k.at1 t1.k.at2)
                           (= t1.i.at1 t1.i.at2)
                           (= t2.j.at1 t1.loc_j.at2)
                           t1.location.1.at2
                           (not t1.location.0.at2)))))
      (a!11 (= (+ t1.i.at1 t1.loc_j.at1 (* (- 1) t1.i.at2)) 0))
      (a!13 (not (and (= t1.k.at1 t1.k.at2)
                      (and (= t1.i.at1 t1.i.at2) (= t1.loc_j.at1 t1.loc_j.at2))
                      t1.location.1.at2
                      t1.location.0.at2)))
      (a!15 (= (+ t1.k.at1 (* (- 1) t1.k.at2)) (- 1)))
      (a!17 (not (and (not (and t1.location.0.at1 t1.location.0.at2))
                      (or t1.location.0.at1 t1.location.0.at2))))
      (a!18 (not (and (not (and t1.location.1.at1 t1.location.1.at2))
                      (or t1.location.1.at1 t1.location.1.at2)))))
(let ((a!2 (not (and t2.EVENT.0.at1
                     (and (not t2.location.0.at1) (not t2.location.1.at1))
                     (<= 5 t2.k.at1)
                     a!1)))
      (a!5 (and t2.EVENT.0.at1
                t2.location.1.at1
                (not t2.location.0.at1)
                (not (and (= t2.k.at1 t2.k.at2)
                          (= t2.loc_i.at1 t2.loc_i.at2)
                          a!4
                          t2.location.0.at2
                          (not t2.location.1.at2)))))
      (a!7 (not (and a!6
                     (and (= t2.j.at1 t2.j.at2) (= t2.loc_i.at1 t2.loc_i.at2))
                     (not t2.location.0.at2)
                     (not t2.location.1.at2))))
      (a!12 (and t1.EVENT.0.at1
                 t1.location.1.at1
                 (not t1.location.0.at1)
                 (not (and (= t1.k.at1 t1.k.at2)
                           (= t1.loc_j.at1 t1.loc_j.at2)
                           a!11
                           t1.location.0.at2
                           (not t1.location.1.at2)))))
      (a!14 (not (and t1.EVENT.0.at1
                      (and (not t1.location.0.at1) (not t1.location.1.at1))
                      (<= 5 t1.k.at1)
                      a!13)))
      (a!16 (not (and a!15
                      (and (= t1.i.at1 t1.i.at2) (= t1.loc_j.at1 t1.loc_j.at2))
                      (not t1.location.0.at2)
                      (not t1.location.1.at2)))))
  (and true
       t2.location.1.at1
       (not t2.location.0.at1)
       (not t1.location.1.at1)
       (not t1.location.0.at1)
       (= t1.i.at1 1)
       (= t1.k.at1 0)
       (= t2.j.at1 1)
       (= t2.k.at1 0)
       (<= t1.i.at1 144)
       (<= t2.j.at1 144)
       a!2
       (not a!3)
       (not a!5)
       (not (and t2.EVENT.0.at1 t2.location.0.at1 (not t2.location.1.at1) a!7))
       (not (and t2.EVENT.0.at1 t2.location.1.at1 t2.location.0.at1 a!1))
       (or t2.EVENT.0.at1
           (and (= t2.loc_i.at1 t2.loc_i.at2)
                (= t2.k.at1 t2.k.at2)
                (= t2.j.at1 t2.j.at2)
                a!8
                a!9))
       (not a!10)
       (not (and t1.EVENT.0.at1 t2.EVENT.0.at1))
       (or t1.EVENT.0.at1 t2.EVENT.0.at1)
       (not a!12)
       a!14
       (not (and t1.EVENT.0.at1 t1.location.0.at1 (not t1.location.1.at1) a!16))
       (not (and t1.EVENT.0.at1 t1.location.1.at1 t1.location.0.at1 a!13))
       (or t1.EVENT.0.at1
           (and (= t1.loc_j.at1 t1.loc_j.at2)
                (= t1.k.at1 t1.k.at2)
                (= t1.i.at1 t1.i.at2)
                a!17
                a!18))
       (not (= t2.j.at2 1))
       (not (<= t2.j.at2 144))))))
;; interpolant computed:
(define-fun .I () Bool
  (or (not t2.location.1.at1)
      (not (= 0 t2.k.at1))
      (not (= 1 t2.j.at1))
      t1.location.1.at1)
  )

(compute-interpolant (and (interp .A) .B))
(exit)

(push 1)
(assert (and .A (not .I)))
(check-sat)
(pop 1)
(exit)
```

**Comment by kenmcmil** [comment] 2015-05-20 01:37
Great, thanks. It turns out that is caused by some propositional constant propagation done by the solver that is confusing interpolation. Apparently that just doesn't happen in Duality which is the main test bed for interpolation. The following patch should fix at least this example. I'll try to get this merged into the master branch as soon as possible. To apply the patch, use "patch -p1 <patchfile" from the main z3 directory.

diff --git a/src/interp/iz3mgr.h b/src/interp/iz3mgr.h
index 3f41383..54fb35a 100755
--- a/src/interp/iz3mgr.h
+++ b/src/interp/iz3mgr.h
@@ -279,6 +279,12 @@ class iz3mgr  {
             res[i] = arg(t,i);
     }
 
+    std::vector<ast> args(const ast &t){
+        std::vector<ast> res;
+        get_args(t,res);
+        return res;
+    }
+
     symb sym(ast t){
         raw_ast *_ast = t.raw();
         return is_app(_ast) ? to_app(_ast)->get_decl() : 0;
diff --git a/src/interp/iz3proof_itp.cpp b/src/interp/iz3proof_itp.cpp
index a788e22..3c4dae1 100755
--- a/src/interp/iz3proof_itp.cpp
+++ b/src/interp/iz3proof_itp.cpp
@@ -2218,8 +2218,12 @@ class iz3proof_itp_impl : public iz3proof_itp {
         }
         else {
             if(get_term_type(p) == LitA){
-                if(get_term_type(q) == LitA)
-                    itp = mk_false();
+                if(get_term_type(q) == LitA){
+                    if(op(q) == Or)
+                        itp = make_assumption(rng.hi,args(q));
+                    else 
+                        itp = mk_false();
+                }
                 else {
                     if(get_term_type(p_eq_q) == LitA)
                         itp = q;
diff --git a/src/interp/iz3translate.cpp b/src/interp/iz3translate.cpp
index 5b42067..36cf802 100755
--- a/src/interp/iz3translate.cpp
+++ b/src/interp/iz3translate.cpp
@@ -1702,7 +1702,7 @@ public:
                     return res;
                 }
             }
-            if(dk == PR_MODUS_PONENS && expect_clause && op(con) == Or){
+            if(dk == PR_MODUS_PONENS && expect_clause && op(con) == Or && op(conc(prem(proof,0))) == Or){
                 Iproof::node clause = translate_main(prem(proof,0),true);
                 res = RewriteClause(clause,prem(proof,1));
                 return res;
@@ -1965,6 +1965,16 @@ public:
                 res = make(commute,pf,comm_equiv);
                 break;
             }
+            case PR_AND_ELIM: {
+                std::vector<ast> rule_ax, res_conc;
+                ast piv = conc(prem(proof,0));
+                rule_ax.push_back(make(Not,piv));
+                rule_ax.push_back(con);
+                ast pf = iproof->make_axiom(rule_ax);
+                res_conc.push_back(con);
+                res = iproof->make_resolution(piv,res_conc,pf,args[0]);
+                break;
+            }
             default:
                 pfgoto(proof);
                 assert(0 && "translate_main: unsupported proof rule");

**Comment by kenmcmil** [comment] 2015-05-20 01:40
Here's a patch for the problem. Apply this with "patch -p1 <patchfile".

```
diff --git a/src/interp/iz3mgr.h b/src/interp/iz3mgr.h
index 3f41383..54fb35a 100755
--- a/src/interp/iz3mgr.h
+++ b/src/interp/iz3mgr.h
@@ -279,6 +279,12 @@ class iz3mgr  {
             res[i] = arg(t,i);
     }
 
+    std::vector<ast> args(const ast &t){
+        std::vector<ast> res;
+        get_args(t,res);
+        return res;
+    }
+
     symb sym(ast t){
         raw_ast *_ast = t.raw();
         return is_app(_ast) ? to_app(_ast)->get_decl() : 0;
diff --git a/src/interp/iz3proof_itp.cpp b/src/interp/iz3proof_itp.cpp
index a788e22..3c4dae1 100755
--- a/src/interp/iz3proof_itp.cpp
+++ b/src/interp/iz3proof_itp.cpp
@@ -2218,8 +2218,12 @@ class iz3proof_itp_impl : public iz3proof_itp {
         }
         else {
             if(get_term_type(p) == LitA){
-                if(get_term_type(q) == LitA)
-                    itp = mk_false();
+                if(get_term_type(q) == LitA){
+                    if(op(q) == Or)
+                        itp = make_assumption(rng.hi,args(q));
+                    else 
+                        itp = mk_false();
+                }
                 else {
                     if(get_term_type(p_eq_q) == LitA)
                         itp = q;
diff --git a/src/interp/iz3translate.cpp b/src/interp/iz3translate.cpp
index 5b42067..36cf802 100755
--- a/src/interp/iz3translate.cpp
+++ b/src/interp/iz3translate.cpp
@@ -1702,7 +1702,7 @@ public:
                     return res;
                 }
             }
-            if(dk == PR_MODUS_PONENS && expect_clause && op(con) == Or){
+            if(dk == PR_MODUS_PONENS && expect_clause && op(con) == Or && op(conc(prem(proof,0))) == Or){
                 Iproof::node clause = translate_main(prem(proof,0),true);
                 res = RewriteClause(clause,prem(proof,1));
                 return res;
@@ -1965,6 +1965,16 @@ public:
                 res = make(commute,pf,comm_equiv);
                 break;
             }
+            case PR_AND_ELIM: {
+                std::vector<ast> rule_ax, res_conc;
+                ast piv = conc(prem(proof,0));
+                rule_ax.push_back(make(Not,piv));
+                rule_ax.push_back(con);
+                ast pf = iproof->make_axiom(rule_ax);
+                res_conc.push_back(con);
+                res = iproof->make_resolution(piv,res_conc,pf,args[0]);
+                break;
+            }
             default:
                 pfgoto(proof);
                 assert(0 && "translate_main: unsupported proof rule");

```

**Comment by kenmcmil** [comment] 2015-05-20 01:43
Also, here's a simpler regression test. You can run this with the option `interp.check=true` to check for the bug.

```
(set-logic AUFLIA)
(declare-fun t2.j.at2 () Int)
(declare-fun t1.i.at2 () Int)
(declare-fun t1.i.at1 () Int)
(declare-fun t1.k.at2 () Int)
(declare-fun t1.k.at1 () Int)
(declare-fun t1.loc_j.at2 () Int)
(declare-fun t1.loc_j.at1 () Int)
(declare-fun t2.j.at1 () Int)
(declare-fun t2.k.at2 () Int)
(declare-fun t2.k.at1 () Int)
(declare-fun t2.loc_i.at2 () Int)
(declare-fun t2.loc_i.at1 () Int)
(declare-fun t1.i.at0 () Int)
(declare-fun t1.k.at0 () Int)
(declare-fun t1.loc_j.at0 () Int)
(declare-fun t2.j.at0 () Int)
(declare-fun t2.k.at0 () Int)
(declare-fun t2.loc_i.at0 () Int)
(declare-fun t1.location.1.at2 () Bool)
(declare-fun t1.location.1.at1 () Bool)
(declare-fun t1.location.0.at2 () Bool)
(declare-fun t1.location.0.at1 () Bool)
(declare-fun t1.EVENT.0.at1 () Bool)
(declare-fun t2.EVENT.0.at1 () Bool)
(declare-fun t2.location.1.at2 () Bool)
(declare-fun t2.location.1.at1 () Bool)
(declare-fun t2.location.0.at2 () Bool)
(declare-fun t2.location.0.at1 () Bool)
(declare-fun t1.location.1.at0 () Bool)
(declare-fun t1.location.0.at0 () Bool)
(declare-fun t1.EVENT.0.at0 () Bool)
(declare-fun t2.EVENT.0.at0 () Bool)
(declare-fun t2.location.1.at0 () Bool)
(declare-fun t2.location.0.at0 () Bool)
;; A:
(define-fun .A () Bool
  (and true
       (= t1.i.at0 1)
       (not t2.location.1.at0)
       (not (and 
                 t2.EVENT.0.at0
                 (not t2.location.1.at0)
                 (not (= t1.i.at0 t2.loc_i.at1))
            ))
       (not t2.location.0.at0)
       (or 
            t2.EVENT.0.at0
            (not  t2.location.1.at1)
       )))

;; B:
(define-fun .B () Bool
  (and true
       (= t2.j.at1 1)
       t2.location.1.at1
       (= (+ t2.j.at1 t2.loc_i.at1 (* (- 1) t2.j.at2)) 0)
       (not (<= t2.j.at2 144))
   ))

(compute-interpolant (and (interp .A) .B))

```

**Comment by kenmcmil** [comment] 2015-05-20 01:48
The patch is pushed on unstable.

**Comment by agriggio** [comment] 2015-05-20 07:20
great, thanks!

**Comment by wintersteiger** [comment] 2015-05-22 19:35
Looks to me like all problems have been solved, can we close this issue?

**Closed** 2015-05-22 20:43 UTC
