### ISSUE TITLE
Incorrect model with strings and optimize

### ISSUE THREAD

**Issue by balasub** [Z3Prover/z3#2210] opened 2019-03-29 15:51 UTC
The following small Java program produces an (incorrect) empty string model as the result:

Program:

```Java
  // demonstrates bug when using string length with Optimize
public class Demo {
  public static void stringLengthOptimizeBug() {
    Context ctx = new Context();
    Optimize optimize = ctx.mkOptimize();
    
    Expr str = ctx.mkConst("str", ctx.mkStringSort());
    IntExpr len = ctx.mkLength((SeqExpr)str);
    BitVecExpr bvExpr = ctx.mkInt2BV(32, len);
    BoolExpr expr = ctx.mkEq(bvExpr, ctx.mkBV(7, 32));
    optimize.Add(expr);
    
    BoolExpr assump[] = new BoolExpr[0]; // no assumptions here
    Status status = optimize.Check(assump);
    
    if (status == Status.SATISFIABLE)
      System.out.println(optimize.getModel().toString());
  }
  
  public static void main(String[] args) {
    stringLengthOptimizeBug();
  }  
}
```

Result: `(define-fun str () String "")`

Using a `Solver` instead of an `Optimize` produces a correct model:

```Java
// produces a correct model
public class Demo {
  public static void stringLengthOptimizeCorrect() {
    Context ctx = new Context();
    Solver s = ctx.mkSolver();
    
    Expr str = ctx.mkConst("str", ctx.mkStringSort());
    IntExpr len = ctx.mkLength((SeqExpr)str);
    BitVecExpr bvExpr = ctx.mkInt2BV(32, len);
    BoolExpr expr = ctx.mkEq(bvExpr, ctx.mkBV(7, 32));
    s.add(expr);
    
    BoolExpr assump[] = new BoolExpr[0]; // no assumptions here
    Status status = s.check();
    
    if (status == Status.SATISFIABLE)
      System.out.println(s.getModel().toString());
  }
  
  public static void main(String[] args) {
    stringLengthOptimizeCorrect();
  }  
}
```
Result: `(define-fun str () String "\x00\x00\x00\x00\x00\x00\x00")`

**Comment by NikolajBjorner** [comment] 2019-04-06 09:25
Duplicate of #2055

**Closed** 2019-05-07 01:09 UTC
Labels: duplicate
