### ISSUE TITLE
(smt.threads=2) Soundness bug on NRA formula 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4300] opened 2020-05-12 08:07 UTC
Hi,
For this case, Z3  gives an incorrect answer:
```
[715] % z3release smt.threads=2 small.smt2
unsat
[716] % z3release smt.ematching=false small.smt2
sat
[717] % cat small.smt2
(assert (exists ((a Real)) (forall ((b Real)) (exists ((c Real)) (>= (+ 8 (/ 1 (+ (/ 0 a) (- 2 b)) (- c))) 0)))))
(check-sat)
[718] %
```

OS: Ubuntu 18.04
Commit: a14c2a3

**Comment by NikolajBjorner** [comment] 2020-05-12 16:41
duplicate of other bugs related to new code

**Closed by NikolajBjorner** 2020-05-12 16:41 UTC
