### ISSUE TITLE
Problem with str.to_code/str.from_code

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#5007] opened 2021-02-09 05:40 UTC
With a fresh build of z3, for this benchmark:

```
(set-logic ALL)
(declare-fun s0 () String)
(assert (= 1 (str.len s0)))
(define-fun s1 () Int (str.to_code s0))
(assert (>= s1 0))
(check-sat)
(get-info :reason-unknown)
```

We get:

```
unknown
(:reason-unknown "Sort mismatch at argument #1 for function (declare-fun >= (Int Int) Bool) supplied sort is String")
```

While having an `unknown` result is reasonable (though not desirable), I'm more concerned with the `reason-unknown`: It does not seem to make sense, nor it seems to be a legitimate reason for being `unknown`.

I'm wondering if it's just that the reason is badly stated, or there's some other bug that causes the solver to say `unknown` here inadvertently.

**Comment by LeventErkok** [comment] 2021-02-09 06:01
Here's another example with a strange output, most likely related to the above:

```
(set-logic ALL)
(declare-fun s0 () Int)
(define-fun s1 () String (str.from_code s0))
(define-fun s2 () Int (str.to_code s1))
(define-fun s3 () Bool (= s0 s2))
(assert (not s3))
(check-sat)
(get-info :reason-unknown)
```

This produces:

```
unknown
(:reason-unknown "Sort of polymorphic function 'seq.len' does not match the declared type.
Given domain: Int
Expected domain: (Seq k!0) ")
```

which is odd because nowhere in the input is `seq.len` mentioned. Must come from some internal constraint I suppose.

**Comment by mtrberzi** [comment] 2021-02-09 15:56
I wonder if #5004 fixes this? The sort errors could be caused by the bug that this patch addresses. Essentially the wrong operators are being matched with certain helper functions.

**Comment by LeventErkok** [comment] 2021-02-09 16:14
@mtrberzi Would be happy to test and report soon as that PR lands on master.

**Comment by mtrberzi** [comment] 2021-02-09 21:33
@LeventErkok Thanks, it looks like Nikolaj has independently made the same fix that was in my PR, and that is in `master` now, so this could be fixed now if you would like to test and report.

**Comment by NikolajBjorner** [comment] 2021-02-09 22:00
@mtrberzi yes, thanks for the PR. I only started looking at PRs after that push.

**Closed by NikolajBjorner** 2021-02-09 22:00 UTC
