### ISSUE TITLE
Z3 does not respect 'timeout' when invoked via Python

### ISSUE THREAD

**Issue by ice-phoenix** [Z3Prover/z3#178] opened 2015-07-29 12:08 UTC
The following test file does not timeout after 5 seconds when invoked on `BV/wintersteiger/fmsd13/fixpoint/2012173/ethernet-fixpoint-4.smt2`:
```python
#!/usr/bin/env python2

import sys
import z3

f = sys.argv[1]

z3.set_param("timeout", 5000)

ctx = z3.Context()
z3expr = z3.parse_smt2_file(f, ctx=ctx)
z3solver = z3.Solver(ctx=ctx)
z3solver.append(z3expr)

print(z3solver.check())
```
PS: the same .smt2 also crashes regular command-line `z3` binary.

**Comment by ice-phoenix** [comment] 2015-07-29 12:11
[ice-phoenix@niobium z3-states]$ z3 --version
    Z3 version 4.4.0

**Comment by wintersteiger** [comment] 2015-07-29 14:34
Can't reproduce this one on any system using the latest unstable. Could you update to the latest version (unstable, 4.4.1) and try this one again?

**Comment by wintersteiger** [comment] 2015-07-29 15:57
Indeed, there were a couple problems with long-running functions that didn't expect to be interrupted. This is now fixed and both, the SMT2 file on the command line and via the Python script behave as intended.

**Closed by wintersteiger** 2015-07-29 15:57 UTC

**Comment by ice-phoenix** [comment] 2015-08-11 08:18
Timeout does not work with the latest `unstable` on
```
z3 timeout=5000 ./QF_ABV/stp/920763/grep0095.stp.smt2
```

**Comment by NikolajBjorner** [comment] 2015-08-11 09:04
Can you do me a favor and send the file over email? I have limited access to downloading benchmarks from where I am.
