### ISSUE TITLE
Debug branch: invalid model for QF_NIA formula  (smt.phase_selection=5)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3264] opened 2020-03-13 08:35 UTC
Hi, for the following formula, 
~~~~
(set-logic QF_NIA)
(declare-fun _substvar_18_ () Int)
(set-option :model_validate true)
(set-option :smt.phase_selection 5)
(declare-const i10 Int)
(declare-const i11 Int)
(assert (> (div 33 (* i11 i10 16 33 _substvar_18_)) 0))
(check-sat)
~~~~
z3 gives wrong answers.
~~~~
(error "line 8 column 10: an invalid model was generated")
~~~~

Commit: a02d3e9

**Comment by NikolajBjorner** [comment] 2020-03-13 23:34
duplicate of  #3269

**Closed by NikolajBjorner** 2020-03-13 23:34 UTC
Labels: Debug
