### ISSUE TITLE
Debug branch: assertion violation at emonics.cpp:538

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3349] opened 2020-03-16 03:57 UTC
Hi, for the following instance,
[emonics538.txt](https://github.com/Z3Prover/z3/files/4335975/emonics538.txt)

z3 debug branch (Commit 5c057caa4)
throws an assertion violation
~~~~
File: ../src/math/lp/emonics.cpp
Line: 538
found
~~~~

**Comment by NikolajBjorner** [comment] 2020-03-17 03:23
It is now improved to

C:\lev\build>z3 3349.smt2
ASSERTION VIOLATION
File: ..\src\math\lp\nla_core.cpp
Line: 433
!ineq_holds(ineq(cmp, t, rs))


This is almost for sure a duplicate of another related issue

**Comment by NikolajBjorner** [comment] 2020-03-17 18:27
likely duplicate of #3318

**Comment by levnach** [comment] 2020-03-17 19:23
does not assert, takes a looong time, after fix https://github.com/Z3Prover/z3/commit/684e220edb0457190025d9513a551a28c4d7f794

**Closed by levnach** 2020-03-17 19:23 UTC
Labels: Debug

**Comment by levnach** [comment] 2020-03-17 23:52
Does not happen anymore in https://github.com/Z3Prover/z3/commit/723c662608f082779a45012faef57980251fb246
