### ISSUE TITLE
Invalid model on SLIA

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5806] opened 2022-02-02 03:07 UTC
Hi, for this following formula, z3 https://github.com/Z3Prover/z3/commit/6a412f7f043690d0032a1c6cf742bdd1692df7d5 gives an invalid model.
```
$ z3 model_validate=true delta.smt2
sat
(error "line 6 column 10: an invalid model was generated")
(
  (define-fun e () String
    "ACD")
  (define-fun x () Int
    28962)
  (define-fun v () String
    "EB")
)
$ cat delta.smt2
(declare-const x Int)
(declare-fun v () String)
(declare-fun e () String)
(assert (or (= 1 x) (str.in_re (str.++ v "B") (re.* (str.to_re (str.substr v 0 x))))))
(assert (exists ((E String)) (= 1 (str.len (str.substr e (+ 1 1) 1)))))
(check-sat)
(get-model)

```

**Comment by NikolajBjorner** [comment] 2022-02-22 03:23
duplicate of #5825

**Closed by NikolajBjorner** 2022-02-22 03:23 UTC
Labels: string
