### ISSUE TITLE
[Z3py] to_smt2() does not work with FPA

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#541] opened 2016-03-29 06:20 UTC
I wanted to use `to_smt2()` to generate a testcase for a segfault that I get with commit 7eec68c but it looks like it does not generate valid code. The following example is unrelated to the segfault but illustrates the issues that I ran into:

```
$ python
>>> from z3 import *
>>> s = Solver()
>>> s.add(FP('x', Float32()) == 5.0)
>>> with open('out.txt', 'w') as f:
...     f.write(s.to_smt2())
$ cat out.txt
; benchmark generated from python API
(set-info :status unknown)
(declare-fun x () (FloatingPoint 8 24))
(assert
 (= x (_ fp.numeral @0)))
(check-sat)
$ z3 -smt2 out.txt
(error "line 3 column 33: invalid sort, symbol, '_' or '(' expected")
(error "line 5 column 4: unknown constant x")
sat
```

I'm not very familiar with the SMT2 syntax but it looks like `(FloatingPoint 8 24)` should change to `(_ FloatingPoint 8 24)` and  `@0` should be declared somewhere.

Thanks :)

**Comment by wintersteiger** [comment] 2016-03-29 15:40
Yes, that's correct. The problem is that s.to_smt2() uses a mixture of SMT version 1.0 and 2.0 and floats never existed in 1.0 times. This is fixed now, but the converter will always print decimal float-literals instead of bit-vector based `(fp #...)` literals. We'll have to do some more refactoring until all options are available in all printers, etc.

**Closed** 2016-03-29 15:39 UTC
