### ISSUE TITLE
(flaky) ASSERTION VIOLATION at ./src/ast/ast.cpp, Line: 433

### ISSUE THREAD

**Issue by zhendongsu** [Z3Prover/z3#6380] opened 2022-10-02 19:31 UTC
```
[533] % for n in $(seq 1 10) ; do z3release model_validate=true small.smt2 ; done
unknown
unknown
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 433
UNEXPECTED CODE WAS REACHED.
Z3 4.11.3.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 433
UNEXPECTED CODE WAS REACHED.
Z3 4.11.3.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
unknown
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 433
UNEXPECTED CODE WAS REACHED.
Z3 4.11.3.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
unknown
unknown
unknown
unknown
[534] % cat small.smt2
(set-option :rewriter.expand_nested_stores true)
(set-option :smt.macro_finder true)
(set-option :smt.threads 32)
(declare-fun symmetric ((Array Int (Array Int Real)) Int) Bool)
(declare-fun n () Int)
(declare-fun a0 () (Array Int (Array Int Real)))
(declare-fun e0 () Real)
(declare-fun a1 () (Array Int (Array Int Real)))
(declare-fun e1 () Real)
(declare-fun a2 () (Array Int (Array Int Real)))
(declare-fun e2 () Real)
(declare-fun a3 () (Array Int (Array Int Real)))
(declare-fun e3 () Real)
(declare-fun a4 () (Array Int (Array Int Real)))
(declare-fun e4 () Real)
(declare-fun a5 () (Array Int (Array Int Real)))
(declare-fun e5 () Real)
(declare-fun a6 () (Array Int (Array Int Real)))
(declare-fun e6 () Real)
(declare-fun a7 () (Array Int (Array Int Real)))
(declare-fun a23 () (Array Int (Array Int Real)))
(assert (forall ((qa (Array Int (Array Int Real))) (qn Int)) (= (symmetric qa qn) (forall ((qi Int) (qj Int)) (=> (and (distinct 1 qi) (= qi qn) (<= 1 qj qn)) (= (select (select qa qi) qj) (select (select qa qj) qi)))))))
(assert (symmetric a0 n))
(assert (= a1 (store a0 0 (store (select a0 0) 0 e0))))
(assert (= a2 (store a1 1 (store (select a1 1) 1 e1))))
(assert (distinct a3 (store a2 2 (store (select a2 2) 2 e2))))
(assert (= a4 (store a3 3 (store (select a3 3) 3 e3))))
(assert (= a5 (store a4 4 (store (select a4 4) 4 e4))))
(assert (= a6 (store a5 5 (store (select a5 5) 5 e5))))
(assert (= a7 (store a6 6 (store (select a6 6) 6 e6))))
(assert (not (symmetric a23 n)))
(check-sat-using (then dom-simplify purify-arith ctx-solver-simplify default))
```

**Comment by NikolajBjorner** [comment] 2023-02-04 21:46
It is a duplicate of a bug that has been fixed: expand_nested_stores creates lambda expressions. Lambdas did not get tracked correctly when copying solver states.

**Closed by NikolajBjorner** 2023-02-04 21:46 UTC
