### ISSUE TITLE
Wrong satisfiability result for FloatingPoint query on Linux for Z3 4.8.12.0 in Java

### ISSUE THREAD

**Issue by kfriedberger** [Z3Prover/z3#5487] opened 2021-08-18 07:55 UTC
The current binary for using Z3 in Java for Linux does not solve simple FloatingPoint queries correctly.
I am using the binary release available [z3-4.8.12-x64-glibc-2.31.zip](https://github.com/Z3Prover/z3/releases/download/z3-4.8.12/z3-4.8.12-x64-glibc-2.31.zip).
I assume that this is the release intended for most Linux systems.
My systems are Ubuntu 20.04 and Ubuntu 21.04, both 64bit with some Intel CPU.

The following example code was extracted from Z3's own [JavaExample](https://github.com/Z3Prover/z3/blob/5c9f4dc4d78187f582cee37ee5682536c92e9276/examples/java/JavaExample.java) (which fails identically, but is much longer to read):

```
import java.util.*;
import com.microsoft.z3.*;

public class FloatExample {

    private static Model check(Context ctx, BoolExpr f, Status sat) {
        Solver s = ctx.mkSolver();
        s.add(f);
        if (s.check() != sat)
            throw new AssertionError(String.format("%s should be %s, but solver returned %s with model [%s].", f, sat, s.check(), s.getModel()));
        if (sat == Status.SATISFIABLE)
            return s.getModel();
        else
            return null;
    }

    public static void floatingPointExample1(Context ctx) {
        FPSort s = ctx.mkFPSort(11, 53);
        System.out.println("Sort: " + s);

        FPNum x = (FPNum) ctx.mkNumeral("-1e1", s); /* -1 * 10^1 = -10 */
        FPNum y = (FPNum) ctx.mkNumeral("-10", s); /* -10 */
        FPNum z = (FPNum) ctx.mkNumeral("-1.25p3", s); /* -1.25 * 2^3 = -1.25 * 8 = -10 */
        System.out.println("x=" + x.toString() + "; y=" + y.toString() + "; z=" + z.toString());

        BoolExpr a = ctx.mkAnd(ctx.mkFPEq(x, y), ctx.mkFPEq(y, z));
        check(ctx, ctx.mkNot(a), Status.UNSATISFIABLE);
    }

    public static void main(String[] args) {
        System.out.println("Z3 Full Version String: " + Version.getFullVersion());

        HashMap<String, String> cfg = new HashMap<String, String>();
        cfg.put("model", "true");
        Context ctx = new Context(cfg);
        
        floatingPointExample1(ctx);
    }
}
```

I get the following error:
```
Z3 Full Version String: Z3 4.8.12.0
Sort: (_ FloatingPoint 11 53)
x=0; y=(- 10); z=(- 10)
Exception in thread "main" java.lang.AssertionError: (not (and (fp.eq (_ -zero 11 53) (fp #b1 #b10000000010 #x4000000000000))
          (fp.eq (fp #b1 #b10000000010 #x4000000000000)
                 (fp #b1 #b10000000010 #x4000000000000)))) should be UNSATISFIABLE, but solver returned SATISFIABLE with model [].
	at FloatExample.check(FloatExample.java:10)
	at FloatExample.floatingPointExample1(FloatExample.java:27)
	at FloatExample.main(FloatExample.java:38)
```

The problem showed up during an investigation of a SegFaults in Z3 4.8.12 for FloatingPoint operations in [JavaSMT#249](https://github.com/sosy-lab/java-smt/pull/249).

**Comment by kfriedberger** [comment] 2021-08-18 13:35
From the output, I would say, that some numbers are created wrong.
For example, the code says `FPNum x = (FPNum) ctx.mkNumeral("-1e1", s); /* -1 * 10^1 = -10 */`, but the output contains `x=0`.

**Comment by NikolajBjorner** [comment] 2021-08-18 20:37
Seems like a duplicate of #5449. The current build has:

```
FloatingPointExample1
Sort: (_ FloatingPoint 11 53)
x=(- 10); y=(- 10); z=(- 10)
OK, unsat:
(declare-fun x () (_ FloatingPoint 11 53))
```

**Closed by NikolajBjorner** 2021-08-18 20:37 UTC
