### ISSUE TITLE
Java API equals() method of class "FuncDecl" 

### ISSUE THREAD

**Issue by yzwwf** [Z3Prover/z3#143] opened 2015-06-26 03:25 UTC
I find that in the Java API, each time the method getFuncDecl() in class Expr is called, a new instance of FuncDecl will be created and returned. However, the equals() method in FuncDecl basically returns the result of "this==o". As a result, two FuncDecl instances will be "not equal", even if they refer to the same function declaration. I guess it would be more reasonable if the equals() method returns "(this.getId()==((FuncDecl)o).getId)". Moreover, the hashCode() method might also need to be modified.

The class Symbol has a similar problem.

**Comment by NikolajBjorner** [comment] 2015-06-26 06:29
yes, this is a bug.

**Comment by wintersteiger** [comment] 2015-06-26 10:25
Hold your horses. What exactly is .Equals() used for? I remember deliberately implementing operator== and .Equals() with different semantics. For instance, these are also different for AST and Sort objects. There may also be a difference between .NET and Java, I haven't had time to look into that yet.

**Comment by yzwwf** [comment] 2015-06-26 11:38
I want to collect all functions (represented by FuncDecl) appearing in an Expr and store them in a HashSet. It turns out that for a function "f", the HashSet will contain N FuncDecl instances of f, if f appears N times. I think it is more suitable for the HashSet to contain one FuncDecl instance for each function f, regardless of how many times f appears in the Expr. This is related to how equals() and hashCode() methods are implemented in FuncDecl. 
In the master branch of Z3, the equals() method of FuncDecl is implemented using "==" operator, and the hashCode() method returns super.hashCode().

**Comment by wintersteiger** [comment] 2015-06-26 11:44
That's right, those are definitely related, but I don't know whether Java uses == where .NET uses .Equals and the other way around. The Java API is to the most part automatically translated from the .NET API, so if they use different functions then this requires a fix for Java only, but for all object types, not just FuncDecls.

**Comment by NikolajBjorner** [comment] 2015-06-26 14:06
Note that in the Java API, equals on Ast uses Z3_ast native pointer comparison (equivalent to comparing the IDs), while equals on FuncDecl did not.
The .NET version of Equals calls ==, which is again defined as comparing equality of Z3_func_decl. It uses the more abstract way by calling into the C-API's equality function, but this simply checks equality of the native pointers that are hash-consed.

**Comment by wintersteiger** [comment] 2015-07-14 20:12
Indeed, the root cause was that Java doesn't allow us to overload ==. This is now fixed for AST, Sort, FuncDecl, along with compareTo in AST.

**Closed by wintersteiger** 2015-07-14 20:12 UTC
