### ISSUE TITLE
Release date for vNext / 4.8.11

### ISSUE THREAD

**Issue by Choc13** [Z3Prover/z3#5330] opened 2021-06-04 12:42 UTC
Hi, 

There were some fixes around packaging (#5290, #5288 etc) that have now been merged in to the master branch that our project requires. I wondered if you had a rough timeline for when the next release will be cut just to help us with planning on our side? 

Thanks

**Comment by NikolajBjorner** [comment] 2021-06-04 23:49
I published a pre-release. If it works for you, I will finalize the release.

**Comment by Choc13** [comment] 2021-06-05 11:03
@NikolajBjorner thanks for publishing the pre-release. I've tried running this locally on Mac and the tests seem to hang in my project now. I've also uploaded the package to a MyGet feed so that I could try it from our build server and it's causing test failures on all platforms now (Windows, Linux and Mac). See [here](https://github.com/SymbolicaDev/Symbolica/pull/12/checks?check_run_id=2752523009) for the build run. 

On Linux it seems to crash the test runner immediately, Mac OSX seems to hang and on Windows there are lots of errors of this kind:

```
Error Message:
   Microsoft.Z3.Z3Exception : Object allocation failed.
  Stack Trace:
     at Microsoft.Z3.Native.Z3_mk_context_rc(IntPtr a0)
   at Microsoft.Z3.Context..ctor()
```

It seems like this is a different issue in Z3 and not one that is related to the packaging of the runtime dependent libs.

**Comment by iscottb122** [comment] 2021-06-11 00:03
@NikolajBjorner

I have looked into the above issue reported by @Choc13 and we can change our own code to work around it easily enough. So as far as we are concerned, as users of the .NET API, we are happy that the 4.8.11 pre-release NuGet package you provided works correctly (for our purposes).

However, some of my findings may be of interest, or may save you time in future, so I will attempt to outline them here.

The tests we described as hanging/crashing would create and dispose many `Context` objects. I was able to bisect the commits between 4.8.10 and the 4.8.11 pre-release and discovered that the issue appeared in #5040, with the introduction of much larger AST hash tables. I trust that this change is beneficial for performance reasons, and with the more standard usage pattern of one or few `Context`s presumably has no downside. We are able to change our code to create only a few `Context`s, so we have no issue with this.

However, you should expect any existing memory leak issues, like that described by @GennadyGS in #5043, to be several (thousand?) times worse going forward, particularly for any users creating many `Context`s. I believe your change in f7b1469 to mitigate this issue is directionally correct, but there is almost certainly still a memory leak issue with disposed `Context`s not [deterministically disposing all of their descendants](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose). This could possibly be fixed easily in the dotnet API code, but I have not yet looked into the details or understood the implications well enough to be confident in making any large changes of this nature. Perhaps another part of Microsoft can lend you a hand here 😉.

Anyway, I just wanted to draw your attention to this in case you receive many reports of memory issues after this release. In summary, I think they are existing leaks, they are just more obvious now, and especially so with many `Context`s. This could possibly also affect the java and python bindings, but I have not looked into how they manage the lifetime of contexts and their descendants.

**Comment by NikolajBjorner** [comment] 2021-06-15 19:06
@nunoplopes - ast tables have larger default size to deal with perf deficiency during resizing. 
This exacerbates memory overhead with context objects in managed code (when managed code creates multiple objects) as explained above. Workaround on this could be to make ast table configurable to defer this memory issue for users who have to create many contexts in managed code.

A bit tough to handle in simple ways given that GC is async in .net and auxiliary Ast nodes use pointers to context. 
I don't see a basic way other than adding some other level of indirection to context pointer in managed objects and interlock-update the inner reference to the real context on destruction. Asts could "leak" on destruction, but this would be legal. Overall somewhat of a rough overhaul or worth a separate .Net API layer that is more suitable for multiple contexts.  @wintersteiger ?

**Comment by NikolajBjorner** [comment] 2021-06-15 19:07
> I have looked into the above issue reported by @Choc13 and we can change our own code to work around it easily enough.

I don't understand what your original issue was or what caused it. Perhaps the runtime dependencies changed when moving to C++17?

**Comment by wintersteiger** [comment] 2021-06-15 19:31
That's right, that would require another level of indirection. It's been a very long time since I last worked on this (or looked at it), but back then the .NET API was designed to clean up completely on destruction of context objects within the .NET API (I'm sure there are some leaks left in the unmanaged code and there may have been new ones introduced to the API since then). If I remember correctly, the .NET GC does not guarantee that all finalizers are called at the end of the program though, so there may be some spurious/legal leaks. 

I have no context of the projects being discussed here, but I haven't seen any applications that benefit from using huge numbers of context objects. To make that work with lower memory usage, one of us would have to add another layer of indirection as @NikolajBjorner suggested - either within the API or within the application. As @iscottb122 reported, it wasn't a problem to move to fewer contexts, so I don't think it's worth investing in that.

The `Object allocation failed` error on Windows may be due to changing dependencies, i.e. missing runtime DLLs, which are sometimes reported via non-obvious error messages. However, given the circumstances, I suspect that they simply mean that you ran out of memory?

**Comment by iscottb122** [comment] 2021-06-15 22:30
@wintersteiger yes, you are exactly correct. On Linux the issue simply crashed our test host process in some inscrutable way, and on WIndows it caused the `Object allocation failed` exception as reported by @Choc13. But the real underlying cause in both cases was simply exhausting the available memory. We had a few simple tests with thousands of test cases, each of which used a fresh `Context` so we could be confident that they were independent of each other. The change since Z3 4.8.10, which increased the default AST hash table size, has made this unviable. However, our tests are very simple, and the expression trees are independent anyway, so we are happy to just share a couple of `Context`s between them all and everything is fine in our world again.

@NikolajBjorner as outlined above, it was just increased memory from the AST hash table change, which we have already easily solved, and we have no runtime dependency issues from this. The rest of what I wrote was just to warn you that after this release you will probably get increased reports of mysterious memory problems from anybody who is still using many `Context`s, and to let you know where this has come from. However, as @wintersteiger said, this is probably not a common usage pattern anyway. 

Of course, if disposing of a `Context` actually did deterministically dispose of everything derived from it, rather than ultimately relying on finalizers, this issue would probably largely go away too. But from what both of you say, this could be a fairly large change in the .NET API layer and may even involve hunting down leaks in the unmanaged code.

**Comment by NikolajBjorner** [comment] 2021-06-16 02:13
> this could be a fairly large change in the .NET API layer 

I see it as follows: if an application really needs to create and tear down contexts en-masse it might want to create a custom .NET wrapper instead of using our default wrapper. This is more work, but the default use of Z3 shouldn't be around spinning up many contexts as far as I can judge: The same context can be shared within the same thread anyway. It is mostly useful for managing thread local memory access. The fact that it shows up in unit tests is understandable, but the unit test behavior is as far as I understand not representative of applications.

**Comment by nunoplopes** [comment] 2021-06-16 09:48
Right, I agree supporting hundreds of fresh contexts is not a priority. It's not a common usage scenario.
The benefits we get from the increased AST hashtable size are enormous! It's still not the final word on improvements to the AST hash table. I've identified further issues with the overflow buckets, so hopefully we can improve the hash table further in a next release.

**Closed** 2021-07-11 21:28 UTC
