### ISSUE TITLE
Multi-threading Z3 generates invalid QF_UFBV and QF_BV model

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3191] opened 2020-03-07 02:28 UTC
Hi,
For this formula:
[invalidmodel.txt](https://github.com/Z3Prover/z3/files/4301296/invalidmodel.txt)

Z3 throws out a warning
~~~~
(error "line 148 column 46: an invalid model was generated")
~~~~

The options are 
~~~~
(set-option :model_validate true)
(set-option :model true)
(set-option :smt.threads 2)
~~~~

After setting `smt.threads to 1`, the formula can be solved correctly.

OS: Ubuntu 16.04
Commit: 7d976e4 (master branch)

**Comment by rainoftime** [comment] 2020-03-07 07:12
Here is a simpler QF_BV example.
~~~~
(set-logic QF_BV)
(set-option :model_validate true)
(set-option :model true)
(set-option :smt.threads 2)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(declare-const v4 Bool)
(assert (xor v1 v1 v3 v3 v0))
(declare-const bv_28-0 (_ BitVec 28))
(assert v0)
(assert v3)
(declare-const v5 Bool)
(declare-const v6 Bool)
(declare-const v7 Bool)
(assert v0)
(declare-const v8 Bool)
(assert v3)
(declare-const v9 Bool)
(declare-const v10 Bool)
(declare-const bv_5-0 (_ BitVec 5))
(declare-const bv_18-0 (_ BitVec 18))
(assert (bvuge #b1110111010 #b1110111010))
(declare-const v11 Bool)
(assert (xor v1 v1 v3 v3 v0))
(declare-const v12 Bool)
(declare-const v16 Bool)
(assert v1)
(declare-const v17 Bool)
(assert (bvugt bv_28-0 (bvsmod bv_28-0 bv_28-0)))
(check-sat-using (then simplify bit-blast smt))
~                                              

~~~~

**Comment by NikolajBjorner** [comment] 2020-03-08 17:09
this will have to be a duplicate of another bug. It doesn't repro any longer.

**Closed by NikolajBjorner** 2020-03-08 17:09 UTC
