### ISSUE TITLE
array regression on constant arrays

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#2686] opened 2019-11-06 14:54 UTC
The default array solver doesn't handle const arrays. This appears used from SPACER.
The newest version of Z3 returns unknown, regressing from a previous version from July 2019.

; contract file: sum_run.txt
; horst files: grammar/evm-abstract-semantics-partial.txt, grammar/queries-sum_run.txt
; pre-analysis: true
; prune-strategy: aggressive
; predicate-inline-strategy: exhaustive

(declare-var B0 Bool)
(declare-var B1 Bool)
(declare-var B2 Bool)
(declare-var B3 Bool)
(declare-var B4 Bool)
(declare-var I0 Int)
(declare-var I1 Int)
(declare-var I2 Int)
(declare-var I3 Int)
(declare-var I4 Int)
(declare-var I5 Int)
(declare-var I6 Int)
(declare-var I7 Int)
(declare-var AIB0 (Array Int Bool))
(declare-var AIB1 (Array Int Bool))
(declare-var AIB2 (Array Int Bool))
(declare-var AIB3 (Array Int Bool))
(declare-var AII0 (Array Int Int))
(declare-var AII1 (Array Int Int))
(declare-var AII2 (Array Int Int))
(declare-var AII3 (Array Int Int))
(declare-rel Halt_0 ((Array Int Bool) (Array Int Int) Int))
(declare-rel isSixStored_0 ())
(declare-rel MState_0_20 (Int (Array Int Bool) (Array Int Int) (Array Int Bool) (Array Int Int) (Array Int Bool) (Array Int Int) Int))

(rule ; isSixStored_0 0
  (=> 
    (and 
      (Halt_0 AIB0 AII0 I0)
      (select AIB0 0)
      (= (select AII0 0) 6))

      isSixStored_0))
; AIB0 -> ?stor?0?r28
; AII0 -> ?stor?1?r28
; I0 -> ?cd?r28

(rule ; r_20_0 0
  (=> 
    (and 
      (MState_0_20 I0 AIB0 AII0 AIB1 AII1 AIB2 AII2 I1)
      (= B0 (select AIB0 (- I0 2)))
      (= I2 (select AII0 (- I0 2)))
      (= I3 (ite B0 (ite (= I2 0) 1 0) 0))
      (or (not B0) (not (= I3 0)))
      (= B1 (select AIB0 (- I0 3)))
      (= I4 (select AII0 (- I0 3)))
      (= AIB3 (store AIB2 0 B1))
      (= AII3 (store AII2 0 I4))
      (>= I0 2)
      (< I0 1024))

      (Halt_0 AIB3 AII3 I1)))
; AIB0 -> ?sa?0?r25
; AIB1 -> ?mem?0?r25
; AIB2 -> ?stor?0?r25
; AIB3 -> ??xt?42?1?r42
; AII0 -> ?sa?1?r25
; AII1 -> ?mem?1?r25
; AII2 -> ?stor?1?r25
; AII3 -> ??xt?42?2?r42
; B0 -> ?v?0?r21
; B1 -> ?v?0?r42
; I0 -> ?size?r25
; I1 -> ?cd?r25
; I2 -> ?v?1?r21
; I3 -> ?b?1?r26
; I4 -> ?v?1?r42

(rule ; r_14_0 0
  (=> 
    (and 
      (MState_0_20 I0 AIB0 AII0 AIB1 AII1 AIB2 AII2 I1)
      (= B0 (select AIB0 (- I0 2)))
      (= I2 (select AII0 (- I0 2)))
      (= I3 (ite B0 (ite (= I2 0) 1 0) 0))
      (or (not B0) (= I3 0))
      (= B1 (select AIB0 (- I0 2)))
      (= I4 (select AII0 (- I0 2)))
      (= B2 (select AIB0 (- I0 3)))
      (= I5 (select AII0 (- I0 3)))
      (= B3 (select AIB0 (- I0 2)))
      (= I6 (select AII0 (- I0 2)))
      (= B4 (and B2 B3))
      (= I7 (ite (and B2 B3) (mod  (+ I5 I6) 115792089237316195423570985008687907853269984665640564039457584007913129639936) 0))
      (= AIB3 (store (store (store (store AIB0 I0 true) (- I0 3) B4) (- I0 2) B1) (- I0 1) true))
      (= AII3 (store (store (store (store AII0 I0 21) (- I0 3) I7) (- I0 2) (ite B1 (mod  (- I4 1) 115792089237316195423570985008687907853269984665640564039457584007913129639936) 0)) (- I0 1) 4))
      (>= I0 2)
      (< I0 1024))

      (MState_0_20 I0 AIB3 AII3 AIB1 AII1 AIB2 AII2 I1)))
; AIB0 -> ?sa?0?r25
; AIB1 -> ?mem?0?r25
; AIB2 -> ?stor?0?r25
; AIB3 -> ??xt?33?1?r33
; AII0 -> ?sa?1?r25
; AII1 -> ?mem?1?r25
; AII2 -> ?stor?1?r25
; AII3 -> ??xt?33?2?r33
; B0 -> ?v?0?r21
; B1 -> ?v?0?r22
; B2 -> ?v1?0?r38
; B3 -> ?y?0?r39
; B4 -> ?v2?0?r36
; I0 -> ?size?r25
; I1 -> ?cd?r25
; I2 -> ?v?1?r21
; I3 -> ?b?1?r20
; I4 -> ?v?1?r22
; I5 -> ?v1?1?r38
; I6 -> ?y?1?r39
; I7 -> ?v2?1?r36

(rule ; r_14_1 0
  (=> 
    (and 
      (= AIB0 ((as const (Array Int Bool)) true))
      (= AII0 ((as const (Array Int Int)) 0))
      (= AIB1 ((as const (Array Int Bool)) false))
      (= AII1 ((as const (Array Int Int)) 0))
      (= I0 0)
      (= I1 3)
      (= AIB2 ((as const (Array Int Bool)) true))
      (= AII2 (store (store (store (store ((as const (Array Int Int)) 0) 3 21) 0 3) 1 2) 2 4)))

      (MState_0_20 I1 AIB2 AII2 AIB0 AII0 AIB1 AII1 I0)))
; AIB0 -> ??xt?44?3?r44
; AIB1 -> ??xt?44?5?r44
; AIB2 -> ??xt?33?1?r33
; AII0 -> ??xt?44?4?r44
; AII1 -> ??xt?44?6?r44
; AII2 -> ??xt?33?2?r33
; I0 -> ??xt?44?7?r44
; I1 -> ??xt?33?0?r33

(query isSixStored_0)

**Comment by NikolajBjorner** [comment] 2019-11-06 15:09
Note that it goes through with fp.spacer.weak_abs=false.
(I set some poor-mans breakpoints to figure this out)

**Comment by agurfinkel** [comment] 2019-11-06 15:27
@NikolajBjorner are you sure this is not a consequence of the recent array rewrite that introduces lambdas (quantifiers). I have been getting similar behavior with that change.

**Comment by agurfinkel** [comment] 2019-11-06 15:32
The input file got messed up by github formatting. Can you send me the original, or post it here in backquotes

**Comment by NikolajBjorner** [comment] 2019-11-06 16:36
lambdas are disabled

**Comment by agurfinkel** [comment] 2019-11-17 00:10
The cause appears to be this commit: 0a29002c2f551504f80a25071d28c5cb8042e88e

There are two co-related issues:
1. The commit fixes `smt.array.weak` to produce `unknown` instead of `sat` as desired. 
    However, it does so by detecting that the input contains an offending term. Thus the 
    result comes out `unknown` more often than before. I did not deep dive into the code 
    to see whether there are any workarounds possible to preserve some of the old behavior

2. The commit flips `m_has_unsupported_op` flag when an unsupported term under 
    `smt.array.weak=true` is detected. The flag is sticky -- once set, it is never reset unless
     the constraints are removed. This affects the previous behavior in which it was possible 
     to set the flag for one query and unset it for the next. This behaviour is highly desired
     in the current implementation of SPACER. The current behavior means that if a solver ever 
     returned `unknown` because of `smt.weak.array`, it will always return `unknown. 
     A small smt-lib file illustrating this behavior is [here](https://gist.github.com/agurfinkel/fe6cd11f68671e8c716864e36c9b5bfc).

**Comment by NikolajBjorner** [comment] 2019-11-17 01:16
regarding 2: m_found_unsupported_op is reset by pop

**Comment by agurfinkel** [comment] 2019-11-17 01:22
There is no `pop`. Look at my simplified instance. 

The sequence is `check_sat(); update_params(); check_sat()`. 
No constraints are withdrawn. The offending term is entered at a very early scope.

**Comment by agurfinkel** [comment] 2019-11-20 02:46
Unfortunately, this is becoming a critical issue. Without `weak_abs`, spacer is pretty bad on anything that has arrays. 

I haven't dived into the code to understand your fix. But one workaround is to split `m_found_unsupported_op` into two flags: `m_found_unsupported_op` and `m_found_unsupported_weak_op`. The second flag is set when something that is not supported by `smt.array.weak` is set, and is reset when `smt.array.weak` option is updated. 

Do you think this is doable?

**Comment by NikolajBjorner** [comment] 2019-11-20 05:19
It's not enough to just clear the flag. Under non-weak semantics (normal semantics) the appropriate axioms have to be instantiated. This would get ensured using propagation. So now propagation has an option to clear a backlog of instantiating select/store and other array axioms.

**Comment by agurfinkel** [comment] 2019-11-20 12:56
Fantastic! Will start using this and report if any additional problems are uncovered

**Comment by agurfinkel** [comment] 2019-11-20 13:10
You can close this issue. I checked, the original file now passes. I will re-open if there are other issues that appear.

**Closed** 2019-11-20 16:14 UTC
Labels: Horn
