### ISSUE TITLE
Soundness issues for QF_NRA formulas

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4491] opened 2020-06-02 02:41 UTC
Hi, for the following formula,
~~~~
(set-logic QF_NRA)
(set-option :model_validate true)
(declare-const r0 Real)
(declare-const r1 Real)
(assert (> (* r1 r0 r1 r0) 0.0))
(check-sat)
(get-model)
~~~~

z3 99f20c59e4 returns an invalid model
~~~~
sat
(error "line 6 column 10: an invalid model was generated")
(model 
  (define-fun r1 () Real
    0.0)
  (define-fun r0 () Real
    1.0)
)
~~~~

API log
[model.log](https://github.com/Z3Prover/z3/files/4714490/model.log)

**Comment by rainoftime** [comment] 2020-06-10 11:10
@levnach 
Could you check the following formula?
~~~~
z3 smt.arith.solver=6 f.smt2
sat

z3 smt.arith.solver=6 f.smt2
unsat
~~~~

(set-logic QF_NRA)
(declare-const r1 Real)
(declare-const r7 Real)
(declare-const r8 Real)
(push 1)
(declare-const r9 Real)
(declare-const v24 Bool)
(declare-const r10 Real)
(declare-const r12 Real)
(assert (or (<= r7 6805.0 (* (/ 7434.32 (/ (- r1 r1 r1 r1) (- r1))) r1 (- r1) (- r1)) (- (- r1))) false))
(assert (or (xor (< 7434.32 7434.32 r1) (= (/ (- r1) r10) (- (/ (- r1 r1 r1 r1) (- r1 r1 r1 r1)) (- r1) 7434.32 60773.0) r8 (- r1) 508987.0) v24) (> (/ (- r1 r1 r1 r1) (- r1 r1 r1 r1)) r10 7434.32 r12 r9) false))
(check-sat)
~~~~

**Comment by rainoftime** [comment] 2020-06-11 03:15
For the following QF_NRA instance,
both z3 arith.sovler {2, 6} give "unsat".

But CVC4, Yices2, and SMTInterpol return sat.

**Comment by NikolajBjorner** [comment] 2020-06-11 03:48
it is a bug in nlsat_solver, a duplicate of an old one on this thread.
It is a bug that doesn't involve quantifiers, so this is useful.

z3 z3arith.txt /v:10 /tr:nlsat_solver /tr:nlsat nlsat.check_lemmas=true

**Comment by NikolajBjorner** [comment] 2020-06-11 03:50
Close as this is now referenced from #4204

**Closed by NikolajBjorner** 2020-06-11 03:50 UTC
