### ISSUE TITLE
Incorrect answer on QF_FP formula with fp.roundToIntegral and RoundingMode

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3197] opened 2020-03-07 07:40 UTC
Hi,
For this formula:
```
(declare-fun a () (_ FloatingPoint 2 10))
(declare-fun b () RoundingMode)
(assert (distinct (fp.roundToIntegral b (fp.roundToIntegral b a)) (fp.roundToIntegral b a)))
(check-sat)
```
Z3  incorrectly gives sat, while this formula should be unsat.

OS: Ubuntu 18.04
Commit: 7d976e4

**Comment by wintersteiger** [comment] 2020-03-09 10:15
Duplicate of https://github.com/Z3Prover/z3/issues/2894

**Closed by wintersteiger** 2020-03-09 10:15 UTC
