### ISSUE TITLE
z3-solver fails to run on node v18

### ISSUE THREAD

**Issue by ritave** [Z3Prover/z3#6045] opened 2022-05-22 02:19 UTC
z3-solver runs correctly when run in node v17, but when environment is upgraded to node v18, the z3 fails to execute. Provided below is a stack trace.

The version of z3 is `z3-solver@4.8.17`

```
Welcome to Node.js v18.1.0.
Type ".help" for more information.
> await require('z3-solver').init();
(node:73600) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/<redacted>/node_modules/z3-solver/build/z3-built.js:4652
      throw ex;
      ^

TypeError: Failed to parse URL from /Users/<redacted>/node_modules/z3-solver/build/z3-built.wasm
    at new Request (node:internal/deps/undici/undici:4816:19)
    at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
    ... 4 lines matching cause stack trace ...
    at /Users/<redacted>/node_modules/z3-solver/build/z3-built.js:11399:11
    at init (/Users/<redacted>/node_modules/z3-solver/build/wrapper.js:373:21)
    at Object.init (/Users/<redacted>/node_modules/z3-solver/build/node-wrapper.js:20:31) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4814:25)
      at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
      at Object.fetch (node:internal/deps/undici/undici:6372:20)
      at fetch (node:internal/bootstrap/pre_execution:199:25)
      at instantiateAsync (/Users/olaftomalka/Documents/Praca/defi/tmp/node_modules/z3-solver/build/z3-built.js:6350:14)
      at createWasm (/Users/olaftomalka/Documents/Praca/defi/tmp/node_modules/z3-solver/build/z3-built.js:6382:3)
      at /Users/olaftomalka/Documents/Praca/defi/tmp/node_modules/z3-solver/build/z3-built.js:11399:11 {
    input: '/Users/<redacted>/node_modules/z3-solver/build/z3-built.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.1.0
```

**Comment by NikolajBjorner** [comment] 2022-05-22 03:02
@ritave - sources are online, https://github.com/Z3Prover/z3/tree/master/src/api/js, maybe they offer you a way to debug.
@bakkot - I have little context on where to start on this, though we want to use the distribution for the updated rise4fun in the coming 1-2 months, possibly looking into adding more user-friendly API bindings with an object model.

**Comment by bakkot** [comment] 2022-05-22 03:35
This is an [emscripten bug](https://github.com/emscripten-core/emscripten/issues/16915), caused by Node adding `WebAssembly.instantiateStreaming` in version 18. I'm sure either emscripten or node will come up with a real solution to this at some point (there's an [emscripten PR already](https://github.com/emscripten-core/emscripten/pull/16917)), but in the mean time I suspect (though I haven't checked) that you can work around this by invoking node with `--no-experimental-fetch`.

**Comment by nunoplopes** [comment] 2022-05-30 20:28
Thank you @bakkot! Closing this then.

**Closed by nunoplopes** 2022-05-30 20:28 UTC

**Comment by ritave** [comment] 2022-05-31 13:19
@nunoplopes This issue shouldn't be closed as long as the Z3 doesn't work using default options on Node >=18. As soon as Z3 is recompiled using working Emscripten and published on NPM, this should still be open

**Comment by nunoplopes** [comment] 2022-05-31 15:21
Well, if the bug is not in Z3, then there's nothing we can do about it. You may do a PR with a reasonable workaround if you'd like, but we don't have expertise to fix it for you I'm afraid.
