### ISSUE TITLE
iZ3 - Interpolator crashes

### ISSUE THREAD

**Issue by MarcusVoelker** [Z3Prover/z3#109] opened 2015-05-26 13:50 UTC
I found a test case where the ComputeInterpolant function crashes, probably with a segfault:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ff9daec8b9c, pid=8644, tid=7860
```

Here is some Java code to reproduce it:

```java
private void test() {
    HashMap<String, String> options = new HashMap<>();
    options.put("proof", "true");
    options.put("model", "true");
    InterpolationContext ctx = new InterpolationContext(options);
    BoolExpr a = ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkBoolConst("#Init"), ctx.mkBoolConst("#P0")), ctx.mkNot(ctx.mkBoolConst("#IP_2"))), ctx.mkEq(ctx.mkBoolConst("#IP_2"), ctx.mkOr(ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr"), ctx.mkInt(0))), ctx.mkAnd(ctx.mkNot(ctx.mkLe(ctx.mkDiv(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(16)), ctx.mkInt(-1))), ctx.mkOr(ctx.mkAnd(ctx.mkLe(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(1)), ctx.mkOr(ctx.mkLe(ctx.mkIntConst("#PC"), ctx.mkInt(1)), ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr"), ctx.mkInt(0)))), ctx.mkOr(ctx.mkGe(ctx.mkIntConst("#PC"), ctx.mkInt(1)), ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr"), ctx.mkInt(0))))), ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr"), ctx.mkInt(0)))))))), ctx.mkEq(ctx.mkBoolConst("#Init"), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(0)), ctx.mkEq(ctx.mkIntConst("#PC"), ctx.mkInt(0))))), ctx.mkEq(ctx.mkBoolConst("#P0"), ctx.mkLt(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(4)))), ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr"), ctx.mkInt(0))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC"), ctx.mkInt(0)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter'"), ctx.mkITE(ctx.mkGe(ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(1)), ctx.mkInt(65536)), ctx.mkInt(32768)), ctx.mkSub(ctx.mkInt(65536), ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(1)), ctx.mkInt(65536))), ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(1)), ctx.mkInt(65536)))), ctx.mkEq(ctx.mkIntConst("#PC'"), ctx.mkAdd(ctx.mkIntConst("#PC"), ctx.mkInt(1))), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'"), ctx.mkIntConst("LOOP_SIXTEEN.#adr")))))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC"), ctx.mkInt(1)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter'"), ctx.mkMod(ctx.mkIntConst("LOOP_SIXTEEN.Counter"), ctx.mkInt(16))), ctx.mkEq(ctx.mkIntConst("#PC'"), ctx.mkAdd(ctx.mkIntConst("#PC"), ctx.mkInt(1))), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'"), ctx.mkIntConst("LOOP_SIXTEEN.#adr")))))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC"), ctx.mkInt(2)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("#PC'"), ctx.mkIntConst("LOOP_SIXTEEN.#adr")), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'"), ctx.mkIntConst("LOOP_SIXTEEN.#adr")), ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter'"), ctx.mkIntConst("LOOP_SIXTEEN.Counter")))))), ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'"), ctx.mkInt(0))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC'"), ctx.mkInt(0)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter''"), ctx.mkITE(ctx.mkGe(ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter'"), ctx.mkInt(1)), ctx.mkInt(65536)), ctx.mkInt(32768)), ctx.mkSub(ctx.mkInt(65536), ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter'"), ctx.mkInt(1)), ctx.mkInt(65536))), ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter'"), ctx.mkInt(1)), ctx.mkInt(65536)))), ctx.mkEq(ctx.mkIntConst("#PC''"), ctx.mkAdd(ctx.mkIntConst("#PC'"), ctx.mkInt(1))), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr'")))))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC'"), ctx.mkInt(1)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter''"), ctx.mkMod(ctx.mkIntConst("LOOP_SIXTEEN.Counter'"), ctx.mkInt(16))), ctx.mkEq(ctx.mkIntConst("#PC''"), ctx.mkAdd(ctx.mkIntConst("#PC'"), ctx.mkInt(1))), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr'")))))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC'"), ctx.mkInt(2)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("#PC''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr'")), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr'")), ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter''"), ctx.mkIntConst("LOOP_SIXTEEN.Counter'"))))));
    BoolExpr b = ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr''"), ctx.mkInt(0)), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC''"), ctx.mkInt(0)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter'''"), ctx.mkITE(ctx.mkGe(ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter''"), ctx.mkInt(1)), ctx.mkInt(65536)), ctx.mkInt(32768)), ctx.mkSub(ctx.mkInt(65536), ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter''"), ctx.mkInt(1)), ctx.mkInt(65536))), ctx.mkMod((IntExpr) ctx.mkAdd(ctx.mkIntConst("LOOP_SIXTEEN.Counter''"), ctx.mkInt(1)), ctx.mkInt(65536)))), ctx.mkEq(ctx.mkIntConst("#PC'''"), ctx.mkAdd(ctx.mkIntConst("#PC''"), ctx.mkInt(1))), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr''")))))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC''"), ctx.mkInt(1)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter'''"), ctx.mkMod(ctx.mkIntConst("LOOP_SIXTEEN.Counter''"), ctx.mkInt(16))), ctx.mkEq(ctx.mkIntConst("#PC'''"), ctx.mkAdd(ctx.mkIntConst("#PC''"), ctx.mkInt(1))), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr''")))))), ctx.mkImplies(ctx.mkEq(ctx.mkIntConst("#PC''"), ctx.mkInt(2)), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("#PC'''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr''")), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'''"), ctx.mkIntConst("LOOP_SIXTEEN.#adr''")), ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter'''"), ctx.mkIntConst("LOOP_SIXTEEN.Counter''")))))), ctx.mkEq(ctx.mkBoolConst("#IP_2'''"), ctx.mkOr(ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'''"), ctx.mkInt(0))), ctx.mkAnd(ctx.mkNot(ctx.mkLe(ctx.mkDiv(ctx.mkIntConst("LOOP_SIXTEEN.Counter'''"), ctx.mkInt(16)), ctx.mkInt(-1))), ctx.mkOr(ctx.mkAnd(ctx.mkLe(ctx.mkIntConst("LOOP_SIXTEEN.Counter'''"), ctx.mkInt(1)), ctx.mkOr(ctx.mkLe(ctx.mkIntConst("#PC'''"), ctx.mkInt(1)), ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'''"), ctx.mkInt(0)))), ctx.mkOr(ctx.mkGe(ctx.mkIntConst("#PC'''"), ctx.mkInt(1)), ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'''"), ctx.mkInt(0))))), ctx.mkNot(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.#adr'''"), ctx.mkInt(0)))))))), ctx.mkEq(ctx.mkBoolConst("#Init'''"), ctx.mkAnd(ctx.mkEq(ctx.mkIntConst("LOOP_SIXTEEN.Counter'''"), ctx.mkInt(0)), ctx.mkEq(ctx.mkIntConst("#PC'''"), ctx.mkInt(0))))), ctx.mkEq(ctx.mkBoolConst("#P0'''"), ctx.mkLt(ctx.mkIntConst("LOOP_SIXTEEN.Counter'''"), ctx.mkInt(4)))), ctx.mkAnd(ctx.mkNot(ctx.mkBoolConst("#Init'''")), ctx.mkNot(ctx.mkBoolConst("#P0'''"))));
    BoolExpr pat = ctx.mkAnd(ctx.MkInterpolant(a), b);
    ctx.ComputeInterpolant(pat, ctx.mkParams());
    System.out.println("Everything okay");
}
```

**Comment by wintersteiger** [comment] 2015-05-27 10:22
I can't reproduce this (Windows, unstable, JDK 1.8.0_31). Could you tell us which system you're seeing this on?

**Comment by wintersteiger** [comment] 2015-05-27 10:24
This is a duplicate of #25 which has been fixed already.

**Comment by MarcusVoelker** [comment] 2015-05-27 11:25
The system I'm seeing this on is Windows, unstable, JDK 1.8.0. I can't tell the exact JDK version because I'm not at that system right now. I built the current HEAD of unstable yesterday, when I submitted the bug, so I would say it's not fixed yet. I'll see if I can dig up more information about this bug.

**Comment by kenmcmil** [comment] 2015-05-27 18:04
The interpolation code can throw some C++ exceptions that may not be caught by the C wrapper. I am reopening this.

**Comment by kenmcmil** [comment] 2015-05-27 23:07
This was caused by a problem with proof generation for Gomory cuts. The fix is in unstable. I'm leaving this issue open, however as it's not clear that the fix covers all cases.

**Comment by kenmcmil** [comment] 2015-07-10 01:04
Closing this issue since no similar errors have been reported.

**Closed by kenmcmil** 2015-07-10 01:04 UTC
