### ISSUE TITLE
Debug branch: Incorrect answers on NIRA formulas

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3157] opened 2020-03-05 07:29 UTC
Hi,
For the following formulas, z3 debug branch gives incorrect answers:

```
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(assert (exists ((d Int)) (> (/ 0.0 (+ 0.5 (ite (distinct a d) b c))) 0)))
(check-sat)
```
z3 debug branch gives sat while z3 master branch gives unsat. (Fixed levnach)

--------------
```
(declare-fun a () Int)
(declare-fun b () Int)
(assert (exists ((c Int)) (> (/ (+ c 1) (+ 0.5 (ite (= c 2) a b))) 2)))
(check-sat)
```
z3 debug branch gives unsat while z3 master branch gives sat. (Fixed levnach)

--------------
```
(declare-fun a () Real)
(declare-fun b () Int)
(assert (and (> a 1) (= 0 (/ 1 a b))))
(check-sat)
```
z3 debug branch gives unsat while the formula should be sat. (Fixed levnach)

--------------
```
(assert (exists ((a Real) (b Real)) (and (= a 2) (or (= (/ 1 a) 0) (> b 0)))))
(check-sat) 
```
z3 debug branch gives unsat while z3 master branch gives sat. (Fixed levnach)

--------------

OS: Ubuntu 18.04
Commit: c716978

**Comment by muchang** [comment] 2020-03-05 09:05
For this formula:
```
(declare-fun a () Int)
(declare-fun b () Int)
(assert (> b 0))
(assert (< (/ 1 b) (mod a b)))
(check-sat)
```
z3 debug branch gives unsat while z3 master branch gives sat.

OS: Ubuntu 18.04
Commit: c716978

**Comment by levnach** [comment] 2020-03-06 01:26
3 and 5 are fixed by https://github.com/Z3Prover/z3/commit/1d52573a47acc35823bef8f1a6f5afc469b9123c

**Comment by levnach** [comment] 2020-03-06 03:24
If I change the first one to 
(set-option :model_validate true)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(assert (exists ((d Int)) (> (/ 0.0 (+ 0.5 (ite (distinct a d) b c))) 0)))
(check-sat)
(get-model)
Then, in "debug" branch, I get no error messages, and a model 
(model 
  (define-fun c () Int
    (- 1))
  (define-fun a () Int
    0)
  (define-fun b () Int
    0)
  (define-fun /0 ((x!0 Real) (x!1 Real)) Real
    1.0)
)
This seem not to be correct since the zero divided by anything, except of the zero, should give the zero again, so the assert of the benchmark does not hold ( we cannot get the denominator zero).
In addition I dumped all the lemmas, seven in this case, produced by z3 in this scenario and ran the legacy z3 on them, getting all unsat.
I am not sure how to proceed here.

**Comment by zhendongsu** [comment] 2020-03-06 18:31
Perhaps another and somewhat simpler variant of 1 above: 
```
[901] % z3 small.smt2
unsat
[902] % z3debug small.smt2
sat
[903] % cat small.smt2
(declare-fun a () Int)
(declare-fun b () Int)
(assert (exists ((c Bool)) (= (/ 0 (- 0.5 (ite c a b))) 1)))
(check-sat)
[904] % 
```

**Comment by levnach** [comment] 2020-03-06 19:05
Debugging
(declare-fun a () Int)
(declare-fun b () Int)
(assert (exists ((c Int)) (> (/ (+ c 1) (+ 0.5 (ite (= c 2) a b))) 2)))
(check-sat)
The z3 in debug branch produces several "sat" lemma, when run as 
~/dev/z3/build/debug/z3  /home/lev/Dropbox/smts/1357_2.smt2 smt.arith.dump_lemmas=true 
The first sat lemma is lemma_7.smt2 is pasted below.
(declare-fun c!0 () Int)
(declare-fun b () Int)
(declare-fun a () Int)
(assert (= c!0 1))
(assert (let ((a!1 (+ (/ 1.0 2.0) (to_real (ite (= c!0 2) a b)))))
(let ((a!2 (* a!1 (/ (+ 1.0 (to_real c!0)) a!1)))
      (a!3 (* (- 1.0) (/ (+ 1.0 (to_real c!0)) a!1))))
  (not (= (+ a!2 a!3) 0.0)))))
(check-sat)
It is generated by "basic_lemma_for_mon_neutral_from_factors_to_monic_model_based_fm()". Here is the trace from basic_lemma_for_mon_neutral_from_factors_to_monic_model_based_fm.
lemma:1 ineqs: v4 != 1 or v16 - v14 = 0
[14]	 [(2, 1),oo]	x = (3, 0) 
root=v14
[4]	 [-oo, (1, 0)]	x = (1, 0) 
root=v4
(v16 = 2 = (v4 =1)*(v14 =3))
[16]	 [-oo, oo]	x = (2, 0) base
root=v16

expl: [14]	 [(2, 1),oo]	x = (3, 0) 
root=v14
[4]	 [-oo, (1, 0)]	x = (1, 0) 
root=v4
(v16 = 2 = (v4 =1)*(v14 =3))
[16]	 [-oo, oo]	x = (2, 0) base
root=v16
What it tells me is that v4 is equal to 1 and v16 = v4*v14, but v16 is not equal to v14, so 
I think nla_solver behaves correctly here. The generated lemma has to be unsat, but it is not. 
I am not sure how to proceed here.

**Comment by NikolajBjorner** [comment] 2020-03-09 17:18
You need to expose appropriate variables for model checking.
It only checks ground formulas.
This one reproduces the error
```
(set-option :model_validate true)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-const c Int)
(assert (> (/ (+ c 1) (+ 0.5 (ite (= c 2) a b))) 2))
(check-sat)
```

**Comment by NikolajBjorner** [comment] 2020-03-13 04:11
It is useful to add some checks. Here is a consolidated version.
```
(set-info :status sat)
(set-option :model_validate true)
(declare-fun a () Real)
(declare-fun b () Int)
(assert (and (> a 1) (= 0 (/ 1 a b))))
(check-sat)
(reset)

(set-info :status unsat)
(set-option :model_validate true)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(declare-fun d () Int)
(assert (> (/ 0.0 (+ 0.5 (ite (distinct a d) b c))) 0))
(check-sat)
(reset)

(set-info :status sat)
(set-option :model_validate true)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(assert (> (/ (+ c 1) (+ 0.5 (ite (= c 2) a b))) 2))
(check-sat)
(reset)

(set-info :status sat)
(set-option :model_validate true)
(assert (exists ((a Real) (b Real)) (and (= a 2) (or (= (/ 1 a) 0) (> b 0)))))
(check-sat) 
(reset)
(exit)
```

**Comment by levnach** [comment] 2020-03-18 18:02
Works fine now.

**Closed by levnach** 2020-03-18 18:02 UTC
Labels: Debug
