### ISSUE TITLE
Z3 gives suboptimal solution for zero/one integer program

### ISSUE THREAD

**Issue by ryanbrummet09** [Z3Prover/z3#2416] opened 2019-07-20 23:25 UTC
First off, apologies for the amount of code.  This is the smallest working example I have of the issue.

The attached optimization problem attempts to maximize the following formula where the w's are weights and the I's are [0,1] integers:

(maximize (+ 0 (* I0 W0) (* I1 W1) (* I2 W2) (* I3 W3) (* I4 W4) (* I5 W5) (* I6 W6) (* I7 W7) (* I8 W8) (* I9 W9) (* I10 W10) (* I11 W11) (* I12 W12) (* I13 W13) (* I14 W14) (* I15 W15) (* I16 W16) (* I17 W17) (* I18 W18) (* I19 W19) (* I20 W20) (* I21 W21) (* I22 W22) (* I23 W23) (* I24 W24) (* I25 W25) (* I26 W26) (* I27 W27) (* I28 W28) (* I29 W29) (* I30 W30) (* I31 W31) (* I32 W32) (* I33 W33) (* I34 W34) (* I35 W35) (* I36 W36) (* I37 W37) (* I38 W38) (* I39 W39) (* I40 W40) (* I41 W41) (* I42 W42) (* I43 W43) (* I44 W44) (* I45 W45) (* I46 W46) (* I47 W47) (* I48 W48) (* I49 W49)))

When I run the code (see attached), Z3 tells me that the optimal solution occurs when I1 and I2, only, are selected to be one (there are other variables but only the I's matter).  I don't know for a fact what the optimal solution is, but I know this isn't it because selecting I0, I1, and I2 is a feasible solution with a higher weight.  Running this code on the rise4fun site (https://rise4fun.com/Z3/tutorial/guide) validates this as all three are selected (as far as I know selecting all three is a valid solution.  The rise4fun version is 4.5.1, which I couldn't find on the git).  Note, that the code is not timing out and takes only a second or two to run.  The version I have is 4.8.6 and was downloaded from the nightly builds 7-20-19.  I have also observed this problem with a nightly 4.8.5 build as well as a few of the older stable, released versions (I'm sorry, I can't remember all the other versions that I have tried).

[InputFile.txt](https://github.com/Z3Prover/z3/files/3414051/InputFile.txt)
[OutputFile.txt](https://github.com/Z3Prover/z3/files/3414052/OutputFile.txt)

**Comment by NikolajBjorner** [comment] 2019-07-21 18:49
thanks, yes fishy

**Comment by ryanbrummet09** [comment] 2019-07-24 20:14
The problem still exists and shouldn't be closed.  Here is another example of this occurring.  I'm not sure of what the optimal answer is, but it should be possible to select I0 and I1.  See attached (I have commented out the assert statements at the end that force I0 and I1 to be added.  Both are added without problem.  Moreover, the rise4fun site is adding them while the current version adds none).

[Input2.txt](https://github.com/Z3Prover/z3/files/3428609/Input2.txt)
[output2.txt](https://github.com/Z3Prover/z3/files/3428610/output2.txt)

**Comment by NikolajBjorner** [comment] 2019-07-24 22:03
are you sure you are running current master?

**Comment by ryanbrummet09** [comment] 2019-07-24 22:05
As of this morning, yes.  I can download the current master again though and give it a try.  Is I0 and I1 being assigned on your end?

**Comment by NikolajBjorner** [comment] 2019-07-24 22:23
They are both assigned to 1 in my tests, and I get consistent results across random seeds.
The bug report exposed two bugs, the main issue that produced the sub-optimal results was due to allowing inprocessing in incremental mode even as the inprocessing would cut out solutions. 
This affected optimization problems that use pseudo-Boolean constraints.

**Comment by ryanbrummet09** [comment] 2019-07-24 22:28
Are running tests on the first input file that I sent you or the second?  The output from the first input file seems to be correct, but not the second.  On the second input file 0 is being assigned to all variables.  However, I0 and I1, at minimum, should be set to 1.  This observation is current as of the time of this post on the master branch.

**Comment by NikolajBjorner** [comment] 2019-07-25 02:04
Added second test to regressions. It fails on the macOS, but only on this platform. So it definitely exposes a remaining bug, just not always reproducible.

**Comment by ryanbrummet09** [comment] 2019-07-26 00:59
The second input above does indeed fail on macOS while it succeeds on a second non macOS platform I've tried that I listed at the bottom of this post.  However, I have found a third case that succeeds on macOS but fails on the distribution below.  So I'm not sure if this problem is completely related to the platform.  Specifically, this (third) input should succeed on I0 at minimum (I believe also on I1, I2, I3, I4, I5, I6, and I7 but I don't know for sure what the optimal solution is, that's what I've been using Z3 for :) ).

[Input3.txt](https://github.com/Z3Prover/z3/files/3433775/Input3.txt)
[output3.txt](https://github.com/Z3Prover/z3/files/3433776/output3.txt)



Fedora release 30 (Thirty)
NAME=Fedora
VERSION="30 (MATE-Compiz)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (MATE-Compiz)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="MATE-Compiz"
VARIANT_ID=matecompiz
Fedora release 30 (Thirty)
Fedora release 30 (Thirty)

**Closed** 2019-07-26 01:55 UTC
Labels: bug

**Comment by NikolajBjorner** [comment] 2019-07-26 01:58
The platform discrepancy was due to different implementations of std::sort (they order equal elements differently). I have removed this discrepancy and also used input2 to identify two real bugs, bringing the total to 4 uncovered by this use case.

**Comment by ryanbrummet09** [comment] 2019-07-27 01:20
I think things might be fixed now.  However, I am getting the following exception/warning on occasion "exception in tactic canceled".  Is this a problem or just misc log information?

**Comment by NikolajBjorner** [comment] 2019-07-27 01:24
if you have a timeout, it may reach it and then throw the canceled exception

**Comment by ryanbrummet09** [comment] 2019-07-27 17:35
OK.  I've also gotten this error/warning too (which is also new; previously I had been getting no error/warnings): "unsat during simplification".  Is this just misc log information as well?

**Comment by ryanbrummet09** [comment] 2019-07-27 17:45
I don't think this bug is fixed.  I'm getting a segmentation fault now on the following input.

[Input4.txt](https://github.com/Z3Prover/z3/files/3438437/Input4.txt)
[Input5.txt](https://github.com/Z3Prover/z3/files/3438438/Input5.txt)

**Comment by NikolajBjorner** [comment] 2019-07-28 02:29
Indeed.

I noticed that you may get much better performance for your benchmarks by disabling the PB solver alltogether.

For example,
     z3.exe input4.txt sat.cardinality.solver=false sat.pb.solver=circuit
